
(COMMON-LISP::IN-PACKAGE "COMPILER") 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T COMMON-LISP::*)
             COMMON-LISP::T)
         COMPILER::CMPERR COMPILER::CMPWARN COMPILER::WT-CVAR
         COMPILER::ADD-INIT COMPILER::INIT-NAME
         COMPILER::FAST-LINK-PROCLAIMED-TYPE-P COMPILER::C1CASE
         COMPILER::WT-INTEGER-LOC COMPILER::CMPNOTE
         COMPILER::UNWIND-EXIT COMPILER::WT-COMMENT
         COMPILER::C1LAMBDA-EXPR)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::*)
         COMPILER::C2RETURN-LOCAL COMPILER::WT-INLINE-LOC
         COMPILER::C1SYMBOL-FUN COMPILER::C2DECL-BODY
         COMPILER::COMPILER-BUILD COMPILER::NCONC-FILES
         COMPILER::C2BLOCK COMPILER::C1BODY COMPILER::C2BLOCK-LOCAL)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T
                 (COMMON-LISP::INTEGER -9223372036854775808
                     9223372036854775807))
             COMMON-LISP::T)
         COMPILER::MEMOIZED-HASH-EQUAL)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION COMMON-LISP::NIL COMMON-LISP::*)
         COMPILER::MAKE-INIT-STRING)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             ((COMMON-LISP::INTEGER -9223372036854775808
                  9223372036854775807)
              (COMMON-LISP::INTEGER -9223372036854775808
                  9223372036854775807))
             COMMON-LISP::T)
         COMPILER::MLIN)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::FIXNUM)
         COMPILER::PROCLAIMED-ARGD COMPILER::ANALYZE-REGS
         COMPILER::ANALYZE-REGS1)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T) COMMON-LISP::T)
         COMPILER::DECL-BODY-SAFETY COMPILER::C2FUNCTION
         COMPILER::C1PROGN COMPILER::C1MAPCAR COMPILER::C1FLET
         COMPILER::C1EXPR COMPILER::C1LET COMPILER::ADD-OBJECT
         COMPILER::C1LABELS COMPILER::C1FMLA-CONSTANT COMPILER::C1ECASE
         COMPILER::C1LENGTH COMPILER::C1APPLY COMPILER::THE-PARAMETER
         COMPILER::C1TAGBODY COMPILER::T3CLINES
         COMPILER::VERIFY-DATA-VECTOR COMPILER::VAR-KIND
         COMPILER::INLINE-TYPE COMPILER::C1MULTIPLE-VALUE-CALL
         COMPILER::C2GET COMPILER::ADD-CONSTANT COMPILER::T1DEFMACRO
         COMPILER::C2EXPR* COMPILER::TAG-UNWIND-EXIT
         COMPILER::CHECK-DOWNWARD COMPILER::WT-CADR
         COMPILER::CHARACTER-LOC-P COMPILER::C1DECLARE
         COMPILER::AET-C-TYPE COMPILER::C1QUOTE COMPILER::CHECK-VREF
         COMPILER::VAR-LOC COMPILER::INLINE-POSSIBLE COMPILER::SET-TOP
         COMPILER::T1ORDINARY COMPILER::BLK-VAR COMPILER::SAVE-AVMA
         COMPILER::C1VREF COMPILER::WT-VV COMPILER::C2GO-LOCAL
         COMPILER::C1MEMBER COMPILER::LTVP-EVAL COMPILER::VV-STR
         COMPILER::TAG-REF-CLB COMPILER::T2DECLARE
         COMPILER::CMP-MACROEXPAND-1 COMPILER::T1DEFINE-STRUCTURE
         COMPILER::T1DEFENTRY COMPILER::ADD-OBJECT2 COMPILER::FUN-LEVEL
         COMPILER::VAR-P COMPILER::WT-DATA-PACKAGE-OPERATION
         COMPILER::PUSH-ARGS-LISPCALL COMPILER::C1PSETQ COMPILER::C1OR
         COMPILER::C1LOCAL-FUN COMPILER::WT-VS-BASE
         COMPILER::DEFAULT-INIT COMPILER::C1MAPCON COMPILER::C1GO
         COMPILER::INFO-REFERRED-ARRAY COMPILER::BLK-REF
         COMPILER::T1DEFLA COMPILER::INFO-CHANGED-ARRAY
         COMPILER::WT-VAR-DECL COMPILER::UNWIND-NO-EXIT
         COMPILER::BLK-VALUE-TO-GO COMPILER::C2GO-CLB
         COMPILER::FUNCTION-ARG-TYPES COMPILER::C1MAPC
         COMPILER::C2DOWNWARD-FUNCTION COMPILER::CMP-MACRO-FUNCTION
         COMPILER::C1SHARP-COMMA COMPILER::ADD-ADDRESS
         COMPILER::GET-LOCAL-RETURN-TYPE COMPILER::T1DEFUN
         COMPILER::C1ADD-GLOBALS COMPILER::C2DM-RESERVE-V
         COMPILER::C1ASH COMPILER::C1STACK-LET
         COMPILER::WT-SYMBOL-FUNCTION COMPILER::C2TAGBODY-CLB
         COMPILER::C1MAPLIST COMPILER::PUSH-DATA-INCF
         COMPILER::C2TAGBODY-LOCAL COMPILER::C1FSET COMPILER::WT1
         COMPILER::VAR-REF-CCB COMPILER::INFO-P COMPILER::C1ASSOC
         COMPILER::C2GETHASH COMPILER::C1RPLACD COMPILER::C1EVAL-WHEN
         COMPILER::REP-TYPE COMPILER::C1FUNOB COMPILER::BLK-REF-CLB
         COMPILER::WT-VS* COMPILER::C1GET COMPILER::SCH-LOCAL-FUN
         COMPILER::SET-PUSH-CATCH-FRAME COMPILER::C1BOOLE3
         COMPILER::BLK-EXIT COMPILER::T1DEFCFUN COMPILER::GET-ARG-TYPES
         COMPILER::WRITE-BLOCK-OPEN COMPILER::C1COMPILER-LET
         COMPILER::ADD-LOOP-REGISTERS COMPILER::INLINE-BOOLE3-STRING
         COMPILER::C1LOAD-TIME-VALUE COMPILER::VAR-TYPE
         COMPILER::REGISTER COMPILER::RESET-INFO-TYPE
         COMPILER::C1UNWIND-PROTECT COMPILER::C1IF
         COMPILER::SHORT-FLOAT-LOC-P COMPILER::C1VAR
         COMPILER::WT-FUNCALL-C COMPILER::C1THE COMPILER::FIX-OPT
         COMPILER::UNDEFINED-VARIABLE COMPILER::C2RPLACD
         COMPILER::C1BOOLE-CONDITION COMPILER::C1NTH COMPILER::VARARG-P
         COMPILER::OBJECT-TYPE COMPILER::VOLATILE COMPILER::FUN-P
         COMPILER::VAR-REF COMPILER::C1DEFINE-STRUCTURE
         COMPILER::MAXARGS COMPILER::LONG-FLOAT-LOC-P
         COMPILER::REPLACE-CONSTANT COMPILER::C2TAGBODY-BODY
         COMPILER::TAG-P COMPILER::C1RETURN-FROM COMPILER::WT-VS
         COMPILER::ARGS-CAUSE-SIDE-EFFECT COMPILER::C1LIST-NTH
         COMPILER::FSET-FN-NAME COMPILER::SAVE-FUNOB COMPILER::C1BLOCK
         COMPILER::C1AND COMPILER::C2TAGBODY-CCB COMPILER::GET-INCLUDED
         COMPILER::TAG-REF COMPILER::NEED-TO-SET-VS-POINTERS
         COMPILER::C1VALUES COMPILER::BLK-P COMPILER::COPY-INFO
         COMPILER::WT-CAR COMPILER::FUN-CFUN
         COMPILER::C1MULTIPLE-VALUE-PROG1 SYSTEM::UNDEF-COMPILER-MACRO
         COMPILER::C1DM-BAD-KEY COMPILER::FUN-REF COMPILER::NAME-SD1
         COMPILER::MDELETE-FILE COMPILER::SAFE-SYSTEM
         COMPILER::WT-DATA2 COMPILER::WT-CDR COMPILER::C2GO-CCB
         COMPILER::C1ASH-CONDITION COMPILER::C1RPLACA
         COMPILER::WT-DATA1 COMPILER::C1RPLACA-NTHCDR
         COMPILER::NAME-TO-SD COMPILER::WT-LIST
         COMPILER::CMP-MACROEXPAND COMPILER::WT-SWITCH-CASE
         COMPILER::GET-LOCAL-ARG-TYPES COMPILER::SET-UP-VAR-CVS
         COMPILER::WT-FASD-ELEMENT COMPILER::RESULT-TYPE
         COMPILER::C1SWITCH COMPILER::FIXNUM-LOC-P
         COMPILER::C1NTHCDR-CONDITION COMPILER::TAG-VAR
         COMPILER::C1NTHCDR COMPILER::CLINK COMPILER::LTVP
         COMPILER::C1LET* COMPILER::TAG-NAME COMPILER::C1FUNCALL
         COMPILER::C2RPLACA COMPILER::MACRO-DEF-P
         COMPILER::C1STRUCTURE-REF COMPILER::GET-RETURN-TYPE
         COMPILER::C1DOWNWARD-FUNCTION COMPILER::T1CLINES
         COMPILER::TYPE-FILTER COMPILER::C1FUNCTION
         COMPILER::CONS-TO-LISTA COMPILER::C1NTH-CONDITION
         COMPILER::FUN-NAME COMPILER::PROCLAMATION COMPILER::VAR-NAME
         COMPILER::WT-CCB-VS COMPILER::FLAGS-POS COMPILER::C1CATCH
         COMPILER::CTOP-WRITE COMPILER::TAG-LABEL COMPILER::C1MEMQ
         COMPILER::C1GETHASH COMPILER::TAG-REF-CCB COMPILER::TAG-SWITCH
         COMPILER::C2BIND COMPILER::VERIFY-DATUM COMPILER::C1MAPCAN
         COMPILER::WT-DOWNWARD-CLOSURE-MACRO COMPILER::C1TERPRI
         COMPILER::FUN-REF-CCB COMMON-LISP::PROCLAIM
         COMPILER::INFO-VOLATILE COMPILER::T3ORDINARY
         COMPILER::C2LOCATION COMPILER::BLK-NAME
         COMPILER::C1STRUCTURE-SET COMPILER::C2VAR
         COMPILER::C1LOCAL-CLOSURE COMPILER::C1MACROLET
         COMPILER::WT-FUNCTION-LINK COMPILER::C2VALUES
         COMPILER::T1MACROLET COMPILER::C1MULTIPLE-VALUE-BIND
         COMPILER::C2FUNCALL-AUX COMPILER::C1MULTIPLE-VALUE-SETQ
         COMPILER::PUSH-ARGS COMPILER::BLK-REF-CCB COMPILER::C1SETQ
         COMPILER::ADD-SYMBOL COMPILER::C2VAR-KIND COMPILER::C1THROW
         COMPILER::DECLARATION-TYPE COMPILER::C1PROGV
         COMPILER::INFO-TYPE COMPILER::CONSTANT-FOLD-P
         COMPILER::C1PRINC COMPILER::WT-DOWN COMPILER::SCH-GLOBAL
         COMPILER::T1PROGN COMPILER::INFO-SP-CHANGE
         COMPILER::C2DM-RESERVE-VL COMPILER::C1MAPL
         COMPILER::FUNCTION-RETURN-TYPE COMPILER::ADD-REG1
         COMPILER::PARSE-CVSPECS COMPILER::FUN-INFO
         COMPILER::VAR-REGISTER COMPILER::SET-RETURN COMPILER::WT-H1
         COMPILER::VAR-REP-LOC)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::*) COMMON-LISP::*)
         COMPILER::INLINE-BOOLE3)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::*)
         COMPILER::C2LABELS COMPILER::C2FLET COMPILER::C2IF
         COMPILER::WT-INLINE COMPILER::C2COMPILER-LET)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T)
             COMMON-LISP::*)
         COMPILER::C1DM-V COMPILER::C1DM-VL COMPILER::C2APPLY-OPTIMIZE
         COMPILER::C2RETURN-FROM COMPILER::C2DM)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::*)
             COMMON-LISP::*)
         COMPILER::T3DEFUN-AUX)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T) COMMON-LISP::FIXNUM)
         COMPILER::F-TYPE)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::T)
         COMPILER::C2RETURN-CCB
         COMPILER::COMPILER-CLEAR-COMPILER-PROPERTIES
         COMPILER::DO-CHANGED COMPILER::CO1STRUCTURE-PREDICATE
         COMPILER::RESULT-TYPE-FROM-ARGS COMPILER::CMPFIX-ARGS
         COMPILER::T3SHARP-COMMA COMPILER::FLAGS
         COMPILER::CO1WRITE-BYTE COMPILER::CHECK-FNAME-ARGS
         COMPILER::C2ASSOC!2 COMPILER::CK-SPEC
         COMPILER::COERCE-LOC-STRUCTURE-REF COMPILER::ADD-DEBUG-INFO
         COMPILER::C2LAMBDA-EXPR-WITH-KEY COMPILER::PRIN1-CMP
         COMPILER::PUSH-CHANGED-VARS COMPILER::SHIFT>>
         COMPILER::ARGS-INFO-REFERRED-VARS
         COMPILER::C2MULTIPLE-VALUE-CALL
         COMPILER::ARGS-INFO-CHANGED-VARS COMPILER::CO1SCHAR
         COMPILER::NEXT-CVAR COMPILER::C2RETURN-CLB
         COMPILER::CO1WRITE-CHAR COMPILER::SET-VS SYSTEM::SWITCH
         COMPILER::FLAG-P COMPILER::DO-ARRAY COMPILER::INLINE-PROC
         COMPILER::CO1CONS COMPILER::C2EXPR-TOP
         COMPILER::CHANGED-LENGTH COMPILER::C2MULTIPLE-VALUE-PROG1
         COMPILER::REMOVE-FLAG COMPILER::CO1SUBLIS COMPILER::ADD-INFO
         COMPILER::C2BIND-INIT COMPILER::C2DM-BIND-VL COMPILER::C1FMLA
         COMPILER::C2CATCH COMPILER::WT-MAKE-DCLOSURE
         COMPILER::UNWIND-BDS COMPILER::IS-REP-REFERRED
         COMPILER::WT-LONG-FLOAT-VALUE COMPILER::WT-GO
         COMPILER::FAST-READ COMPILER::WT COMPILER::SAFE-COMPILE
         COMPILER::WT-H COMPILER::STRUCT-TYPE-OPT
         COMPILER::REFERRED-LENGTH COMPILER::TYPE-AND COMPILER::C2THROW
         COMPILER::NEED-TO-PROTECT COMPILER::COERCE-LOC
         COMPILER::TYPE>= COMPILER::WT-NL1 COMPILER::CHECK-END
         COMPILER::C2BLOCK-CCB COMPILER::C2LAMBDA-EXPR-WITHOUT-KEY
         COMPILER::SET-BDS-BIND COMPILER::C2DM-BIND-INIT
         COMPILER::CAN-BE-REPLACED COMPILER::MAYBE-EVAL
         COMPILER::WT-VAR COMPILER::WT-REQUIREDS
         COMPILER::CONVERT-CASE-TO-SWITCH COMPILER::CO1TYPEP
         COMPILER::C1DECL-BODY COMPILER::DOWNWARD-FUNCTION
         COMPILER::MULTIPLE-VALUE-CHECK COMPILER::NEXT-CFUN
         SYSTEM::SWITCH-FINISH COMPILER::CO1READ-CHAR
         COMPILER::COMPILER-CC COMPILER::C1PROGN*
         COMPILER::C1LAMBDA-FUN COMPILER::MAKE-USER-INIT
         COMPILER::SHIFT<< COMPILER::C1ARGS COMPILER::CK-VL
         COMPILER::T23EXPR COMPILER::IS-CHANGED COMPILER::PUSH-REFERRED
         COMPILER::WT-CHARACTER-VALUE
         COMPILER::PUSH-REFERRED-WITH-START COMPILER::NEXT-LABEL*
         COMPILER::CMPCK COMPILER::C2DM-BIND-LOC
         COMPILER::WT-SHORT-FLOAT-VALUE
         COMPILER::PUSH-CHANGED-WITH-START COMPILER::C2EXPR-TOP*
         COMPILER::DOLIST* COMPILER::WT-LABEL COMPILER::PUSH-CHANGED
         COMPILER::BASE-USED COMPILER::CO1VECTOR-PUSH
         COMPILER::WT-V*-MACROS COMPILER::CO1CONSTANT-FOLD
         COMPILER::WT-FIXNUM-VALUE COMPILER::C2BLOCK-CLB
         SYSTEM::DEFINE-INLINE-FUNCTION COMPILER::SET-JUMP-TRUE
         COMPILER::C2BIND-LOC COMPILER::IN-ARRAY
         COMPILER::SET-JUMP-FALSE COMPILER::PROCLAIM-VAR
         COMMON-LISP::DEFINE-COMPILER-MACRO COMPILER::C1CONSTANT-VALUE
         COMPILER::COMPILER-DEF-HOOK COMPILER::CO1READ-BYTE
         COMPILER::MAYBE-WT-C2DM-BIND-VL COMPILER::IS-REFERRED
         COMPILER::DOTIMES** SYSTEM::ADD-DEBUG COMPILER::DO-REFERRED
         COMPILER::NEXT-LABEL COMPILER::C2CALL-LAMBDA COMPILER::C2APPLY
         COMPILER::C1EXPR* COMPILER::C2SETQ COMPILER::MIA
         COMPILER::C2PSETQ COMPILER::C1SETQ1
         COMPILER::C2LIST-NTH-IMMEDIATE COMPILER::WT-NL
         COMPILER::CO1EQL COMPILER::CFAST-WRITE COMPILER::CO1LDB
         COMPILER::EQL-NOT-NIL COMPILER::JUMPS-TO-P
         COMPILER::C2CALL-LOCAL COMPILER::BIGNUM-EXPANSION-STORAGE
         COMPILER::STACK-LET COMPILER::C2MULTIPLE-VALUE-SETQ
         COMPILER::C2MEMBER!2 COMPILER::C2UNWIND-PROTECT
         COMPILER::DOLIST** COMPILER::SET-DBIND COMPILER::DOTIMES*
         COMPILER::NEXT-CMACRO COMPILER::GET-INLINE-LOC
         COMPILER::C2STACK-LET)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T COMMON-LISP::*)
             COMMON-LISP::*)
         COMPILER::COMPILE-FILE1)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T
                 (COMMON-LISP::ARRAY COMMON-LISP::T (COMMON-LISP::*))
                 (COMMON-LISP::INTEGER -9223372036854775808
                     9223372036854775807)
                 (COMMON-LISP::INTEGER -9223372036854775808
                     9223372036854775807)
                 COMMON-LISP::T)
             COMMON-LISP::FIXNUM)
         COMPILER::BSEARCHLEQ)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T
                 (COMMON-LISP::ARRAY COMMON-LISP::T (COMMON-LISP::*))
                 (COMMON-LISP::INTEGER -9223372036854775808
                     9223372036854775807)
                 COMMON-LISP::T)
             COMMON-LISP::FIXNUM)
         COMPILER::PUSH-ARRAY)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             ((COMMON-LISP::VECTOR COMMON-LISP::CHARACTER
                  COMMON-LISP::*))
             COMMON-LISP::T)
         COMPILER::TS COMPILER::DASH-TO-UNDERSCORE)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             ((COMMON-LISP::VECTOR COMMON-LISP::CHARACTER
                  COMMON-LISP::*)
              (COMMON-LISP::INTEGER -9223372036854775808
                  9223372036854775807)
              (COMMON-LISP::INTEGER -9223372036854775808
                  9223372036854775807))
             COMMON-LISP::T)
         COMPILER::DASH-TO-UNDERSCORE-INT)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION COMMON-LISP::NIL COMMON-LISP::T)
         COMPILER::VS-PUSH COMPILER::WFS-ERROR COMPILER::MACRO-ENV
         COMPILER::C1T COMPILER::WT-CVARS COMPILER::WT-DATA-END
         COMPILER::GAZONK-NAME COMPILER::INIT-ENV
         COMPILER::ADD-LOAD-TIME-SHARP-COMMA COMPILER::CCB-VS-PUSH
         COMPILER::WT-DATA-FILE COMPILER::WT-FASD-DATA-FILE
         COMPILER::INC-INLINE-BLOCKS COMPILER::PRINT-CURRENT-FORM
         COMPILER::CLOSE-INLINE-BLOCKS COMPILER::WT-DATA-BEGIN
         COMPILER::BABOON COMPILER::WT-C-PUSH COMPILER::WT-NEXT-VAR-ARG
         COMPILER::WT-FIRST-VAR-ARG COMPILER::CVS-PUSH
         COMPILER::TAIL-RECURSION-POSSIBLE COMPILER::RESET-TOP
         COMPILER::C1NIL COMPILER::PRINT-COMPILER-INFO)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             ((COMMON-LISP::ARRAY COMMON-LISP::T (COMMON-LISP::*)))
             COMMON-LISP::T)
         COMPILER::COPY-ARRAY)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T) COMMON-LISP::*)
         COMPILER::T1EXPR COMPILER::WT-TO-STRING COMPILER::C2OR
         COMPILER::WT-LOC COMPILER::SET-LOC COMPILER::MEXPAND-DEFTYPE
         COMPILER::C2EXPR COMPILER::C2PROGN COMPILER::C2AND
         COMPILER::WT-SHORT-FLOAT-LOC COMPILER::WT-CHARACTER-LOC
         COMPILER::CMP-EVAL COMPILER::T1EVAL-WHEN
         COMPILER::WT-LONG-FLOAT-LOC COMPILER::CMP-TOPLEVEL-EVAL
         COMPILER::WT-FIXNUM-LOC)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::*) COMMON-LISP::T)
         COMPILER::FCALLN-INLINE COMPILER::CS-PUSH COMPILER::WT-CLINK
         COMPILER::COMPILER-COMMAND COMPILER::MAKE-INFO
         COMPILER::T2PROGN COMPILER::MAKE-TAG COMPILER::C2FSET
         COMPILER::MAKE-BLK COMPILER::LIST-INLINE
         COMMON-LISP::COMPILE-FILE COMPILER::MAKE-FUN
         COMPILER::MAKE-VAR COMPILER::T3PROGN COMPILER::LIST*-INLINE)) 
(COMMON-LISP::MAPC
    (COMMON-LISP::LAMBDA (COMPILER::X)
      (COMMON-LISP::SETF
          (COMMON-LISP::GET COMPILER::X 'COMPILER::PROCLAIMED-CLOSURE)
          COMMON-LISP::T))
    '(COMMON-LISP::COMPILE COMMON-LISP::DISASSEMBLE COMPILER::CMP-ANON
         COMPILER::CMP-TMP-MACRO)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T)
             COMMON-LISP::T)
         COMPILER::T3DEFUN-VARARG COMPILER::T3DEFUN-NORMAL
         COMPILER::C2CALL-GLOBAL COMPILER::C2SWITCH COMPILER::MY-CALL
         COMPILER::C1MAKE-VAR COMPILER::WT-IF-PROCLAIMED
         COMPILER::C2STRUCTURE-REF COMPILER::C2CALL-UNKNOWN-GLOBAL
         COMPILER::WT-GLOBAL-ENTRY)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::T)
         COMPILER::T2DEFENTRY COMPILER::T3DEFENTRY COMPILER::DEFSYSFUN)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::T)
         COMPILER::C2PROGV COMPILER::WT-INLINE-COND COMPILER::C2TAGBODY
         COMPILER::CAN-BE-REPLACED* COMPILER::WT-INLINE-FIXNUM
         COMPILER::MAKE-INLINE-STRING COMPILER::WT-INLINE-SHORT-FLOAT
         COMPILER::C2LET* COMPILER::ADD-FAST-LINK
         COMPILER::C1STRUCTURE-REF1 COMPILER::GET-INLINE-INFO
         COMPILER::CHECK-FORM-TYPE COMPILER::C2MAPCAN
         COMPILER::FIX-DOWN-ARGS COMPILER::CMP-EXPAND-MACRO
         COMPILER::SUBLIS1-INLINE COMPILER::ADD-FUNCTION-PROCLAMATION
         COMPILER::ADD-FUNCTION-DECLARATION COMPILER::SET-VAR
         COMPILER::BOOLE3 COMPILER::CJF COMPILER::C2PRINC
         COMPILER::INLINE-TYPE-MATCHES COMPILER::C1MAP-FUNCTIONS
         COMPILER::C1DM COMPILER::WT-INLINE-CHARACTER
         COMPILER::WT-MAKE-CCLOSURE COMPILER::TOO-MANY-ARGS
         COMPILER::COMPILER-PASS2 COMPILER::WT-INLINE-INTEGER
         COMPILER::T3DEFCFUN COMPILER::MYSUB
         COMPILER::WT-INLINE-LONG-FLOAT COMPILER::TOO-FEW-ARGS
         COMPILER::CHECK-VDECL COMPILER::C2GO COMPILER::C2LET
         COMPILER::ASSIGN-DOWN-VARS COMPILER::C2CASE
         COMPILER::C2FUNCALL-SFUN COMPILER::AND-FORM-TYPE
         COMPILER::C-FUNCTION-NAME COMPILER::C2MAPCAR COMPILER::CJT
         COMPILER::C2MULTIPLE-VALUE-BIND COMPILER::C2MAPC)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::T)
         COMPILER::C1APPLY-OPTIMIZE COMPILER::T3DEFUN-LOCAL-ENTRY
         COMPILER::T3INIT-FUN COMPILER::C2STRUCTURE-SET)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T COMMON-LISP::*)
             COMMON-LISP::T)
         COMPILER::T3DEFUN COMPILER::T2DEFUN COMPILER::T3LOCAL-FUN
         COMPILER::T3LOCAL-DCFUN)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::*)
             COMMON-LISP::T)
         COMPILER::C2LAMBDA-EXPR COMPILER::C2FUNCALL COMPILER::LINK
         COMPILER::INLINE-ARGS)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::*)
             COMMON-LISP::T)
         COMPILER::WT-SIMPLE-CALL COMPILER::GET-OUTPUT-PATHNAME)) 