
(IN-PACKAGE "COMPILER") 
(PROCLAIM '(FTYPE (FUNCTION ((VECTOR T)) T) COPY-ARRAY)) 
(MAPC (LAMBDA (X) (SETF (GET X 'PROCLAIMED-CLOSURE) T))
      '(DISASSEMBLE CMP-ANON CMP-TMP-MACRO COMPILE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) T) WT-MAKE-DCLOSURE DO-MACRO-EXPANSION
            C2PSETQ C2DM-BIND-INIT CO1EQL MAKE-USER-INIT
            CAN-BE-REPLACED C1EXPR* SET-JUMP-TRUE CO1WRITE-CHAR
            STRUCT-TYPE-OPT SHIFT>> WT-V*-MACROS C1FMLA CO1VECTOR-PUSH
            C2MULTIPLE-VALUE-PROG1 C2RETURN-CCB T3SHARP-COMMA
            RESULT-TYPE-FROM-ARGS C2MEMBER!2 C2STACK-LET SET-BDS-BIND
            C2LIST-NTH-IMMEDIATE FAST-READ SET-JUMP-FALSE COMPILER-CC
            JUMPS-TO-P CO1CONSTANT-FOLD C2BIND-INIT NEED-TO-PROTECT
            C2CATCH SET-DBIND CO1CONS C2RETURN-CLB C2BIND-LOC
            C2MULTIPLE-VALUE-SETQ CHECK-END IS-REP-REFERRED COERCE-LOC
            C2CALL-LOCAL COERCE-LOC-STRUCTURE-REF
            CO1STRUCTURE-PREDICATE C2EXPR-TOP C2SETQ UNWIND-BDS
            ARGS-INFO-CHANGED-VARS CMPFIX-ARGS C1LAMBDA-FUN C2EXPR-TOP*
            COMPILER-CLEAR-COMPILER-PROPERTIES CO1SPECIAL-FIX-DECL
            CO1SUBLIS PRIN1-CMP C2DM-BIND-LOC SET-VS TYPE>=
            C2LAMBDA-EXPR-WITH-KEY C2UNWIND-PROTECT C2BLOCK-CCB
            C2MULTIPLE-VALUE-CALL C2ASSOC!2 C2THROW GET-INLINE-LOC
            SYSTEM::ADD-DEBUG C2LAMBDA-EXPR-WITHOUT-KEY TYPE-AND
            MULTIPLE-VALUE-CHECK WT-REQUIREDS CFAST-WRITE
            CONVERT-CASE-TO-SWITCH CO1SCHAR C2APPLY ADD-INFO
            C1CONSTANT-VALUE C1ARGS WT-VAR COMPILER-DEF-HOOK
            C2BLOCK-CLB CO1READ-CHAR C2DM-BIND-VL MAYBE-EVAL
            ARGS-INFO-REFERRED-VARS CO1READ-BYTE CO1TYPEP CO1LDB
            ADD-DEBUG-INFO CO1WRITE-BYTE PUSH-CHANGED-VARS C1SETQ1
            SHIFT<< C1PROGN*)) 
(PROCLAIM '(FTYPE (FUNCTION (T *) *) COMPILE-FILE1)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM FIXNUM) T) MLIN)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T) *) C1DM-VL C2RETURN-FROM
            C2APPLY-OPTIMIZE C1DM-V C2DM)) 
(PROCLAIM '(FTYPE (FUNCTION (T T *) *) T3DEFUN-AUX)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T) *) WT-INLINE C2FLET C2LABELS C2IF
            C2COMPILER-LET)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) T) WT-LIST C2TAGBODY-CCB C1DEFINE-STRUCTURE
            C1AND C1EVAL-WHEN C2GETHASH SYSTEM:UNDEF-COMPILER-MACRO
            C2GO-CLB ADD-REG1 WT1 TAG-P BLK-VALUE-TO-GO C1LABELS
            REPLACE-CONSTANT C1BOOLE3 C1IF TAG-REF-CLB C2TAGBODY-LOCAL
            C1MEMBER T1DEFLA C1GO BLK-NAME C1MAPC CTOP-WRITE
            VAR-REF-CCB TAG-REF C1PSETQ C1LET* C1FUNCALL FASD-PACKAGE
            C1LOCAL-FUN C1NTHCDR VAR-NAME C1LOCAL-CLOSURE C1SHARP-COMMA
            C2GO-LOCAL C2LOCATION TAG-NAME INLINE-BOOLE3-STRING
            VARARG-P T1DEFENTRY C2DOWNWARD-FUNCTION FUN-REF C1SETQ
            WT-H1 C1STACK-LET C1MAPLIST TAG-REF-CCB C1DECLARE
            VERIFY-DATA-VECTOR VAR-P C1STRUCTURE-REF C1BOOLE-CONDITION
            C1NTH GET-INCLUDED WRITE-BLOCK-OPEN REP-TYPE C2GET REGISTER
            BLK-VAR C1FUNCTION C2VAR-KIND VAR-REF C1MULTIPLE-VALUE-SETQ
            TAG-VAR C2FUNCTION CMP-MACROEXPAND-1 FUN-INFO C2TAGBODY-CLB
            WT-VS C1PROGN AET-C-TYPE C1ADD-GLOBALS BLK-REF-CCB
            C2TAGBODY-BODY C1TERPRI C1FLET T1CLINES BLK-REF-CLB
            C1VALUES VAR-TYPE BLK-REF FASD-INDEX C2EXPR* C1RPLACA
            VAR-REP-LOC WT-DATA1 C2VAR UNDEFINED-VARIABLE C1ASH
            WT-CCB-VS DEFAULT-INIT THE-PARAMETER SAFE-SYSTEM
            ADD-ADDRESS T1DEFUN C1MAPCON FUN-LEVEL DECLARATION-TYPE
            C1GET FLAGS-POS FASD-DIRECTION FASD-TABLE COPY-INFO C1VREF
            INFO-CHANGED-ARRAY WT-DATA-PACKAGE-OPERATION C1VAR
            CONSTANT-FOLD-P FUN-NAME MAXARGS C1COMPILER-LET
            FASD-FILEPOS C1MACROLET C1PROGV WT-SYMBOL-FUNCTION C1APPLY
            VAR-REGISTER FSET-FN-NAME C1MAPCAN FIX-OPT
            SET-PUSH-CATCH-FRAME C1UNWIND-PROTECT FASD-EVALD_FORMS
            UNWIND-NO-EXIT INFO-SP-CHANGE WT-DOWNWARD-CLOSURE-MACRO
            INFO-REFERRED-ARRAY SCH-LOCAL-FUN C1THROW C1MAPL
            WT-VAR-DECL C2GO-CCB C1LIST-NTH C1RETURN-FROM
            C2DM-RESERVE-VL TAG-LABEL RESET-INFO-TYPE
            C1MULTIPLE-VALUE-CALL FASD-TABLE_LENGTH FASD-STREAM WT-VS*
            VAR-KIND TYPE-FILTER C1NTHCDR-CONDITION VAR-LOC
            CMP-MACROEXPAND VOLATILE C1MULTIPLE-VALUE-BIND BLK-P
            WT-SWITCH-CASE C2RPLACD C1BLOCK C1MULTIPLE-VALUE-PROG1
            C2RPLACA INLINE-TYPE C1EXPR CLINK C1DM-BAD-KEY C1CATCH
            C1NTH-CONDITION SCH-GLOBAL C2BIND T1DEFCFUN OBJECT-TYPE
            C1OR C1ASSOC WT-DOWN INFO-VOLATILE T1PROGN C1PRINC
            C1TAGBODY PARSE-CVSPECS C1FSET C1RPLACA-NTHCDR FUN-REF-CCB
            C1DOWNWARD-FUNCTION TAG-SWITCH T3CLINES C2VALUES BLK-EXIT
            C1LENGTH C1STRUCTURE-SET FASD-EOF T1ORDINARY C1ECASE
            CHECK-VREF ARGS-CAUSE-SIDE-EFFECT ADD-LOOP-REGISTERS
            C1FMLA-CONSTANT PUSH-DATA-INCF C1LOAD-TIME-VALUE
            TAG-UNWIND-EXIT C1MAPCAR C1GETHASH NAME-TO-SD INFO-TYPE
            C1MEMQ T1DEFINE-STRUCTURE T3ORDINARY C1LET C1THE NAME-SD1
            MDELETE-FILE T1MACROLET T2DECLARE CHECK-DOWNWARD
            RESULT-TYPE MACRO-DEF-P FUN-P NEED-TO-SET-VS-POINTERS
            SET-UP-VAR-CVS C1ASH-CONDITION CONS-TO-LISTA C1QUOTE
            C1RPLACD FUN-CFUN C2DM-RESERVE-V T1DEFMACRO C1SWITCH
            INFO-P)) 
(PROCLAIM '(FTYPE (FUNCTION (STRING *) T) TS)) 
(PROCLAIM '(FTYPE (FUNCTION (*) *) INLINE-BOOLE3)) 
(PROCLAIM
    '(FTYPE (FUNCTION (*) T) C2FSET COMPILER-COMMAND CS-PUSH WT-CLINK
            LIST*-INLINE COMPILE-FILE MAKE-INFO MAKE-FUN MAKE-VAR
            MAKE-TAG LIST-INLINE MAKE-BLK)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) *) C2EXPR CMP-TOPLEVEL-EVAL CMP-EVAL
            T1EVAL-WHEN C2AND C2OR C2PROGN T1EXPR)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) FIXNUM) ANALYZE-REGS1 ANALYZE-REGS
            PROCLAIMED-ARGD)) 
(PROCLAIM '(FTYPE (FUNCTION (T FIXNUM) T) MEMOIZED-HASH-EQUAL)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T) T) C2MAPC C2MULTIPLE-VALUE-BIND
            COMPILER-PASS2 WT-IF-PROCLAIMED CJT TOO-FEW-ARGS C2LET
            WT-INLINE-LONG-FLOAT C2MAPCAN AND-FORM-TYPE
            ASSIGN-DOWN-VARS CHECK-FORM-TYPE INLINE-TYPE-MATCHES
            C1MAP-FUNCTIONS FIX-DOWN-ARGS C1STRUCTURE-REF1
            CMP-EXPAND-MACRO SUBLIS1-INLINE C1DM C2GO C2TAGBODY C2LET*
            MAKE-INLINE-STRING WT-INLINE-CHARACTER WT-INLINE-FIXNUM
            CAN-BE-REPLACED* SET-VAR WT-INLINE-INTEGER C2PROGV
            TOO-MANY-ARGS GET-INLINE-INFO T3DEFCFUN WT-MAKE-CCLOSURE
            C2CASE C2PRINC C2FUNCALL-SFUN C2MAPCAR
            WT-INLINE-SHORT-FLOAT WT-INLINE-COND C-FUNCTION-NAME CJF
            BOOLE3 MYSUB)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T) T) WT-GLOBAL-ENTRY C2SWITCH C1MAKE-VAR
            T3DEFUN-NORMAL T3DEFUN-VARARG C2STRUCTURE-REF MY-CALL
            T3INIT-FUN)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T) T) T3DEFUN C1APPLY-OPTIMIZE
            C2STRUCTURE-SET T2DEFUN T3DEFUN-LOCAL-ENTRY)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T *) T) T3LOCAL-FUN T3LOCAL-DCFUN)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T) T) DEFSYSFUN T3DEFMACRO T2DEFMACRO
            T3DEFENTRY T2DEFENTRY)) 
(PROCLAIM
    '(FTYPE (FUNCTION (STRING FIXNUM FIXNUM) T) DASH-TO-UNDERSCORE-INT)) 
(PROCLAIM '(FTYPE (FUNCTION (T T *) T) LINK C2LAMBDA-EXPR INLINE-ARGS)) 
(PROCLAIM '(FTYPE (FUNCTION (T T T *) T) GET-OUTPUT-PATHNAME)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) *) C2BLOCK-LOCAL NCONC-FILES C1SYMBOL-FUN
            C2BLOCK COMPILER-BUILD C2RETURN-LOCAL WT-INLINE-LOC)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T *) T) CMPWARN INIT-NAME ADD-INIT UNWIND-EXIT
            C1CASE WT-COMMENT C1LAMBDA-EXPR CMPNOTE CMPERR)) 
(PROCLAIM '(FTYPE (FUNCTION (STRING) T) DASH-TO-UNDERSCORE)) 
(PROCLAIM '(FTYPE (FUNCTION (T) FIXNUM) F-TYPE)) 
(PROCLAIM
    '(FTYPE (FUNCTION NIL T) VS-PUSH C1NIL PRINT-CURRENT-FORM
            WT-DATA-FILE CVS-PUSH INC-INLINE-BLOCKS
            TAIL-RECURSION-POSSIBLE WT-C-PUSH CCB-VS-PUSH
            CLOSE-INLINE-BLOCKS GAZONK-NAME WT-DATA-BEGIN WT-DATA-END
            WT-FASD-DATA-FILE ADD-LOAD-TIME-SHARP-COMMA C1T WFS-ERROR
            WT-CVARS PRINT-COMPILER-INFO BABOON)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T (VECTOR T) FIXNUM T) FIXNUM) PUSH-ARRAY)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T (VECTOR T) FIXNUM FIXNUM T) FIXNUM)
            BSEARCHLEQ)) 