(make-package :slot-accessor-name :use '(:cl) :nicknames '(:s-a-n))
(make-package :walker :use '(:cl))
(make-package :iterate :use '(:cl :walker))
(make-package :pcl :use '(:cl :iterate :walker :s))
(import 'si::std-instance :pcl)
(import 'si::funcallable-std-instance :pcl)
