
(IN-PACKAGE "PCL") 
(PROCLAIM
    '(FTYPE (FUNCTION NIL T)
            INITIALIZE-CHECKING-OR-CACHING-FUNCTION-LIST MAKE-ARG-INFO
            RENEW-SYS-FILES ALLOCATE-FUNCALLABLE-INSTANCE-1
            SHOW-DFUN-CONSTRUCTORS MAKE-CACHE SHOW-EMF-CALL-TRACE
            INITIAL-DISPATCH-DFUN-INFO DISPATCH-DFUN-INFO
            IN-THE-COMPILER-P UPDATE-DISPATCH-DFUNS
            SHOW-FREE-CACHE-VECTORS NO-METHODS-DFUN-INFO
            %%ALLOCATE-INSTANCE--CLASS DEFAULT-METHOD-ONLY-DFUN-INFO
            BOOTSTRAP-META-BRAID GET-EFFECTIVE-METHOD-GENSYM
            STRUCTURE-FUNCTIONS-EXIST-P LIST-ALL-DFUNS MAKE-CPD
            CACHES-TO-ALLOCATE INITIAL-DFUN-INFO
            ALLOCATE-FUNCALLABLE-INSTANCE-2 BOOTSTRAP-BUILT-IN-CLASSES)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) *) DEFAULT-CODE-CONVERTER
            MAKE-FINAL-DISPATCH-DFUN PROTOTYPES-FOR-MAKE-METHOD-LAMBDA
            FIND-STRUCTURE-CLASS EARLY-COLLECT-INHERITANCE
            EMIT-ONE-INDEX-WRITERS NET-CODE-CONVERTER
            MAKE-DISPATCH-DFUN *NORMALIZE-TYPE COMPILE-IIS-FUNCTIONS
            GENERIC-FUNCTION-NAME-P EMIT-IN-CHECKING-CACHE-P
            EMIT-ONE-CLASS-READER GET-GENERIC-FUNCTION-INFO
            COMPUTE-APPLICABLE-METHODS-EMF ANALYZE-LAMBDA-LIST
            EMIT-ONE-INDEX-READERS EARLY-METHOD-FUNCTION PCL-DESCRIBE
            TYPE-FROM-SPECIALIZER FIND-WRAPPER METHOD-PROTOTYPE-FOR-GF
            SPECIALIZER-FROM-TYPE STRUCTURE-WRAPPER
            GET-DISPATCH-FUNCTION EMIT-TWO-CLASS-READER
            PARSE-METHOD-GROUP-SPECIFIER CLASS-EQ-TYPE
            EMIT-CONSTANT-VALUE EMIT-TWO-CLASS-WRITER
            CONVERT-TO-SYSTEM-TYPE PARSE-DEFMETHOD
            EMIT-ONE-CLASS-WRITER)) 
(PROCLAIM
    '(FTYPE (FUNCTION (*) T) |__si::MAKE-CACHING| |__si::MAKE-N-N|
            MAKE-INITIALIZE-INFO |__si::MAKE-NO-METHODS|
            |__si::MAKE-TWO-CLASS| INTERN-PV-TABLE
            |__si::MAKE-ARG-INFO| |__si::MAKE-ONE-INDEX-DFUN-INFO|
            FIX-EARLY-GENERIC-FUNCTIONS CALLED-FIN-WITHOUT-FUNCTION
            MAKE-FAST-METHOD-CALL STRING-APPEND |__si::MAKE-ONE-INDEX|
            |__si::MAKE-INITIAL| |__si::MAKE-CHECKING| ZERO
            |__si::MAKE-PV-TABLE| MAKE-PROGN FALSE MAKE-PV-TABLE
            WALKER::UNBOUND-LEXICAL-FUNCTION |__si::MAKE-DISPATCH|
            USE-PACKAGE-PCL TRUE |__si::MAKE-DEFAULT-METHOD-ONLY|
            |__si::MAKE-INITIAL-DISPATCH| |__si::MAKE-CONSTANT-VALUE|
            |__si::MAKE-DFUN-INFO| |__si::MAKE-STD-INSTANCE|
            MAKE-METHOD-CALL |__si::MAKE-CLASS-PRECEDENCE-DESCRIPTION|
            MAKE-FAST-INSTANCE-BOUNDP |__si::MAKE-ACCESSOR-DFUN-INFO|
            |STRUCTURE-OBJECT class constructor| |__si::MAKE-CACHE|
            |__si::MAKE-ONE-CLASS| PV-WRAPPERS-FROM-PV-ARGS)) 
(PROCLAIM '(FTYPE (FUNCTION (T) (OR CACHE NULL)) PV-TABLE-CACHE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T *) *) MAKE-METHOD-FUNCTION-INTERNAL
            PARSE-METHOD-OR-SPEC MAKE-METHOD-LAMBDA-INTERNAL
            COERCE-TO-CLASS MAKE-FINAL-DFUN-INTERNAL GET-FUNCTION
            EXTRACT-DECLARATIONS COMPILE-LAMBDA GET-FUNCTION1
            MAKE-CACHING-DFUN GET-METHOD-FUNCTION DISPATCH-DFUN-COST
            MACROEXPAND-ALL PARSE-SPECIALIZED-LAMBDA-LIST ENSURE-CLASS
            WALK-FORM MAKE-INSTANCE-1 GET-DFUN-CONSTRUCTOR
            MAP-ALL-CLASSES ENSURE-GENERIC-FUNCTION
            MAKE-CONSTANT-VALUE-DFUN)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) T) ACCESSOR-MISS-FUNCTION ADD-TO-CVECTOR
            QUALIFIER-CHECK-RUNTIME SET-FUNCTION-PRETTY-ARGLIST
            ADD-DIRECT-SUBCLASSES REMOVE-METHOD SET-WRAPPER
            DOCTOR-DFUN-FOR-THE-DEBUGGER MAKE-PLIST
            SYMBOL-OR-CONS-LESSP MAKE-STD-BOUNDP-METHOD-FUNCTION
            UPDATE-CPL METHODS-CONVERTER MAKE-DFUN-ARG-LIST
            MAKE-DISCRIMINATING-FUNCTION-ARGLIST
            STANDARD-INSTANCE-ACCESS REMTAIL DO-SATISFIES-DEFTYPE
            CPL-FORWARD-REFERENCED-CLASS-ERROR FIND-STANDARD-II-METHOD
            MAKE-UNORDERED-METHODS-EMF UPDATE-INITIALIZE-INFO-INTERNAL
            ADD-METHOD COMPUTE-PV |SETF PCL FIND-CLASS-PREDICATE|
            PROCLAIM-DEFMETHOD UPDATE-ALL-PV-TABLE-CACHES
            ITERATE::SIMPLE-EXPAND-ITERATE-FORM CLASS-MIGHT-PRECEDE-P
            MEC-ALL-CLASSES SET-FUNCALLABLE-INSTANCE-FUNCTION
            MAKE-DFUN-LAMBDA-LIST CHECKING-DFUN-INFO
            METHOD-FUNCTION-RETURNING-T PV-WRAPPERS-FROM-ALL-WRAPPERS
            SET-METHODS ITERATE::MV-SETQ SUPERCLASSES-COMPATIBLE-P
            SLOT-EXISTS-P SWAP-WRAPPERS-AND-SLOTS DESCRIBE-PACKAGE
            VALUE-FOR-CACHING SAUT-NOT-PROTOTYPE
            SET-STANDARD-SVUC-METHOD PLIST-VALUE AUGMENT-TYPE
            UPDATE-CLASS N-N-DFUN-INFO VARIABLE-SPECIAL-P
            UPDATE-STD-OR-STR-METHODS ADD-FORMS MAKE-CAXR
            MAKE-DLAP-LAMBDA-LIST REDIRECT-EARLY-FUNCTION-INTERNAL
            GET-KEY-ARG1 EMIT-N-WRAPPER-COMPUTE-PRIMARY-CACHE-LOCATION
            MAKE-INTERNAL-READER-METHOD-FUNCTION |SETF PCL FIND-CLASS|
            COMPUTE-CALLS PROCLAIM-DEFGENERIC WALKER::NOTE-DECLARATION
            SYSTEM:%SET-COMPILED-FUNCTION-NAME VARIABLE-LEXICAL-P
            CANONICALIZE-DEFCLASS-OPTION RAISE-METATYPE
            PARSE-QUALIFIER-PATTERN SAUT-NOT-CLASS-EQ
            MAKE-PV-TABLE-INTERNAL WALKER::ENVIRONMENT-FUNCTION
            COMPUTE-APPLICABLE-METHODS-FUNCTION
            EMIT-1-WRAPPER-COMPUTE-PRIMARY-CACHE-LOCATION
            PV-TABLE-LOOKUP VARIABLE-CLASS
            MAKE-FAST-METHOD-CALL-LAMBDA-LIST |SETF PCL GDEFINITION|
            NET-CONSTANT-CONVERTER WALKER::VARIABLE-SYMBOL-MACRO-P
            SYMBOL-LESSP GF-MAKE-FUNCTION-FROM-EMF
            REMOVE-DIRECT-SUBCLASSES UPDATE-INITS
            |SETF PCL METHOD-FUNCTION-PLIST| COMPUTE-STD-CPL
            CPL-INCONSISTENT-ERROR CHANGE-CLASS-INTERNAL
            FIND-SLOT-DEFINITION COMPUTE-LAYOUT NO-SLOT
            %SET-CCLOSURE-ENV COMPUTE-CONSTANTS
            SET-STRUCTURE-SVUC-METHOD GET-KEY-ARG REMOVE-SLOT-ACCESSORS
            MAKE-CDXR MEMF-CONSTANT-CONVERTER BOOTSTRAP-SLOT-INDEX
            CLASS-CAN-PRECEDE-P MEC-ALL-CLASSES-INTERNAL
            CLASSES-HAVE-COMMON-SUBCLASS-P MAKE-CLASS-PREDICATE
            SAUT-NOT-CLASS DESTRUCTURE-INTERNAL
            ITERATE::EXTRACT-SPECIAL-BINDINGS MAKE-EARLY-ACCESSOR
            MAP-PV-TABLE-REFERENCES-OF MAKE-STD-WRITER-METHOD-FUNCTION
            FUNCALLABLE-STANDARD-INSTANCE-ACCESS
            METHOD-FUNCTION-RETURNING-NIL MEC-ALL-CLASS-LISTS
            ADD-SLOT-ACCESSORS EMIT-1-NIL-DLAP
            MAKE-STD-READER-METHOD-FUNCTION
            CANONICALIZE-SLOT-SPECIFICATION LIST-EQ REAL-REMOVE-METHOD
            WALKER::ENVIRONMENT-MACRO SAUT-NOT-EQL UPDATE-SLOTS
            DEAL-WITH-ARGUMENTS-OPTION PRINTING-RANDOM-THING-INTERNAL
             WALKER::WALK-REPEAT-EVAL
            PV-WRAPPERS-FROM-ALL-ARGS WALKER::NOTE-LEXICAL-BINDING)) 
(PROCLAIM '(FTYPE (FUNCTION (T) (INTEGER 1 255)) CACHE-NKEYS)) 
(PROCLAIM '(FTYPE (FUNCTION (T) (INTEGER 1 256)) CACHE-LINE-SIZE)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM T T) *) COMPUTE-CACHE-PARAMETERS)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM T *) *) FIND-FREE-CACHE-LINE)) 
(PROCLAIM '(FTYPE (FUNCTION (T) FIELD-TYPE) CACHE-FIELD)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) FUNCTION) CACHE-LIMIT-FN
            FAST-METHOD-CALL-FUNCTION METHOD-CALL-FUNCTION)) 
(MAPC (LAMBDA (COMPILER::X)
        (SETF (GET COMPILER::X 'SYSTEM::PROCLAIMED-CLOSURE) T))
      '(TRACE-METHOD-INTERNAL FDEFINE-CAREFULLY DO-STANDARD-DEFSETF-1
           REDEFINE-FUNCTION)) 
(PROCLAIM
    '(FTYPE (FUNCTION (FIXNUM FIXNUM T) FIXNUM)
            COMPUTE-PRIMARY-CACHE-LOCATION)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T FIXNUM *) T) GET-CACHE-FROM-CACHE
            COMPUTE-PRIMARY-CACHE-LOCATION-FROM-LOCATION)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) (VALUES T T)) MAKE-KEYWORD
            MAKE-CLASS-PREDICATE-NAME)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T *) T) FIND-CLASS-PREDICATE FIND-CLASS-CELL
            USE-CONSTANT-VALUE-DFUN-P MAKE-EARLY-GF ITERATE::MAYBE-WARN
            TRACE-METHOD ALLOCATE-FUNCALLABLE-INSTANCE WALKER::RELIST
            UPDATE-DFUN USE-DISPATCH-DFUN-P PV-TABLE-LOOKUP-PV-ARGS
            MAKE-WRAPPER EARLY-METHOD-SPECIALIZERS
            INITIALIZE-METHOD-FUNCTION MAKE-FINAL-DFUN
            WALKER::WALKER-ENVIRONMENT-BIND-1 MAKE-TYPE-PREDICATE-NAME
            ALLOCATE-STRUCTURE-INSTANCE MAKE-SPECIALIZABLE
            CAPITALIZE-WORDS SET-DFUN ITERATE::FUNCTION-LAMBDA-P
            FIND-CLASS INITIALIZE-INTERNAL-SLOT-GFS SET-ARG-INFO
            WALKER::RELIST* ALLOCATE-STANDARD-INSTANCE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) *) SAUT-NOT ENSURE-CLASS-VALUES
            EMIT-CHECKING EMIT-DEFAULT-ONLY-FUNCTION EMIT-DEFAULT-ONLY
            SAUT-CLASS CLASS-APPLICABLE-USING-CLASS-P EMIT-CACHING
            DESTRUCTURE GET-NEW-FUNCTION-GENERATOR-INTERNAL
            COMPUTE-TEST MAKE-DIRECT-SLOTD SLOT-NAME-LISTS-FROM-SLOTS
            SAUT-EQL INSURE-DFUN CHECK-INITARGS-VALUES
            SET-FUNCTION-NAME INITIAL-DFUN COMPUTE-STD-CPL-PHASE-1
            *SUBTYPEP COMPUTE-APPLICABLE-METHODS-USING-TYPES
            SDFUN-FOR-CACHING INVOKE-EMF SPLIT-DECLARATIONS
            GENERATE-FAST-CLASS-SLOT-ACCESS-P COMPUTE-CODE SLOT-VALUE
            SPECIALIZER-APPLICABLE-USING-TYPE-P SLOT-BOUNDP
            FORM-LIST-TO-LISP ITERATE::PARSE-DECLARATIONS
            MAKE-INSTANCE-FUNCTION-TRAP SAUT-PROTOTYPE
            MUTATE-SLOTS-AND-CALLS SAUT-AND SAUT-CLASS-EQ
            FIND-SUPERCLASS-CHAIN SLOT-UNBOUND-INTERNAL
            UPDATE-SLOT-VALUE-GF-INFO SLOT-MAKUNBOUND)) 
(PROCLAIM
    '(FTYPE (FUNCTION NIL *) EMIT-N-N-WRITERS EMIT-N-N-READERS
            COUNT-ALL-DFUNS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) T) CHECKING-FUNCTION
            METHOD-CALL-CALL-METHOD-ARGS EARLY-COLLECT-CPL
            METHOD-FUNCTION-PV-TABLE ECD-OTHER-INITARGS
            BOOTSTRAP-CLASS-PREDICATES CONSTANT-SYMBOL-P GDEFINITION
            %FBOUNDP INITIALIZE-INFO-CACHED-MAKE-INSTANCE-FUNCTION
            MAKE-INSTANCE-FUNCTION-SYMBOL FGEN-TEST
            GF-PRECOMPUTE-DFUN-AND-EMF-P VARIABLE-GLOBALLY-SPECIAL-P
            SLOT-INITARGS-FROM-STRUCTURE-SLOTD ARG-INFO-P
            STRUCTURE-TYPE-INTERNAL-SLOTDS CCLOSUREP CHECKING-CACHE
            GF-LAMBDA-LIST
            MAKE-OPTIMIZED-STRUCTURE-SLOT-VALUE-USING-CLASS-METHOD-FUNCTION
            STRUCTURE-SVUC-METHOD DISPATCH-CACHE
            BOOTSTRAP-ACCESSOR-DEFINITIONS FINAL-ACCESSOR-DFUN-TYPE
            SETFBOUNDP ONE-CLASS-P EARLY-GF-P UPDATE-C-A-M-GF-INFO
            FGEN-GENSYMS SORT-SLOTS MAKE-CLASS-EQ-PREDICATE N-N-CACHE
            SFUN-P DFUN-ARG-SYMBOL
            INITIALIZE-INFO-CACHED-DEFAULT-INITARGS-FUNCTION
            EARLY-METHOD-STANDARD-ACCESSOR-SLOT-NAME
            MAKE-TYPE-PREDICATE SORT-CALLS
            MAKE-STRUCTURE-SLOT-BOUNDP-FUNCTION TWO-CLASS-WRAPPER1
            USE-DEFAULT-METHOD-ONLY-DFUN-P FGEN-SYSTEM
            CACHING-DFUN-COST CPD-CLASS CACHING-CACHE
            INITIAL-DISPATCH-P LOOKUP-FGEN
            COMPUTE-APPLICABLE-METHODS-EMF-STD-P COMPUTE-LINE-SIZE
            GF-INFO-STATIC-C-A-M-EMF FAST-INSTANCE-BOUNDP-P
            N-N-ACCESSOR-TYPE KEYWORD-SPEC-NAME DEFAULT-TEST-CONVERTER
            RESET-INITIALIZE-INFO INITIAL-P
            INITIALIZE-INFO-CACHED-MAKE-INSTANCE-FUNCTION-SYMBOL
            EXPAND-MAKE-INSTANCE-FORM STRUCTURE-SLOT-BOUNDP
            STANDARD-SVUC-METHOD TWO-CLASS-INDEX
            EARLY-CLASS-PRECEDENCE-LIST MAKE-INITIAL-DFUN GMAKUNBOUND
            METHODS-CONTAIN-EQL-SPECIALIZER-P EXPAND-SHORT-DEFCOMBIN
            ACCESSOR-DFUN-INFO-CACHE MAKE-CALL-METHODS
            STRUCTURE-SLOTD-NAME ALLOCATE-CACHE-VECTOR
            RESET-CLASS-INITIALIZE-INFO GET-SETF-FUNCTION-NAME
            METHOD-CALL-P LEGAL-CLASS-NAME-P EXTRACT-PARAMETERS
            EARLY-SLOT-DEFINITION-NAME ECD-METACLASS DISPATCH-P
            METHOD-FUNCTION-PLIST %STD-INSTANCE-SLOTS
            CANONICAL-SLOT-NAME CONSTANT-VALUE-DFUN-INFO
            FUNCTION-RETURNING-T FUNCTION-PRETTY-ARGLIST
            STRUCTURE-TYPE-SLOT-DESCRIPTION-LIST CHECK-WRAPPER-VALIDITY
            INITIALIZE-INFO-P CPD-AFTER
            MAKE-OPTIMIZED-STRUCTURE-SETF-SLOT-VALUE-USING-CLASS-METHOD-FUNCTION
            ONE-INDEX-INDEX WALKER::ENV-DECLARATIONS
            STRUCTURE-SLOTD-TYPE MAKE-DEFAULT-METHOD-GROUP-DESCRIPTION
            EVAL-FORM LIST-DFUN
            INITIALIZE-INFO-CACHED-SHARED-INITIALIZE-T-FUNCTION
            CACHE-OWNER FAST-METHOD-CALL-PV-CELL DFUN-INFO-P
            UPDATE-PV-TABLE-CACHE-INFO EARLY-CLASS-SLOTDS
            FUNCTION-RETURNING-NIL ECD-CLASS-NAME
            TWO-CLASS-ACCESSOR-TYPE EARLY-CLASS-DEFINITION
            FAST-METHOD-CALL-P INITIALIZE-INFO-CACHED-RI-VALID-P
            COMPUTE-MCASE-PARAMETERS GF-DFUN-INFO
            INITIALIZE-INFO-CACHED-COMBINED-INITARGS-FORM-LIST
            EARLY-METHOD-LAMBDA-LIST ONE-CLASS-WRAPPER0
            CLASS-PRECEDENCE-DESCRIPTION-P GET-MAKE-INSTANCE-FUNCTIONS
            EXPAND-LONG-DEFCOMBIN MAP-SPECIALIZERS
            EARLY-CLASS-DIRECT-SUBCLASSES WALKER::ENV-WALK-FORM
            STRUCTURE-TYPE-INCLUDED-TYPE-NAME
            ONE-INDEX-DFUN-INFO-ACCESSOR-TYPE GBOUNDP ECD-SOURCE
            CLASS-FROM-TYPE INITIALIZE-INFO-CACHED-NEW-KEYS
            ARG-INFO-NKEYS DEFAULT-CONSTANT-CONVERTER
            INITIALIZE-INFO-CACHED-COMBINED-INITIALIZE-FUNCTION
            STORE-FGEN EARLY-METHOD-STANDARD-ACCESSOR-P
            INTERN-FUNCTION-NAME NET-TEST-CONVERTER ARG-INFO-KEY/REST-P
            COMPLICATED-INSTANCE-CREATION-METHOD
            FTYPE-DECLARATION-FROM-LAMBDA-LIST
            GENERIC-CLOBBERS-FUNCTION DEFAULT-STRUCTUREP
            GF-INFO-C-A-M-EMF-STD-P ARG-INFO-VALID-P
            FORMAT-CYCLE-REASONS FAST-METHOD-CALL-ARG-INFO
            GET-MAKE-INSTANCE-FUNCTION-SYMBOL %STD-INSTANCE-WRAPPER
            SLOT-BOUNDP-SYMBOL INITIAL-CACHE
            METHOD-FUNCTION-NEEDS-NEXT-METHODS-P
            SYSTEM:%COMPILED-FUNCTION-NAME MAKE-CALLS-TYPE-DECLARATION
            UPDATE-CLASS-CAN-PRECEDE-P SLOT-READER-SYMBOL FREE-CACHE
            DNET-METHODS-P CONSTANT-VALUE-CACHE
            GET-BUILT-IN-CLASS-SYMBOL UPDATE-GFS-OF-CLASS
            ONE-CLASS-CACHE STD-INSTANCE-P ONE-INDEX-CACHE
            STRUCTURE-SLOTD-WRITER-FUNCTION FGEN-GENERATOR-LAMBDA
            EXTRACT-SPECIALIZER-NAMES EARLY-SLOT-DEFINITION-LOCATION
            DO-STANDARD-DEFSETFS-FOR-DEFCLASS %CCLOSURE-ENV
            EARLY-ACCESSOR-METHOD-SLOT-NAME ACCESSOR-DFUN-INFO-P
            INFORM-TYPE-SYSTEM-ABOUT-STD-CLASS SLOT-WRITER-SYMBOL
            ARG-INFO-KEYWORDS INITIALIZE-INFO-WRAPPER
            FAST-METHOD-CALL-NEXT-METHOD-CALL INITIAL-DISPATCH-CACHE
            NEXT-WRAPPER-FIELD
            INITIALIZE-INFO-CACHED-INITARGS-FORM-LIST CHECKING-P
            EXTRACT-REQUIRED-PARAMETERS GET-BUILT-IN-WRAPPER-SYMBOL
            INITIALIZE-INFO-CACHED-CONSTANTS
            STRUCTURE-SLOTD-READER-FUNCTION EARLY-METHOD-CLASS
            STRUCTURE-OBJECT-P DEFAULT-METHOD-ONLY-CACHE
            PARSE-SPECIALIZERS INTERN-EQL-SPECIALIZER
            COMPILE-LAMBDA-DEFERRED MAKE-CONSTANT-FUNCTION
            MAKE-PV-TYPE-DECLARATION ARG-INFO-APPLYP
            GET-PV-CELL-FOR-CLASS ONE-INDEX-DFUN-INFO-INDEX
            UNENCAPSULATED-FDEFINITION CHECK-CACHE
            WALKER::GET-IMPLEMENTATION-DEPENDENT-WALKER-TEMPLATE
            INITIALIZE-INFO-KEY ONE-CLASS-INDEX SYSTEM:%STRUCTURE-NAME
            SLOT-VECTOR-SYMBOL MAKE-PV-TABLE-TYPE-DECLARATION
            TWO-CLASS-CACHE PROCLAIM-INCOMPATIBLE-SUPERCLASSES
            BUILT-IN-OR-STRUCTURE-WRAPPER1 ECD-SUPERCLASS-NAMES
            STRUCTURE-TYPE CLASS-HAS-A-FORWARD-REFERENCED-SUPERCLASS-P
            N-N-P INTERNED-SYMBOL-P DEFAULT-METHOD-ONLY-P
            EARLY-CLASS-SLOTS NO-METHODS-P ARG-INFO-NUMBER-OPTIONAL
            ONE-INDEX-P GET-MAKE-INSTANCE-FUNCTION EARLY-CLASS-NAME
            METHOD-FUNCTION-FROM-FAST-FUNCTION MAKE-PERMUTATION-VECTOR
            ONE-CLASS-ACCESSOR-TYPE TWO-CLASS-P BUILT-IN-WRAPPER-OF
            FREE-CACHE-VECTOR GET-CACHE-VECTOR ARG-INFO-LAMBDA-LIST
            UPDATE-GF-INFO ONE-INDEX-DFUN-INFO-CACHE %SYMBOL-FUNCTION
            ACCESSOR-DFUN-INFO-ACCESSOR-TYPE FUNCALLABLE-INSTANCE-P
            ECD-CANONICAL-SLOTS EARLY-COLLECT-SLOTS
            INITIALIZE-INFO-CACHED-VALID-P UNPARSE-SPECIALIZERS
            GF-INFO-FAST-MF-P
            MAKE-OPTIMIZED-STRUCTURE-SLOT-BOUNDP-USING-CLASS-METHOD-FUNCTION
            EARLY-CLASS-NAME-OF GF-DFUN-CACHE CLASS-PREDICATE
            EXTRACT-LAMBDA-LIST CLASS-OF COPY-CACHE SYMBOL-PKG-NAME
            ONE-INDEX-DFUN-INFO-P WRAPPER-OF METHOD-FUNCTION-METHOD
            CPD-SUPERS DEFAULT-STRUCTURE-INSTANCE-P
            STRUCTURE-SLOTD-INIT-FORM EARLY-METHOD-QUALIFIERS
            LIST-LARGE-CACHE UPDATE-GF-SIMPLE-ACCESSOR-TYPE TYPE-CLASS
            MAKE-EQL-PREDICATE EARLY-GF-NAME UPDATE-ALL-C-A-M-GF-INFO
            FLUSH-CACHE-VECTOR-INTERNAL ITERATE::SEQUENCE-ACCESSOR
            MAP-ALL-GENERIC-FUNCTIONS STRUCTURE-TYPE-P
            FIND-CYCLE-REASONS DEFAULT-STRUCTURE-TYPE
            COMPUTE-CLASS-SLOTS WRAPPER-FOR-STRUCTURE
            INITIALIZE-INFO-CACHED-SHARED-INITIALIZE-NIL-FUNCTION
            USE-CACHING-DFUN-P EARLY-COLLECT-DEFAULT-INITARGS
            DEFAULT-SECONDARY-DISPATCH-FUNCTION ONE-INDEX-ACCESSOR-TYPE
            WALKER::ENV-WALK-FUNCTION WALKER::ENV-LOCK
            STRUCTURE-SLOTD-ACCESSOR-SYMBOL
            METHOD-LL->GENERIC-FUNCTION-LL CACHE-P WRAPPER-FIELD
            INITIALIZE-INFO-BOUND-SLOTS DEFAULT-CONSTANTP
            MAKE-FUNCTION-INLINE COMPUTE-STD-CPL-PHASE-2
            CACHING-DFUN-INFO CONSTANT-VALUE-P
            WALKER::GET-WALKER-TEMPLATE ARG-INFO-METATYPES COUNT-DFUN
            MAKE-INITFUNCTION WALKER::ENV-LEXICAL-VARIABLES PV-TABLEP
            COMPILE-LAMBDA-UNCOMPILED UNDEFMETHOD-1
            GF-INFO-SIMPLE-ACCESSOR-TYPE FORCE-CACHE-FLUSHES
            DFUN-INFO-CACHE GFS-OF-TYPE TWO-CLASS-WRAPPER0
            ITERATE::VARIABLES-FROM-LET SHOW-DFUN-COSTS
            ARG-INFO-PRECEDENCE FGEN-GENERATOR
            RESET-CLASS-INITIALIZE-INFO-1 CACHING-P NO-METHODS-CACHE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (*) *) INVALID-METHOD-ERROR
            METHOD-COMBINATION-ERROR UNTRACE-METHOD
            UPDATE-MAKE-INSTANCE-FUNCTION-TABLE LIST-LARGE-CACHES)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) LIST) CACHE-OVERFLOW PV-TABLE-SLOT-NAME-LISTS
            PV-TABLE-CALL-LIST)) 
(PROCLAIM '(FTYPE (FUNCTION (T) BOOLEAN) CACHE-VALUEP)) 
(PROCLAIM '(FTYPE (FUNCTION NIL FIXNUM) GET-WRAPPER-CACHE-NUMBER)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM T) T) %CCLOSURE-ENV-NTHCDR)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T) *)
            COMPUTE-DISCRIMINATING-FUNCTION-ARGLIST-INFO-INTERNAL
            WALK-METHOD-LAMBDA
            |(FAST-METHOD ADD-READER-METHOD (SLOT-CLASS T T))|
            |(FAST-METHOD SLOT-VALUE-USING-CLASS (STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
            |(FAST-METHOD SHARED-INITIALIZE :AFTER (CLASS-EQ-SPECIALIZER T))|
            |(FAST-METHOD COMPUTE-EFFECTIVE-METHOD (GENERIC-FUNCTION LONG-METHOD-COMBINATION T))|
            |(FAST-METHOD SHARED-INITIALIZE :BEFORE (STANDARD-METHOD T))|
            |(FAST-METHOD (SETF DOCUMENTATION) (T STANDARD-SLOT-DEFINITION))|
            |(FAST-METHOD (SETF CLASS-SLOT-VALUE) (T STD-CLASS T))|
            |(FAST-METHOD (SETF SLOT-ACCESSOR-FUNCTION) (T EFFECTIVE-SLOT-DEFINITION T))|
            |(FAST-METHOD SHARED-INITIALIZE :BEFORE (CLASS T))|
            ADD-METHOD-DECLARATIONS
            |(FAST-METHOD SHARED-INITIALIZE :AFTER (STANDARD-SLOT-DEFINITION T))|
            MAKE-TWO-CLASS-ACCESSOR-DFUN
            |(FAST-METHOD SHARED-INITIALIZE :AFTER (EQL-SPECIALIZER T))|
            |(FAST-METHOD SHARED-INITIALIZE :AFTER (STANDARD-ACCESSOR-METHOD T))|
            |(FAST-METHOD SHARED-INITIALIZE :BEFORE (STANDARD-GENERIC-FUNCTION T))|
            |(FAST-METHOD SLOT-VALUE-USING-CLASS (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
            |(FAST-METHOD ADD-BOUNDP-METHOD (SLOT-CLASS T T))|
            |(FAST-METHOD ADD-WRITER-METHOD (SLOT-CLASS T T))|
            |(FAST-METHOD UPDATE-INSTANCE-FOR-DIFFERENT-CLASS (STANDARD-OBJECT STANDARD-OBJECT))|
            |(FAST-METHOD SHARED-INITIALIZE (SLOT-OBJECT T))|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T) *)
            |(FAST-METHOD UPDATE-INSTANCE-FOR-REDEFINED-CLASS (STANDARD-OBJECT T T T))|
            ITERATE::ITERATE-TRANSFORM-BODY)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T *) *) ITERATE::RENAME-LET-BINDINGS
            MAKE-EFFECTIVE-METHOD-FUNCTION-SIMPLE1)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T) *) CONSTANT-VALUE-MISS
            EMIT-ONE-OR-N-INDEX-READER/WRITER CACHING-MISS
            CACHE-MISS-VALUES
            |(FAST-METHOD COMPUTE-DISCRIMINATING-FUNCTION-ARGLIST-INFO (STANDARD-GENERIC-FUNCTION))|
            WALKER::WALK-FORM-INTERNAL
            GET-OPTIMIZED-STD-ACCESSOR-METHOD-FUNCTION
            SLOT-VALUE-USING-CLASS-DFUN SLOT-BOUNDP-USING-CLASS-DFUN
            |(FAST-METHOD METHOD-FUNCTION (STANDARD-METHOD))|
            |(FAST-METHOD CLASS-PROTOTYPE (STD-CLASS))|
            |(FAST-METHOD METHOD-QUALIFIERS (TRACED-METHOD))|
            MAKE-FINAL-CONSTANT-VALUE-DFUN CHECK-METHOD-ARG-INFO
            MAKE-OPTIMIZED-STD-BOUNDP-METHOD-FUNCTION
            MAKE-FINAL-CACHING-DFUN EMIT-READER/WRITER-FUNCTION
            SET-SLOT-VALUE
            |(FAST-METHOD CLASS-PROTOTYPE (STRUCTURE-CLASS))|
            WALKER::WALK-LET-IF ACCESSOR-VALUES1
            |(FAST-METHOD METHOD-LAMBDA-LIST (TRACED-METHOD))|
            ITERATE::EXPAND-INTO-LET OPTIMIZE-SLOT-VALUE-BY-CLASS-P
            ITERATE::RENAME-VARIABLES
            EMIT-ONE-OR-N-INDEX-READER/WRITER-FUNCTION CHECKING-MISS
            |(FAST-METHOD METHOD-SPECIALIZERS (TRACED-METHOD))|
            ACCESSOR-VALUES-INTERNAL GET-CLASS-SLOT-VALUE-1
            LOAD-LONG-DEFCOMBIN
            |(FAST-METHOD ACCESSOR-METHOD-SLOT-NAME (TRACED-METHOD))|
            |(FAST-METHOD FUNCTION-KEYWORDS (STANDARD-METHOD))|
            MAKE-OPTIMIZED-STD-WRITER-METHOD-FUNCTION
            |(FAST-METHOD MAKE-INSTANCES-OBSOLETE (SYMBOL))|
            MAKE-OPTIMIZED-STD-READER-METHOD-FUNCTION
            EMIT-READER/WRITER GENERATING-LISP
            MAKE-FINAL-N-N-ACCESSOR-DFUN
            |(FAST-METHOD METHOD-PRETTY-ARGLIST (STANDARD-METHOD))|
            ITERATE::WALK-GATHERING-BODY
            |(FAST-METHOD COMPUTE-DISCRIMINATING-FUNCTION (STANDARD-GENERIC-FUNCTION))|
            GET-OPTIMIZED-STD-SLOT-VALUE-USING-CLASS-METHOD-FUNCTION
            CONVERT-METHODS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T) *) BOOTSTRAP-ACCESSOR-DEFINITION
            INITIALIZE-INSTANCE-SIMPLE-FUNCTION
            |(FAST-METHOD INITIALIZE-INSTANCE (SLOT-OBJECT))|
            ORDER-SPECIALIZERS MAKE-ONE-CLASS-ACCESSOR-DFUN
            |(FAST-METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION (SLOT-CLASS T))|
            |(FAST-METHOD DOCUMENTATION (STANDARD-SLOT-DEFINITION))|
            GET-ACCESSOR-FROM-SVUC-METHOD-FUNCTION
            |(FAST-METHOD ALLOCATE-INSTANCE (STRUCTURE-CLASS))|
            SETF-SLOT-VALUE-USING-CLASS-DFUN
            GENERATE-DISCRIMINATION-NET
            MAKE-FINAL-ONE-INDEX-ACCESSOR-DFUN
            |(FAST-METHOD CLASS-SLOT-VALUE (STD-CLASS T))|
            |(FAST-METHOD DESCRIBE-OBJECT (T T))| ACCESSOR-VALUES
            LOAD-SHORT-DEFCOMBIN SET-CLASS-SLOT-VALUE-1
            |(FAST-METHOD MAKE-INSTANCE (SYMBOL))|
            REAL-MAKE-METHOD-LAMBDA EMIT-CHECKING-OR-CACHING-FUNCTION
            |(FAST-METHOD DESCRIBE-OBJECT (STANDARD-GENERIC-FUNCTION T))|
            |(FAST-METHOD DEFAULT-INITARGS (SLOT-CLASS T))|
            MAKE-SHARED-INITIALIZE-FORM-LIST
            |(FAST-METHOD DESCRIBE-OBJECT (SLOT-OBJECT T))|
            ACCESSOR-MISS |(FAST-METHOD NO-APPLICABLE-METHOD (T))|
            MAKE-FINAL-CHECKING-DFUN
            |(FAST-METHOD COMPUTE-APPLICABLE-METHODS-USING-CLASSES (GENERIC-FUNCTION T))|
            GET-ACCESSOR-METHOD-FUNCTION
            |(FAST-METHOD SLOTS-TO-INSPECT (SLOT-CLASS SLOT-OBJECT))|
            |(FAST-METHOD LEGAL-QUALIFIERS-P (STANDARD-METHOD T))|
            |(FAST-METHOD REINITIALIZE-INSTANCE :AFTER (SLOT-CLASS))|
            |(FAST-METHOD LEGAL-SPECIALIZERS-P (STANDARD-METHOD T))|
            |(FAST-METHOD DESCRIBE-OBJECT (CLASS T))|
            |(FAST-METHOD SLOT-ACCESSOR-FUNCTION (EFFECTIVE-SLOT-DEFINITION T))|
            |(FAST-METHOD CHANGE-CLASS (T SYMBOL))|
            EMIT-CHECKING-OR-CACHING)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T) *) MEMF-CODE-CONVERTER
            |(FAST-METHOD (SETF SLOT-VALUE-USING-CLASS) (T STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
            GENERATE-DISCRIMINATION-NET-INTERNAL
            DO-SHORT-METHOD-COMBINATION
            MAKE-LONG-METHOD-COMBINATION-FUNCTION
            CACHE-MISS-VALUES-INTERNAL)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T *) *) MAKE-ONE-INDEX-ACCESSOR-DFUN
            WALKER::WALK-DECLARATIONS GET-SECONDARY-DISPATCH-FUNCTION)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T *) *) SLOT-VALUE-OR-DEFAULT NESTED-WALK-FORM
            LOAD-DEFGENERIC MAKE-ACCESSOR-TABLE
            MAKE-DEFAULT-INITARGS-FORM-LIST
            GET-EFFECTIVE-METHOD-FUNCTION MAKE-CHECKING-DFUN
            GET-COMPLEX-INITIALIZATION-FUNCTIONS MAKE-N-N-ACCESSOR-DFUN
            GET-SIMPLE-INITIALIZATION-FUNCTION MAKE-FINAL-ACCESSOR-DFUN
            TYPES-FROM-ARGUMENTS MAKE-EFFECTIVE-METHOD-FUNCTION
            COMPUTE-SECONDARY-DISPATCH-FUNCTION)) 
(PROCLAIM '(FTYPE (FUNCTION (T T T T T T *) *) REAL-MAKE-A-METHOD)) 
(PROCLAIM '(FTYPE (FUNCTION (T) SIMPLE-VECTOR) CACHE-VECTOR)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T) T) BOOTSTRAP-MAKE-SLOT-DEFINITION
            |(FAST-METHOD (SETF SLOT-VALUE-USING-CLASS) (T STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
            LOAD-DEFCLASS MAKE-EARLY-CLASS-DEFINITION
            WALKER::WALK-TEMPLATE-HANDLE-REPEAT-1 OPTIMIZE-GF-CALL
            EMIT-SLOT-ACCESS REAL-LOAD-DEFCLASS SET-ARG-INFO1)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T) T)
            |(FAST-METHOD WRITER-METHOD-CLASS (SLOT-CLASS T))|
            |(FAST-METHOD COMPUTE-SLOT-ACCESSOR-INFO (EFFECTIVE-SLOT-DEFINITION T T))|
            |(FAST-METHOD ENSURE-CLASS-USING-CLASS (T PCL-CLASS))|
            |(FAST-METHOD SLOT-MAKUNBOUND-USING-CLASS (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
            |(FAST-METHOD SHARED-INITIALIZE :AFTER (STANDARD-METHOD T))|
            EXPAND-EMF-CALL-METHOD
            |(FAST-METHOD SHARED-INITIALIZE :AFTER (STD-CLASS T))|
            COMPUTE-PV-SLOT
            |(FAST-METHOD SLOT-BOUNDP-USING-CLASS (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
            |(FAST-METHOD (SETF SLOT-ACCESSOR-STD-P) (T EFFECTIVE-SLOT-DEFINITION T))|
            UPDATE-SLOTS-IN-PV BOOTSTRAP-MAKE-SLOT-DEFINITIONS
            WALKER::WALK-TEMPLATE-HANDLE-REPEAT WALKER::WALK-BINDINGS-1
            OPTIMIZE-ACCESSOR-CALL REAL-MAKE-METHOD-INITARGS-FORM
            |(FAST-METHOD FIND-METHOD-COMBINATION (GENERIC-FUNCTION (EQL STANDARD) T))|
            |(FAST-METHOD (SETF DOCUMENTATION) (T DOCUMENTATION-MIXIN))|
            MAKE-EMF-CACHE MAKE-METHOD-INITARGS-FORM-INTERNAL1
            BOOTSTRAP-ACCESSOR-DEFINITIONS1
            |(FAST-METHOD SHARED-INITIALIZE :AFTER (DOCUMENTATION-MIXIN T))|
            MAKE-INSTANCE-FUNCTION-COMPLEX MAKE-FGEN
            |(FAST-METHOD REMOVE-NAMED-METHOD (T T))|
            |(FAST-METHOD COMPUTE-EFFECTIVE-METHOD (GENERIC-FUNCTION SHORT-METHOD-COMBINATION T))|
            |(FAST-METHOD SHARED-INITIALIZE :AFTER (STRUCTURE-CLASS T))|
            MAKE-FINAL-ORDINARY-DFUN-INTERNAL
            |(FAST-METHOD SLOT-MAKUNBOUND-USING-CLASS (STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
            MAKE-INSTANCE-FUNCTION-SIMPLE OPTIMIZE-INSTANCE-ACCESS
            MAKE-PARAMETER-REFERENCES
            GET-MAKE-INSTANCE-FUNCTION-INTERNAL
            |(FAST-METHOD SLOT-UNBOUND (T T T))|
            |(FAST-METHOD (SETF DOCUMENTATION) (T T))|
            |(FAST-METHOD SHARED-INITIALIZE :AFTER (STRUCTURE-SLOT-DEFINITION T))|
            |(FAST-METHOD SLOT-BOUNDP-USING-CLASS (STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
            LOAD-FUNCTION-GENERATOR
            |(FAST-METHOD SHARED-INITIALIZE :BEFORE (STANDARD-ACCESSOR-METHOD T))|
            |(FAST-METHOD READER-METHOD-CLASS (SLOT-CLASS T))|
            |(FAST-METHOD ENSURE-CLASS-USING-CLASS (T NULL))|
            |(FAST-METHOD SHARED-INITIALIZE :BEFORE (BUILT-IN-CLASS T))|
            OPTIMIZE-GENERIC-FUNCTION-CALL)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T *) T) EMIT-FETCH-WRAPPER FILL-CACHE
            GET-METHOD CHECK-INITARGS-2-PLIST MAKE-EMF-CALL
            CHECK-INITARGS-1 WALKER::WALK-ARGLIST REAL-GET-METHOD
            CAN-OPTIMIZE-ACCESS1 CHECK-INITARGS-2-LIST)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T) T) ONE-CLASS-DFUN-INFO
            |(FAST-METHOD SLOTS-FETCHER (STANDARD-CLASS))| SORT-METHODS
            OPTIMIZE-GF-CALL-INTERNAL WALKER::WALK-LABELS
            |(FAST-METHOD SPECIALIZER-CLASS (EQL-SPECIALIZER))|
            |(FAST-METHOD RAW-INSTANCE-ALLOCATOR (STANDARD-CLASS))|
            WALKER::WALK-DO
            |(FAST-METHOD SPECIALIZER-DIRECT-METHODS (CLASS))|
            ITERATE::RENAME-AND-CAPTURE-VARIABLES EXPAND-DEFGENERIC
            |(FAST-METHOD GENERIC-FUNCTION-PRETTY-ARGLIST (STANDARD-GENERIC-FUNCTION))|
            |(FAST-METHOD SPECIALIZER-DIRECT-METHODS (SPECIALIZER-WITH-OBJECT))|
            FLUSH-CACHE-TRAP WALKER::WALK-MACROLET
            |(FAST-METHOD CLASS-DEFAULT-INITARGS (SLOT-CLASS))|
            |(FAST-METHOD COMPUTE-SLOTS :AROUND (STD-CLASS))|
            COMPUTE-EFFECTIVE-METHOD OPTIMIZE-SET-SLOT-VALUE
            WALKER::WALK-SYMBOL-MACROLET OPTIMIZE-SLOT-BOUNDP
            |(FAST-METHOD COMPUTE-DEFAULT-INITARGS (SLOT-CLASS))|
            GET-FUNCTION-GENERATOR FIX-SLOT-ACCESSORS
            SET-FUNCTION-NAME-1 WALKER::WALK-LET EMIT-BOUNDP-CHECK
            INITIALIZE-INTERNAL-SLOT-GFS* PRINT-CACHE WALKER::WALK-IF
            WALKER::WALK-SETQ WALKER::RELIST-INTERNAL
            |(FAST-METHOD RAW-INSTANCE-ALLOCATOR (FUNCALLABLE-STANDARD-CLASS))|
            EMIT-1-T-DLAP CAN-OPTIMIZE-ACCESS WALKER::WALK-COMPILER-LET
            |(FAST-METHOD WRAPPER-FETCHER (STANDARD-CLASS))|
            |SETF PCL METHOD-FUNCTION-GET|
            |(FAST-METHOD SPECIALIZER-METHOD-TABLE (CLASS-EQ-SPECIALIZER))|
            GET-NEW-FUNCTION-GENERATOR WALKER::WALK-UNEXPECTED-DECLARE
            |(FAST-METHOD ACCESSOR-METHOD-CLASS (STANDARD-ACCESSOR-METHOD))|
            VARIABLE-DECLARATION
            |(FAST-METHOD GENERIC-FUNCTION-LAMBDA-LIST (GENERIC-FUNCTION))|
            MAP-ALL-ORDERS ONE-INDEX-DFUN-INFO WALKER::WALK-LAMBDA
            |(FAST-METHOD COMPUTE-SLOTS :AROUND (STRUCTURE-CLASS))|
            NOTE-PV-TABLE-REFERENCE WALKER::RECONS
            STANDARD-COMPUTE-EFFECTIVE-METHOD
            |(FAST-METHOD SLOT-DEFINITION-ALLOCATION (STRUCTURE-SLOT-DEFINITION))|
            |SETF PCL PLIST-VALUE| EMIT-GREATER-THAN-1-DLAP
            MAKE-METHOD-SPEC ITERATE::OPTIMIZE-GATHERING-FORM
            OPTIMIZE-SLOT-VALUE PRINT-STD-INSTANCE COMPUTE-PRECEDENCE
            WALKER::WALK-TAGBODY WALKER::WALK-NAMED-LAMBDA
            |(FAST-METHOD CLASS-FINALIZED-P (PCL-CLASS))|
            SKIP-FAST-SLOT-ACCESS-P TRACE-EMF-CALL-INTERNAL
            |(FAST-METHOD SPECIALIZER-DIRECT-GENERIC-FUNCTIONS (CLASS))|
            |(FAST-METHOD COMPUTE-SLOTS (STD-CLASS))|
            |(FAST-METHOD MAKE-INSTANCES-OBSOLETE (STD-CLASS))|
            ITERATE::SIMPLE-EXPAND-GATHERING-FORM
            |(FAST-METHOD CLASS-DIRECT-SLOTS (BUILT-IN-CLASS))|
            SORT-APPLICABLE-METHODS SKIP-OPTIMIZE-SLOT-VALUE-BY-CLASS-P
            OBSOLETE-INSTANCE-TRAP WALKER::WALK-PROG
            |(FAST-METHOD CLASS-CONSTRUCTORS (SLOT-CLASS))|
            INVALIDATE-WRAPPER
            |(FAST-METHOD COMPUTE-SLOTS (STRUCTURE-CLASS))|
            |(FAST-METHOD SLOTS-FETCHER (FUNCALLABLE-STANDARD-CLASS))|
            |(FAST-METHOD CLASS-DIRECT-DEFAULT-INITARGS (BUILT-IN-CLASS))|
            ENTRY-IN-CACHE-P WALKER::WALK-TAGBODY-1
            |(FAST-METHOD ACCESSOR-METHOD-CLASS (STANDARD-WRITER-METHOD))|
            MAKE-OPTIMIZED-STD-SLOT-VALUE-USING-CLASS-METHOD-FUNCTION
            |(FAST-METHOD FINALIZE-INHERITANCE (STRUCTURE-CLASS))|
            WALKER::WALK-LOCALLY WALKER::WALK-MULTIPLE-VALUE-BIND
            |(FAST-METHOD INITIALIZE-INTERNAL-SLOT-FUNCTIONS (EFFECTIVE-SLOT-DEFINITION))|
            |(FAST-METHOD CLASS-DIRECT-DEFAULT-INITARGS (SLOT-CLASS))|
            WRAP-METHOD-GROUP-SPECIFIER-BINDINGS WALKER::WALK-LET*
            |(FAST-METHOD CLASS-PREDICATE-NAME (T))|
            |(FAST-METHOD COMPUTE-CLASS-PRECEDENCE-LIST (SLOT-CLASS))|
            |(FAST-METHOD GF-FAST-METHOD-FUNCTION-P (STANDARD-GENERIC-FUNCTION))|
            EMIT-SLOT-READ-FORM FIRST-FORM-TO-LISP
            MAKE-OPTIMIZED-STD-SLOT-BOUNDP-USING-CLASS-METHOD-FUNCTION
            |(FAST-METHOD CLASS-SLOTS (BUILT-IN-CLASS))|
            WALKER::WITH-AUGMENTED-ENVIRONMENT-INTERNAL
            WALKER::WALK-PROG* WALKER::WALK-FLET
            |(FAST-METHOD SPECIALIZER-CLASS (CLASS))|
            MAKE-OPTIMIZED-STD-SETF-SLOT-VALUE-USING-CLASS-METHOD-FUNCTION
            |(FAST-METHOD METHOD-QUALIFIERS (STANDARD-METHOD))|
            MAKE-METHOD-INITARGS-FORM-INTERNAL WALKER::WALK-DO*
            MAKE-TOP-LEVEL-FORM
            |(FAST-METHOD FINALIZE-INHERITANCE (STD-CLASS))|
            |(FAST-METHOD SPECIALIZER-DIRECT-GENERIC-FUNCTIONS (SPECIALIZER-WITH-OBJECT))|
            |(FAST-METHOD SPECIALIZER-METHOD-TABLE (EQL-SPECIALIZER))|
            ITERATE::OPTIMIZE-ITERATE-FORM DECLARE-STRUCTURE
            MAKE-DFUN-CALL ITERATE::VARIABLE-SAME-P
            |(FAST-METHOD WRAPPER-FETCHER (FUNCALLABLE-STANDARD-CLASS))|
            WALKER::WALK-MULTIPLE-VALUE-SETQ CONVERT-TABLE
            |(FAST-METHOD CLASS-SLOT-CELLS (STD-CLASS))|
            |(FAST-METHOD CLASS-DEFAULT-INITARGS (BUILT-IN-CLASS))|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T) T)
            |(FAST-METHOD REMOVE-DIRECT-SUBCLASS (CLASS CLASS))|
            EMIT-CHECKING-OR-CACHING-FUNCTION-PRELIMINARY
            |(FAST-METHOD CHANGE-CLASS (STANDARD-OBJECT STANDARD-CLASS))|
            WALKER::WALK-LET/LET*
            |(FAST-METHOD EFFECTIVE-SLOT-DEFINITION-CLASS (STRUCTURE-CLASS T))|
            |(FAST-METHOD VALIDATE-SUPERCLASS (SLOT-CLASS FORWARD-REFERENCED-CLASS))|
            |(FAST-METHOD VALIDATE-SUPERCLASS (FUNCALLABLE-STANDARD-CLASS STANDARD-CLASS))|
            MAKE-EFFECTIVE-METHOD-FUNCTION-TYPE
            |(FAST-METHOD REMOVE-BOUNDP-METHOD (SLOT-CLASS T))|
            |(FAST-METHOD MAKE-WRITER-METHOD-FUNCTION (FUNCALLABLE-STANDARD-CLASS T))|
            |(FAST-METHOD DOCUMENTATION (T))|
            |(FAST-METHOD REINITIALIZE-INSTANCE :BEFORE (SLOT-CLASS))|
            MAYBE-EXPAND-ACCESSOR-FORM BOOTSTRAP-SET-SLOT
            |(FAST-METHOD INFORM-TYPE-SYSTEM-ABOUT-CLASS (STD-CLASS T))|
            WALKER::WALK-TEMPLATE
            |(FAST-METHOD PRINT-OBJECT (STANDARD-METHOD-COMBINATION T))|
            |(FAST-METHOD REINITIALIZE-INSTANCE (STANDARD-METHOD))|
            |(FAST-METHOD REINITIALIZE-INSTANCE (SLOT-OBJECT))|
            GET-WRAPPERS-FROM-CLASSES
            |(FAST-METHOD LEGAL-SLOT-NAME-P (STANDARD-METHOD T))|
            MAKE-EFFECTIVE-METHOD-FUNCTION1
            |(FAST-METHOD PRINT-OBJECT (CLASS T))|
            |(FAST-METHOD PRINT-OBJECT (GENERIC-FUNCTION T))|
            |(FAST-METHOD INFORM-TYPE-SYSTEM-ABOUT-CLASS (STRUCTURE-CLASS T))|
            EXPAND-CACHE EXPAND-DEFCLASS
            |(FAST-METHOD UPDATE-GF-DFUN (STD-CLASS T))|
            |(FAST-METHOD COMPATIBLE-META-CLASS-CHANGE-P (T T))|
            |(FAST-METHOD MAP-DEPENDENTS (DEPENDENT-UPDATE-MIXIN T))|
            |(FAST-METHOD REMOVE-DIRECT-METHOD (CLASS METHOD))|
            |(FAST-METHOD MAKE-BOUNDP-METHOD-FUNCTION (SLOT-CLASS T))|
            |(FAST-METHOD LEGAL-LAMBDA-LIST-P (STANDARD-METHOD T))|
            |(FAST-METHOD INITIALIZE-INSTANCE :AFTER (STANDARD-GENERIC-FUNCTION))|
            |(FAST-METHOD REINITIALIZE-INSTANCE :AFTER (STANDARD-GENERIC-FUNCTION))|
            MAKE-EFFECTIVE-METHOD-FUNCTION-INTERNAL
            |(FAST-METHOD LEGAL-SPECIALIZER-P (STANDARD-METHOD T))|
            |(FAST-METHOD MAKE-READER-METHOD-FUNCTION (FUNCALLABLE-STANDARD-CLASS T))|
            |(FAST-METHOD SAME-SPECIALIZER-P (SPECIALIZER SPECIALIZER))|
            TWO-CLASS-DFUN-INFO
            |(FAST-METHOD EFFECTIVE-SLOT-DEFINITION-CLASS (STD-CLASS T))|
            |(FAST-METHOD PRINT-OBJECT (T T))|
            |(FAST-METHOD VALIDATE-SUPERCLASS (CLASS CLASS))|
            FILL-CACHE-P MEMF-TEST-CONVERTER
            |(FAST-METHOD LEGAL-QUALIFIER-P (STANDARD-METHOD T))|
            WALKER::WALK-BINDINGS-2
            |(FAST-METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION-INITARGS :AROUND (STRUCTURE-CLASS T))|
            |(FAST-METHOD REMOVE-DEPENDENT (DEPENDENT-UPDATE-MIXIN T))|
            |(FAST-METHOD ADD-DIRECT-SUBCLASS (CLASS CLASS))|
            |(FAST-METHOD ADD-DEPENDENT (DEPENDENT-UPDATE-MIXIN T))|
            |(FAST-METHOD PRINT-OBJECT (SLOT-DEFINITION T))|
            WALKER::WALK-DO/DO* ADJUST-CACHE
            |(FAST-METHOD ADD-DIRECT-METHOD (SPECIALIZER-WITH-OBJECT METHOD))|
            |(FAST-METHOD REMOVE-DIRECT-METHOD (SPECIALIZER-WITH-OBJECT METHOD))|
            |(FAST-METHOD LEGAL-DOCUMENTATION-P (STANDARD-METHOD T))|
            OPTIMIZE-READER
            |(FAST-METHOD PRINT-OBJECT (STANDARD-METHOD T))|
            |(FAST-METHOD MAKE-WRITER-METHOD-FUNCTION (SLOT-CLASS T))|
            |(FAST-METHOD ALLOCATE-INSTANCE (STANDARD-CLASS))|
            EXPAND-SYMBOL-MACROLET-INTERNAL
            |(FAST-METHOD ADD-DIRECT-METHOD (CLASS METHOD))|
            |(FAST-METHOD SAME-SPECIALIZER-P (EQL-SPECIALIZER EQL-SPECIALIZER))|
            MAKE-DISPATCH-LAMBDA
            |(FAST-METHOD LEGAL-METHOD-FUNCTION-P (STANDARD-METHOD T))|
            |(FAST-METHOD SAME-SPECIALIZER-P (CLASS-EQ-SPECIALIZER CLASS-EQ-SPECIALIZER))|
            INITIALIZE-INSTANCE-SIMPLE
            |(FAST-METHOD VALIDATE-SUPERCLASS (CLASS BUILT-IN-CLASS))|
            OPTIMIZE-WRITER
            |(FAST-METHOD REMOVE-READER-METHOD (SLOT-CLASS T))|
            |(FAST-METHOD COMPUTE-APPLICABLE-METHODS (GENERIC-FUNCTION T))|
            |(FAST-METHOD CHANGE-CLASS (STANDARD-OBJECT FUNCALLABLE-STANDARD-CLASS))|
            |(FAST-METHOD DIRECT-SLOT-DEFINITION-CLASS (STRUCTURE-CLASS T))|
            LOAD-PRECOMPILED-IIS-ENTRY
            LOAD-PRECOMPILED-DFUN-CONSTRUCTOR
            |(FAST-METHOD SLOT-ACCESSOR-STD-P (EFFECTIVE-SLOT-DEFINITION T))|
            |(FAST-METHOD DIRECT-SLOT-DEFINITION-CLASS (STD-CLASS T))|
            |(FAST-METHOD DOCUMENTATION (DOCUMENTATION-MIXIN))|
            WALKER::WALK-PROG/PROG*
            |(FAST-METHOD ALLOCATE-INSTANCE (FUNCALLABLE-STANDARD-CLASS))|
            |(FAST-METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION-INITARGS (SLOT-CLASS T))|
            |(FAST-METHOD REMOVE-WRITER-METHOD (SLOT-CLASS T))|
            |(FAST-METHOD MAKE-INSTANCE (CLASS))|
            |(FAST-METHOD PRINT-OBJECT (STANDARD-ACCESSOR-METHOD T))|
            |(FAST-METHOD SAME-SPECIALIZER-P (CLASS CLASS))|
            |(FAST-METHOD MAKE-READER-METHOD-FUNCTION (SLOT-CLASS T))|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T *) T) COMPUTE-SECONDARY-DISPATCH-FUNCTION1
            FIND-CLASS-PREDICATE-FROM-CELL
            ENSURE-GENERIC-FUNCTION-USING-CLASS GET-DECLARATION
            METHOD-FUNCTION-GET CPL-ERROR EMIT-MISS
            PRECOMPUTE-EFFECTIVE-METHODS GET-METHOD-FUNCTION-PV-CELL
            MAP-CACHE EXPAND-EFFECTIVE-METHOD-FUNCTION
            MAKE-EMF-FROM-METHOD GET-EFFECTIVE-METHOD-FUNCTION1
            REAL-ENSURE-GF-USING-CLASS--GENERIC-FUNCTION
            NAMED-OBJECT-PRINT-FUNCTION
            MAKE-EFFECTIVE-METHOD-FUNCTION-SIMPLE PROBE-CACHE
            INITIALIZE-INFO REAL-ENSURE-GF-USING-CLASS--NULL
            FIND-CLASS-FROM-CELL WALKER::CONVERT-MACRO-TO-LAMBDA
            REAL-ADD-METHOD RECORD-DEFINITION)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T *) T) MAKE-DEFMETHOD-FORM
            MAKE-DEFMETHOD-FORM-INTERNAL LOAD-DEFMETHOD
            EARLY-MAKE-A-METHOD)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T *) T) EMIT-DLAP
            GET-SECONDARY-DISPATCH-FUNCTION1)) 
(PROCLAIM '(FTYPE (FUNCTION (T T FIXNUM) T) COMPUTE-STD-CPL-PHASE-3)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T T) T)
            GET-SECONDARY-DISPATCH-FUNCTION2)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T *) T) REAL-ADD-NAMED-METHOD
            EARLY-ADD-NAMED-METHOD FILL-DFUN-CACHE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T) T)
            |(FAST-METHOD SLOT-MISSING (T T T T))|
            LOAD-DEFMETHOD-INTERNAL EXPAND-DEFMETHOD)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T FIXNUM) T) GET-CACHE
            FILL-CACHE-FROM-CACHE-P)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T T T *) T)
            BOOTSTRAP-INITIALIZE-CLASS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) FIXNUM) N-N-ACCESSORS-LIMIT-FN
            FAST-INSTANCE-BOUNDP-INDEX PV-TABLE-PV-SIZE
            ARG-INFO-NUMBER-REQUIRED EARLY-CLASS-SIZE DEFAULT-LIMIT-FN
            CHECKING-LIMIT-FN ONE-INDEX-LIMIT-FN CPD-COUNT CACHE-COUNT
            PV-CACHE-LIMIT-FN CACHING-LIMIT-FN)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM) T) POWER-OF-TWO-CEILING)) 
(PROCLAIM '(FTYPE (FUNCTION (T T *) (VALUES T T)) SYMBOL-APPEND)) 
(PROCLAIM '(FTYPE (FUNCTION (T STREAM T) T) PRINT-DFUN-INFO)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) NON-NEGATIVE-FIXNUM) CACHE-NLINES CACHE-MASK
            CACHE-MAX-LOCATION CACHE-SIZE)) 
(IN-PACKAGE "PCL")

(DOLIST (V '(DISASSEMBLE |(FAST-WRITER-METHOD SLOT-OBJECT OPTIONS)|
                |(FAST-WRITER-METHOD STANDARD-GENERIC-FUNCTION METHODS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT METHODS)|
                |(FAST-WRITER-METHOD SLOT-CLASS DIRECT-SLOTS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT DIRECT-SLOTS)|
                |(FAST-WRITER-METHOD SLOT-CLASS SLOTS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT SLOTS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT DIRECT-METHODS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT FROM-DEFCLASS-P)|
                |(FAST-WRITER-METHOD SLOT-OBJECT DIRECT-SUPERCLASSES)|
                |(FAST-WRITER-METHOD SLOT-OBJECT DIRECT-SUBCLASSES)|
                ADD-READER-METHOD
                SHORT-COMBINATION-IDENTITY-WITH-ONE-ARGUMENT
                REMOVE-READER-METHOD |LISP::T class predicate|
                EQL-SPECIALIZER-P |(SETF GENERIC-FUNCTION-NAME)|
                OBJECT-PLIST SLOT-DEFINITION-DEFSTRUCT-ACCESSOR-SYMBOL
                |PCL::STANDARD-METHOD-COMBINATION class predicate|
                |PCL::STANDARD-EFFECTIVE-SLOT-DEFINITION class predicate|
                |PCL::STANDARD-DIRECT-SLOT-DEFINITION class predicate|
                |PCL::STANDARD-SLOT-DEFINITION class predicate|
                |PCL::STANDARD-OBJECT class predicate|
                |(FAST-READER-METHOD SLOT-OBJECT METHOD)|
                |PCL::BUILT-IN-CLASS class predicate| SPECIALIZER-TYPE
                |LISP::RATIONAL class predicate|
                |LISP::RATIO class predicate| GF-DFUN-STATE
                |(SETF GENERIC-FUNCTION-METHOD-CLASS)|
                |(FAST-READER-METHOD STRUCTURE-SLOT-DEFINITION DEFSTRUCT-ACCESSOR-SYMBOL)|
                |(FAST-READER-METHOD SLOT-OBJECT DEFSTRUCT-ACCESSOR-SYMBOL)|
                |(SETF GENERIC-FUNCTION-METHOD-COMBINATION)|
                CLASS-DEFSTRUCT-CONSTRUCTOR
                |(FAST-READER-METHOD DEFINITION-SOURCE-MIXIN SOURCE)|
                |(FAST-READER-METHOD SLOT-OBJECT SOURCE)|
                METHOD-FAST-FUNCTION |(SETF GENERIC-FUNCTION-METHODS)|
                |(SETF GF-PRETTY-ARGLIST)|
                |(FAST-READER-METHOD STANDARD-GENERIC-FUNCTION ARG-INFO)|
                |(FAST-READER-METHOD SLOT-OBJECT ARG-INFO)|
                |(FAST-READER-METHOD SLOT-CLASS INITIALIZE-INFO)|
                |(FAST-READER-METHOD SLOT-OBJECT INITIALIZE-INFO)|
                SPECIALIZERP EXACT-CLASS-SPECIALIZER-P
                |(FAST-READER-METHOD PCL-CLASS WRAPPER)|
                |(FAST-READER-METHOD SLOT-OBJECT WRAPPER)|
                |(FAST-READER-METHOD SLOT-DEFINITION INITARGS)|
                |(FAST-READER-METHOD SLOT-OBJECT INITARGS)|
                |(FAST-READER-METHOD STRUCTURE-CLASS DEFSTRUCT-CONSTRUCTOR)|
                |(FAST-READER-METHOD SLOT-OBJECT DEFSTRUCT-CONSTRUCTOR)|
                |(FAST-READER-METHOD SLOT-OBJECT OPERATOR)|
                |(FAST-READER-METHOD SHORT-METHOD-COMBINATION OPERATOR)|
                |LISP::CHARACTER class predicate|
                COMPATIBLE-META-CLASS-CHANGE-P
                |LISP::SEQUENCE class predicate|
                |(FAST-READER-METHOD CLASS CLASS-EQ-SPECIALIZER)|
                |(FAST-READER-METHOD SLOT-OBJECT CLASS-EQ-SPECIALIZER)|
                |(BOUNDP READER-FUNCTION)| TRACE-METHOD-INTERNAL
                |(BOUNDP PREDICATE-NAME)| |(BOUNDP READERS)|
                UPDATE-GF-DFUN |(BOUNDP CLASS-PRECEDENCE-LIST)|
                |(BOUNDP ACCESSOR-FLAGS)| |(BOUNDP DOCUMENTATION)|
                |(BOUNDP LOCATION)| SPECIALIZER-OBJECT
                |(BOUNDP INCOMPATIBLE-SUPERCLASS-LIST)|
                ACCESSOR-METHOD-SLOT-NAME |(BOUNDP SPECIALIZERS)|
                |(BOUNDP IDENTITY-WITH-ONE-ARGUMENT)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT DEFSTRUCT-ACCESSOR-SYMBOL)|
                REDEFINE-FUNCTION SPECIALIZER-CLASS
                |(BOUNDP PRETTY-ARGLIST)|
                |PCL::PCL-CLASS class predicate|
                |PCL::STD-CLASS class predicate|
                |(BOUNDP DEFSTRUCT-FORM)|
                |(SETF SLOT-DEFINITION-DEFSTRUCT-ACCESSOR-SYMBOL)|
                CLASS-EQ-SPECIALIZER-P
                |(FAST-BOUNDP-METHOD SLOT-OBJECT SOURCE)| SLOTS-FETCHER
                |(SETF SLOT-ACCESSOR-STD-P)| REMOVE-WRITER-METHOD
                |(BOUNDP INITFUNCTION)| |(BOUNDP WRITER-FUNCTION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT ARG-INFO)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT INITIALIZE-INFO)|
                STRUCTURE-CLASS-P |(BOUNDP WRITERS)|
                |(BOUNDP INITFORM)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT WRAPPER)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT INITARGS)|
                |LISP::BIT-VECTOR class predicate|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT DEFSTRUCT-CONSTRUCTOR)|
                UPDATE-CONSTRUCTORS |(BOUNDP SLOT-NAME)|
                |(SETF SLOT-DEFINITION-INITARGS)| |(BOUNDP ALLOCATION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT CLASS-EQ-SPECIALIZER)|
                DOCUMENTATION |(BOUNDP GENERIC-FUNCTION)|
                |(BOUNDP FUNCTION)| |(BOUNDP LAMBDA-LIST)|
                METHOD-PRETTY-ARGLIST |(BOUNDP SLOT-DEFINITION)|
                |LISP::ARRAY class predicate|
                |(BOUNDP CAN-PRECEDE-LIST)| |(BOUNDP PROTOTYPE)|
                CLASS-EQ-SPECIALIZER INFORM-TYPE-SYSTEM-ABOUT-CLASS
                |PCL::DEFINITION-SOURCE-MIXIN class predicate|
                |(BOUNDP DFUN-STATE)|
                |LISP::STRUCTURE-OBJECT class predicate|
                |(BOUNDP FROM-DEFCLASS-P)| COMPILE |(READER METHOD)|
                |LISP::STANDARD-OBJECT class predicate|
                |(CALL STANDARD-COMPUTE-EFFECTIVE-METHOD)|
                |(BOUNDP FAST-FUNCTION)|
                |LISP::COMPLEX class predicate| |(BOUNDP METHOD-CLASS)|
                |(READER SOURCE)| |(BOUNDP METHOD-COMBINATION)|
                |(BOUNDP INTERNAL-READER-FUNCTION)|
                |(BOUNDP INTERNAL-WRITER-FUNCTION)|
                ACCESSOR-METHOD-CLASS |(BOUNDP DIRECT-METHODS)|
                |(BOUNDP DIRECT-SLOTS)| |(BOUNDP BOUNDP-FUNCTION)|
                |(BOUNDP DIRECT-SUPERCLASSES)|
                |(BOUNDP DIRECT-SUBCLASSES)| |(BOUNDP OPTIONS)|
                |(BOUNDP METHODS)| |(WRITER METHOD)|
                |LISP::BUILT-IN-CLASS class predicate|
                |PCL::DEPENDENT-UPDATE-MIXIN class predicate|
                GENERIC-FUNCTION-PRETTY-ARGLIST |(WRITER SOURCE)|
                |(FAST-METHOD UPDATE-INSTANCE-FOR-DIFFERENT-CLASS (STANDARD-OBJECT STANDARD-OBJECT))|
                |(FAST-METHOD SLOTS-TO-INSPECT (SLOT-CLASS SLOT-OBJECT))|
                |(FAST-METHOD INITIALIZE-INSTANCE (SLOT-OBJECT))|
                |(FAST-METHOD REINITIALIZE-INSTANCE (SLOT-OBJECT))|
                |(FAST-METHOD SPECIALIZER-DIRECT-METHODS (SPECIALIZER-WITH-OBJECT))|
                |(FAST-METHOD SPECIALIZER-DIRECT-GENERIC-FUNCTIONS (SPECIALIZER-WITH-OBJECT))|
                |(FAST-METHOD SAME-SPECIALIZER-P (CLASS-EQ-SPECIALIZER CLASS-EQ-SPECIALIZER))|
                |(FAST-METHOD SAME-SPECIALIZER-P (EQL-SPECIALIZER EQL-SPECIALIZER))|
                |(FAST-METHOD SAME-SPECIALIZER-P (SPECIALIZER SPECIALIZER))|
                |(FAST-METHOD SPECIALIZER-METHOD-TABLE (EQL-SPECIALIZER))|
                |(FAST-METHOD SPECIALIZER-CLASS (EQL-SPECIALIZER))|
                |(FAST-METHOD SPECIALIZER-METHOD-TABLE (CLASS-EQ-SPECIALIZER))|
                MAKE-BOUNDP-METHOD-FUNCTION
                |LISP::STRING class predicate|
                |(FAST-METHOD (SETF DOCUMENTATION) (T DOCUMENTATION-MIXIN))|
                |(FAST-METHOD DOCUMENTATION (DOCUMENTATION-MIXIN))|
                |PCL::METAOBJECT class predicate|
                |(FAST-METHOD (SETF SLOT-VALUE-USING-CLASS) (T STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
                |(FAST-METHOD SLOT-BOUNDP-USING-CLASS (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
                |(FAST-METHOD SLOT-MAKUNBOUND-USING-CLASS (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
                |(FAST-METHOD SLOT-MAKUNBOUND-USING-CLASS (STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
                |(FAST-METHOD SLOT-BOUNDP-USING-CLASS (STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
                |(FAST-METHOD SLOT-VALUE-USING-CLASS (STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
                |(FAST-METHOD SLOT-VALUE-USING-CLASS (STD-CLASS STANDARD-OBJECT STANDARD-EFFECTIVE-SLOT-DEFINITION))|
                |(FAST-METHOD (SETF DOCUMENTATION) (T STANDARD-SLOT-DEFINITION))|
                |(FAST-METHOD METHOD-QUALIFIERS (TRACED-METHOD))|
                |(FAST-METHOD METHOD-PRETTY-ARGLIST (STANDARD-METHOD))|
                |(FAST-METHOD FUNCTION-KEYWORDS (STANDARD-METHOD))|
                |(FAST-METHOD COMPUTE-DISCRIMINATING-FUNCTION (STANDARD-GENERIC-FUNCTION))|
                |(FAST-METHOD METHOD-LAMBDA-LIST (TRACED-METHOD))|
                |(FAST-METHOD MAKE-INSTANCES-OBSOLETE (SYMBOL))|
                |(FAST-METHOD METHOD-SPECIALIZERS (TRACED-METHOD))|
                |(FAST-METHOD METHOD-FUNCTION (STANDARD-METHOD))|
                |(FAST-METHOD ACCESSOR-METHOD-SLOT-NAME (TRACED-METHOD))|
                |(FAST-METHOD COMPUTE-DISCRIMINATING-FUNCTION-ARGLIST-INFO (STANDARD-GENERIC-FUNCTION))|
                |(FAST-METHOD DOCUMENTATION (STANDARD-SLOT-DEFINITION))|
                |(FAST-METHOD MAKE-INSTANCE (SYMBOL))|
                |(FAST-METHOD CHANGE-CLASS (T SYMBOL))|
                |(FAST-METHOD (SETF SLOT-VALUE-USING-CLASS) (T STRUCTURE-CLASS STRUCTURE-OBJECT STRUCTURE-EFFECTIVE-SLOT-DEFINITION))|
                |(FAST-METHOD ADD-DIRECT-METHOD (SPECIALIZER-WITH-OBJECT METHOD))|
                |(FAST-METHOD REINITIALIZE-INSTANCE (STANDARD-METHOD))|
                |(FAST-METHOD REMOVE-DIRECT-METHOD (CLASS METHOD))|
                |(FAST-METHOD INITIALIZE-INSTANCE :AFTER (STANDARD-GENERIC-FUNCTION))|
                |(FAST-METHOD REMOVE-DIRECT-METHOD (SPECIALIZER-WITH-OBJECT METHOD))|
                |(FAST-METHOD REINITIALIZE-INSTANCE :AFTER (STANDARD-GENERIC-FUNCTION))|
                |(FAST-METHOD ADD-DIRECT-METHOD (CLASS METHOD))|
                |(FAST-METHOD GENERIC-FUNCTION-PRETTY-ARGLIST (STANDARD-GENERIC-FUNCTION))|
                |(FAST-METHOD INITIALIZE-INTERNAL-SLOT-FUNCTIONS (EFFECTIVE-SLOT-DEFINITION))|
                |(FAST-METHOD ACCESSOR-METHOD-CLASS (STANDARD-WRITER-METHOD))|
                |(FAST-METHOD ACCESSOR-METHOD-CLASS (STANDARD-ACCESSOR-METHOD))|
                |(FAST-METHOD GF-FAST-METHOD-FUNCTION-P (STANDARD-GENERIC-FUNCTION))|
                |(FAST-METHOD GENERIC-FUNCTION-LAMBDA-LIST (GENERIC-FUNCTION))|
                |(FAST-METHOD METHOD-QUALIFIERS (STANDARD-METHOD))|
                |(FAST-METHOD SLOT-DEFINITION-ALLOCATION (STRUCTURE-SLOT-DEFINITION))|
                |(FAST-METHOD ENSURE-CLASS-USING-CLASS (T PCL-CLASS))|
                |(FAST-METHOD CLASS-PROTOTYPE (STRUCTURE-CLASS))|
                |(FAST-METHOD CLASS-PROTOTYPE (STD-CLASS))|
                |(FAST-METHOD ALLOCATE-INSTANCE (STRUCTURE-CLASS))|
                |(FAST-METHOD REINITIALIZE-INSTANCE :AFTER (SLOT-CLASS))|
                |(FAST-METHOD VALIDATE-SUPERCLASS (CLASS BUILT-IN-CLASS))|
                |(FAST-METHOD VALIDATE-SUPERCLASS (CLASS CLASS))|
                |(FAST-METHOD VALIDATE-SUPERCLASS (SLOT-CLASS FORWARD-REFERENCED-CLASS))|
                |(FAST-METHOD CHANGE-CLASS (STANDARD-OBJECT FUNCALLABLE-STANDARD-CLASS))|
                |(FAST-METHOD ALLOCATE-INSTANCE (STANDARD-CLASS))|
                |(FAST-METHOD REMOVE-DIRECT-SUBCLASS (CLASS CLASS))|
                |(FAST-METHOD REINITIALIZE-INSTANCE :BEFORE (SLOT-CLASS))|
                |(FAST-METHOD CHANGE-CLASS (STANDARD-OBJECT STANDARD-CLASS))|
                |(FAST-METHOD ALLOCATE-INSTANCE (FUNCALLABLE-STANDARD-CLASS))|
                |(FAST-METHOD ADD-DIRECT-SUBCLASS (CLASS CLASS))|
                |(FAST-METHOD MAKE-INSTANCE (CLASS))|
                |(FAST-METHOD VALIDATE-SUPERCLASS (FUNCALLABLE-STANDARD-CLASS STANDARD-CLASS))|
                |(FAST-METHOD SAME-SPECIALIZER-P (CLASS CLASS))|
                |(FAST-METHOD SPECIALIZER-DIRECT-METHODS (CLASS))|
                |(FAST-METHOD RAW-INSTANCE-ALLOCATOR (STANDARD-CLASS))|
                |(FAST-METHOD CLASS-DIRECT-SLOTS (BUILT-IN-CLASS))|
                |(FAST-METHOD CLASS-FINALIZED-P (PCL-CLASS))|
                |(FAST-METHOD SPECIALIZER-CLASS (CLASS))|
                |(FAST-METHOD SLOTS-FETCHER (STANDARD-CLASS))|
                |(FAST-METHOD MAKE-INSTANCES-OBSOLETE (STD-CLASS))|
                |(FAST-METHOD CLASS-SLOTS (BUILT-IN-CLASS))|
                |(FAST-METHOD FINALIZE-INHERITANCE (STD-CLASS))|
                |(FAST-METHOD CLASS-DEFAULT-INITARGS (SLOT-CLASS))|
                |(FAST-METHOD CLASS-DIRECT-DEFAULT-INITARGS (BUILT-IN-CLASS))|
                |(FAST-METHOD COMPUTE-CLASS-PRECEDENCE-LIST (SLOT-CLASS))|
                |(FAST-METHOD FINALIZE-INHERITANCE (STRUCTURE-CLASS))|
                |(FAST-METHOD COMPUTE-SLOTS :AROUND (STD-CLASS))|
                |(FAST-METHOD COMPUTE-DEFAULT-INITARGS (SLOT-CLASS))|
                |(FAST-METHOD COMPUTE-SLOTS (STD-CLASS))|
                |(FAST-METHOD RAW-INSTANCE-ALLOCATOR (FUNCALLABLE-STANDARD-CLASS))|
                |(FAST-METHOD COMPUTE-SLOTS (STRUCTURE-CLASS))|
                |(FAST-METHOD COMPUTE-SLOTS :AROUND (STRUCTURE-CLASS))|
                |(FAST-METHOD CLASS-DIRECT-DEFAULT-INITARGS (SLOT-CLASS))|
                |(FAST-METHOD WRAPPER-FETCHER (FUNCALLABLE-STANDARD-CLASS))|
                |(FAST-METHOD SLOTS-FETCHER (FUNCALLABLE-STANDARD-CLASS))|
                |(FAST-METHOD WRAPPER-FETCHER (STANDARD-CLASS))|
                |(FAST-METHOD CLASS-CONSTRUCTORS (SLOT-CLASS))|
                |(FAST-METHOD CLASS-DEFAULT-INITARGS (BUILT-IN-CLASS))|
                |(FAST-METHOD SPECIALIZER-DIRECT-GENERIC-FUNCTIONS (CLASS))|
                |(FAST-METHOD CLASS-SLOT-CELLS (STD-CLASS))|
                CLASS-PREDICATE-NAME
                |PCL::STRUCTURE-EFFECTIVE-SLOT-DEFINITION class predicate|
                |PCL::STRUCTURE-DIRECT-SLOT-DEFINITION class predicate|
                |PCL::STRUCTURE-SLOT-DEFINITION class predicate|
                |PCL::STRUCTURE-OBJECT class predicate|
                |LISP::SYMBOL class predicate|
                |PCL::EFFECTIVE-SLOT-DEFINITION class predicate|
                |(COMBINED-METHOD SHARED-INITIALIZE)|
                LEGAL-QUALIFIERS-P ADD-BOUNDP-METHOD
                LEGAL-LAMBDA-LIST-P |LISP::VECTOR class predicate|
                |SETF PCL GENERIC-FUNCTION-NAME|
                |(READER READER-FUNCTION)| |(READER PREDICATE-NAME)|
                |(READER READERS)| DESCRIBE-OBJECT
                |(READER CLASS-PRECEDENCE-LIST)|
                |(READER ACCESSOR-FLAGS)| |(READER DOCUMENTATION)|
                |(READER LOCATION)| CLASS-INITIALIZE-INFO
                |(SETF CLASS-SLOT-VALUE)| MAKE-WRITER-METHOD-FUNCTION
                |SETF PCL GF-DFUN-STATE|
                |(READER INCOMPATIBLE-SUPERCLASS-LIST)|
                |(READER SPECIALIZERS)|
                |(READER IDENTITY-WITH-ONE-ARGUMENT)|
                |(SETF CLASS-INITIALIZE-INFO)|
                |(READER PRETTY-ARGLIST)| |(READER DEFSTRUCT-FORM)|
                |SETF PCL CLASS-NAME| |SETF PCL SLOT-DEFINITION-NAME|
                |(WRITER READER-FUNCTION)|
                |(SETF CLASS-DEFSTRUCT-CONSTRUCTOR)|
                |(WRITER PREDICATE-NAME)| |(WRITER READERS)|
                |(READER INITFUNCTION)| |(READER WRITER-FUNCTION)|
                INITIALIZE-INTERNAL-SLOT-FUNCTIONS
                |SETF PCL SLOT-DEFINITION-TYPE|
                |(WRITER CLASS-PRECEDENCE-LIST)| |(READER WRITERS)|
                |(WRITER ACCESSOR-FLAGS)| |(READER INITFORM)|
                METHOD-COMBINATION-P |(WRITER DOCUMENTATION)|
                |(WRITER LOCATION)|
                |(CALL REAL-ENSURE-GF-USING-CLASS--GENERIC-FUNCTION)|
                |SETF PCL METHOD-GENERIC-FUNCTION|
                |SETF PCL GENERIC-FUNCTION-METHOD-COMBINATION|
                |SETF PCL GENERIC-FUNCTION-METHODS|
                |(READER SLOT-NAME)|
                |(WRITER INCOMPATIBLE-SUPERCLASS-LIST)|
                |SETF PCL SLOT-ACCESSOR-STD-P|
                |(CALL REAL-MAKE-METHOD-INITARGS-FORM)|
                |(READER ALLOCATION)| |(WRITER SPECIALIZERS)|
                |(CALL REAL-ENSURE-GF-USING-CLASS--NULL)|
                |(WRITER IDENTITY-WITH-ONE-ARGUMENT)|
                |(SETF METHOD-GENERIC-FUNCTION)| LEGAL-SPECIALIZERS-P
                |(WRITER PRETTY-ARGLIST)| |SETF PCL OBJECT-PLIST|
                |LISP::FLOAT class predicate| |(WRITER DEFSTRUCT-FORM)|
                |(READER GENERIC-FUNCTION)| |(READER FUNCTION)|
                |(READER LAMBDA-LIST)| |(READER SLOT-DEFINITION)|
                |PCL::CLASS-PROTOTYPE-SPECIALIZER class predicate|
                |SETF PCL CLASS-DEFSTRUCT-FORM|
                |SETF PCL SLOT-DEFINITION-INITFORM|
                |(READER CAN-PRECEDE-LIST)|
                |SETF PCL GENERIC-FUNCTION-METHOD-CLASS|
                |(READER PROTOTYPE)| |(WRITER INITFUNCTION)|
                |(WRITER WRITER-FUNCTION)| |(WRITER WRITERS)|
                SLOT-ACCESSOR-STD-P |(WRITER INITFORM)|
                |(READER DFUN-STATE)| |(READER FROM-DEFCLASS-P)|
                |SETF PCL GF-PRETTY-ARGLIST|
                |SETF PCL SLOT-DEFINITION-INITFUNCTION|
                |SETF PCL SLOT-DEFINITION-ALLOCATION|
                |SETF PCL SLOT-DEFINITION-INTERNAL-WRITER-FUNCTION|
                |SETF PCL SLOT-DEFINITION-INTERNAL-READER-FUNCTION|
                |SETF PCL SLOT-DEFINITION-BOUNDP-FUNCTION|
                |SETF PCL SLOT-DEFINITION-WRITER-FUNCTION|
                |SETF PCL SLOT-DEFINITION-READER-FUNCTION|
                |SETF PCL SLOT-DEFINITION-LOCATION|
                |SETF PCL SLOT-ACCESSOR-FUNCTION| |(WRITER SLOT-NAME)|
                |(BOUNDP NAME)| |(WRITER ALLOCATION)|
                |(READER FAST-FUNCTION)| |(READER METHOD-CLASS)|
                |(SETF OBJECT-PLIST)| |(READER METHOD-COMBINATION)|
                |(READER INTERNAL-READER-FUNCTION)|
                |(READER INTERNAL-WRITER-FUNCTION)|
                METHOD-COMBINATION-OPTIONS |(READER DIRECT-METHODS)|
                |(READER DIRECT-SLOTS)|
                |SETF PCL SLOT-DEFINITION-READERS|
                |(READER BOUNDP-FUNCTION)| |(WRITER GENERIC-FUNCTION)|
                |(WRITER FUNCTION)| |(READER DIRECT-SUPERCLASSES)|
                |(READER DIRECT-SUBCLASSES)| |SETF PCL DOCUMENTATION|
                |(WRITER LAMBDA-LIST)| |LISP::LIST class predicate|
                FUNCALLABLE-STANDARD-CLASS-P |(BOUNDP CLASS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT METHOD)|
                |(WRITER SLOT-DEFINITION)| |(READER OPTIONS)|
                |(READER METHODS)| |(WRITER CAN-PRECEDE-LIST)|
                |SETF PCL SLOT-VALUE-USING-CLASS|
                |SETF PCL SLOT-DEFINITION-CLASS|
                |(FAST-WRITER-METHOD STRUCTURE-SLOT-DEFINITION DEFSTRUCT-ACCESSOR-SYMBOL)|
                |(FAST-WRITER-METHOD SLOT-OBJECT DEFSTRUCT-ACCESSOR-SYMBOL)|
                |(WRITER PROTOTYPE)| |(BOUNDP OBJECT)| |(BOUNDP TYPE)|
                CLASS-CAN-PRECEDE-LIST |SETF PCL CLASS-SLOTS|
                |SETF PCL CLASS-DIRECT-SLOTS| SLOT-ACCESSOR-FUNCTION
                |(BOUNDP PLIST)|
                |SETF PCL CLASS-INCOMPATIBLE-SUPERCLASS-LIST|
                |SETF PCL SLOT-DEFINITION-WRITERS|
                |(FAST-WRITER-METHOD SLOT-OBJECT SOURCE)|
                |(WRITER DFUN-STATE)| |(WRITER FROM-DEFCLASS-P)|
                |(BOUNDP SLOTS)| SLOT-CLASS-P
                MAKE-READER-METHOD-FUNCTION LEGAL-METHOD-FUNCTION-P
                |(FAST-WRITER-METHOD SLOT-OBJECT ARG-INFO)|
                |(FAST-WRITER-METHOD SLOT-CLASS INITIALIZE-INFO)|
                |(FAST-WRITER-METHOD SLOT-OBJECT INITIALIZE-INFO)|
                |PCL::PLIST-MIXIN class predicate|
                |(WRITER FAST-FUNCTION)| |(WRITER METHOD-CLASS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT WRAPPER)|
                |(WRITER METHOD-COMBINATION)|
                |(WRITER INTERNAL-READER-FUNCTION)|
                |(WRITER INTERNAL-WRITER-FUNCTION)| GET-METHOD
                |(WRITER DIRECT-METHODS)| |(WRITER DIRECT-SLOTS)|
                |(FAST-WRITER-METHOD SLOT-DEFINITION INITARGS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT INITARGS)|
                |(FAST-WRITER-METHOD STRUCTURE-CLASS DEFSTRUCT-CONSTRUCTOR)|
                |(FAST-WRITER-METHOD SLOT-OBJECT DEFSTRUCT-CONSTRUCTOR)|
                |(FAST-WRITER-METHOD SLOT-OBJECT OPERATOR)|
                |(WRITER BOUNDP-FUNCTION)|
                |(WRITER DIRECT-SUPERCLASSES)|
                |(WRITER DIRECT-SUBCLASSES)|
                |(FAST-WRITER-METHOD SLOT-OBJECT CLASS-EQ-SPECIALIZER)|
                |(WRITER OPTIONS)| |(WRITER METHODS)|
                SHORT-METHOD-COMBINATION-P GF-ARG-INFO
                SPECIALIZER-METHOD-TABLE MAKE-METHOD-INITARGS-FORM
                CLASS-DEFSTRUCT-FORM
                |(FAST-READER-METHOD STANDARD-GENERIC-FUNCTION NAME)|
                |(FAST-READER-METHOD SLOT-OBJECT NAME)|
                |(FAST-READER-METHOD STANDARD-GENERIC-FUNCTION DFUN-STATE)|
                |(FAST-READER-METHOD SLOT-OBJECT DFUN-STATE)|
                |(FAST-READER-METHOD STANDARD-ACCESSOR-METHOD SLOT-NAME)|
                |(FAST-READER-METHOD SLOT-OBJECT SLOT-NAME)|
                |(FAST-READER-METHOD SLOT-DEFINITION NAME)|
                |(FAST-READER-METHOD CLASS NAME)|
                |(FAST-READER-METHOD CLASS PREDICATE-NAME)|
                |(FAST-READER-METHOD SLOT-OBJECT PREDICATE-NAME)|
                |LISP::INTEGER class predicate| GF-PRETTY-ARGLIST
                SAME-SPECIALIZER-P
                SLOT-DEFINITION-INTERNAL-READER-FUNCTION
                SLOT-DEFINITION-INTERNAL-WRITER-FUNCTION
                SLOT-DEFINITION-READER-FUNCTION
                SLOT-DEFINITION-WRITER-FUNCTION
                SLOT-DEFINITION-BOUNDP-FUNCTION
                |(FAST-READER-METHOD STANDARD-GENERIC-FUNCTION METHOD-CLASS)|
                |(FAST-READER-METHOD SLOT-OBJECT METHOD-CLASS)|
                |(FAST-READER-METHOD SLOT-OBJECT ACCESSOR-FLAGS)|
                |(FAST-READER-METHOD SLOT-DEFINITION CLASS)|
                |(FAST-READER-METHOD SLOT-OBJECT CLASS)|
                |(FAST-READER-METHOD STANDARD-METHOD-COMBINATION DOCUMENTATION)|
                |(FAST-READER-METHOD SLOT-OBJECT DOCUMENTATION)|
                |(FAST-READER-METHOD STANDARD-GENERIC-FUNCTION METHOD-COMBINATION)|
                |(FAST-READER-METHOD SLOT-OBJECT METHOD-COMBINATION)|
                |(FAST-READER-METHOD STANDARD-ACCESSOR-METHOD SLOT-DEFINITION)|
                |(FAST-READER-METHOD SLOT-OBJECT SLOT-DEFINITION)|
                |(FAST-READER-METHOD STANDARD-METHOD GENERIC-FUNCTION)|
                |(FAST-READER-METHOD SLOT-OBJECT GENERIC-FUNCTION)|
                |(FAST-READER-METHOD SLOT-OBJECT FUNCTION)|
                |(FAST-READER-METHOD STANDARD-METHOD FAST-FUNCTION)|
                |(FAST-READER-METHOD SLOT-OBJECT FAST-FUNCTION)|
                |(FAST-READER-METHOD STANDARD-EFFECTIVE-SLOT-DEFINITION LOCATION)|
                |(FAST-READER-METHOD SLOT-OBJECT LOCATION)|
                |(FAST-READER-METHOD EFFECTIVE-SLOT-DEFINITION READER-FUNCTION)|
                |(FAST-READER-METHOD SLOT-OBJECT READER-FUNCTION)|
                |(FAST-READER-METHOD EFFECTIVE-SLOT-DEFINITION WRITER-FUNCTION)|
                |(FAST-READER-METHOD SLOT-OBJECT WRITER-FUNCTION)|
                |(FAST-READER-METHOD EFFECTIVE-SLOT-DEFINITION BOUNDP-FUNCTION)|
                |(FAST-READER-METHOD SLOT-OBJECT BOUNDP-FUNCTION)|
                |(FAST-READER-METHOD STRUCTURE-SLOT-DEFINITION INTERNAL-READER-FUNCTION)|
                |(FAST-READER-METHOD SLOT-OBJECT INTERNAL-READER-FUNCTION)|
                |(FAST-READER-METHOD STRUCTURE-SLOT-DEFINITION INTERNAL-WRITER-FUNCTION)|
                |(FAST-READER-METHOD SLOT-OBJECT INTERNAL-WRITER-FUNCTION)|
                |(FAST-READER-METHOD STANDARD-SLOT-DEFINITION ALLOCATION)|
                |(FAST-READER-METHOD SLOT-OBJECT ALLOCATION)|
                |(FAST-READER-METHOD SLOT-DEFINITION INITFUNCTION)|
                |(FAST-READER-METHOD SLOT-OBJECT INITFUNCTION)|
                |(FAST-READER-METHOD LONG-METHOD-COMBINATION FUNCTION)|
                |(FAST-READER-METHOD TRACED-METHOD FUNCTION)|
                |(FAST-READER-METHOD TRACED-METHOD GENERIC-FUNCTION)|
                |(FAST-READER-METHOD STANDARD-METHOD SPECIALIZERS)|
                |(FAST-READER-METHOD SLOT-OBJECT SPECIALIZERS)|
                |(FAST-READER-METHOD SLOT-DEFINITION READERS)|
                |(FAST-READER-METHOD SLOT-OBJECT READERS)|
                |(FAST-READER-METHOD SLOT-DEFINITION WRITERS)|
                |(FAST-READER-METHOD SLOT-OBJECT WRITERS)|
                |(FAST-READER-METHOD EQL-SPECIALIZER OBJECT)|
                |(FAST-READER-METHOD SLOT-OBJECT OBJECT)|
                |(FAST-READER-METHOD CLASS-PROTOTYPE-SPECIALIZER OBJECT)|
                |(FAST-READER-METHOD CLASS-EQ-SPECIALIZER OBJECT)|
                |(FAST-READER-METHOD SLOT-OBJECT IDENTITY-WITH-ONE-ARGUMENT)|
                |(FAST-READER-METHOD SHORT-METHOD-COMBINATION IDENTITY-WITH-ONE-ARGUMENT)|
                |(FAST-READER-METHOD STANDARD-METHOD-COMBINATION TYPE)|
                |(FAST-READER-METHOD SLOT-OBJECT TYPE)|
                |(FAST-READER-METHOD SLOT-DEFINITION TYPE)|
                |(FAST-READER-METHOD PCL-CLASS PROTOTYPE)|
                |(FAST-READER-METHOD SLOT-OBJECT PROTOTYPE)|
                |(FAST-READER-METHOD SPECIALIZER TYPE)|
                |(FAST-READER-METHOD SLOT-DEFINITION INITFORM)|
                |(FAST-READER-METHOD SLOT-OBJECT INITFORM)|
                |(FAST-READER-METHOD STRUCTURE-CLASS DEFSTRUCT-FORM)|
                |(FAST-READER-METHOD SLOT-OBJECT DEFSTRUCT-FORM)|
                |(FAST-READER-METHOD STANDARD-GENERIC-FUNCTION PRETTY-ARGLIST)|
                |(FAST-READER-METHOD SLOT-OBJECT PRETTY-ARGLIST)|
                |(FAST-READER-METHOD STANDARD-METHOD LAMBDA-LIST)|
                |(FAST-READER-METHOD SLOT-OBJECT LAMBDA-LIST)|
                |(FAST-READER-METHOD PCL-CLASS CLASS-PRECEDENCE-LIST)|
                |(FAST-READER-METHOD SLOT-OBJECT CLASS-PRECEDENCE-LIST)|
                |(FAST-READER-METHOD PCL-CLASS CAN-PRECEDE-LIST)|
                |(FAST-READER-METHOD SLOT-OBJECT CAN-PRECEDE-LIST)|
                |(FAST-READER-METHOD PCL-CLASS INCOMPATIBLE-SUPERCLASS-LIST)|
                |(FAST-READER-METHOD SLOT-OBJECT INCOMPATIBLE-SUPERCLASS-LIST)|
                |(FAST-READER-METHOD PLIST-MIXIN PLIST)|
                |(FAST-READER-METHOD SLOT-OBJECT PLIST)|
                |(FAST-READER-METHOD SLOT-OBJECT FROM-DEFCLASS-P)|
                |(FAST-READER-METHOD STANDARD-METHOD-COMBINATION OPTIONS)|
                |(FAST-READER-METHOD SLOT-OBJECT OPTIONS)|
                |(FAST-READER-METHOD STANDARD-GENERIC-FUNCTION METHODS)|
                |(FAST-READER-METHOD SLOT-OBJECT METHODS)|
                |(FAST-READER-METHOD SLOT-CLASS DIRECT-SLOTS)|
                |(FAST-READER-METHOD SLOT-OBJECT DIRECT-SLOTS)|
                |(FAST-READER-METHOD SLOT-CLASS SLOTS)|
                |(FAST-READER-METHOD SLOT-OBJECT SLOTS)|
                |(FAST-READER-METHOD SLOT-OBJECT DIRECT-METHODS)|
                |(FAST-READER-METHOD CLASS DIRECT-SUPERCLASSES)|
                |(FAST-READER-METHOD SLOT-OBJECT DIRECT-SUPERCLASSES)|
                |(FAST-READER-METHOD CLASS DIRECT-SUBCLASSES)|
                |(FAST-READER-METHOD SLOT-OBJECT DIRECT-SUBCLASSES)|
                SLOT-DEFINITION-CLASS EQL-SPECIALIZER-OBJECT
                |PCL::DIRECT-SLOT-DEFINITION class predicate|
                CLASS-CONSTRUCTORS |(BOUNDP WRAPPER)| SLOTS-TO-INSPECT
                |(FAST-BOUNDP-METHOD SLOT-OBJECT NAME)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT DFUN-STATE)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT SLOT-NAME)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT PREDICATE-NAME)|
                |(BOUNDP DEFSTRUCT-ACCESSOR-SYMBOL)|
                SPECIALIZER-DIRECT-GENERIC-FUNCTIONS
                |(BOUNDP CLASS-EQ-SPECIALIZER)|
                |(SETF SLOT-DEFINITION-NAME)| ADD-WRITER-METHOD
                |(FAST-BOUNDP-METHOD SLOT-OBJECT METHOD-CLASS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT ACCESSOR-FLAGS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT CLASS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT DOCUMENTATION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT METHOD-COMBINATION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT SLOT-DEFINITION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT GENERIC-FUNCTION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT FUNCTION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT FAST-FUNCTION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT LOCATION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT READER-FUNCTION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT WRITER-FUNCTION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT BOUNDP-FUNCTION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT INTERNAL-READER-FUNCTION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT INTERNAL-WRITER-FUNCTION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT ALLOCATION)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT INITFUNCTION)|
                |(BOUNDP OPERATOR)| |(BOUNDP ARG-INFO)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT SPECIALIZERS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT READERS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT WRITERS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT OBJECT)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT TYPE)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT PROTOTYPE)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT INITFORM)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT DEFSTRUCT-FORM)|
                |(SETF SLOT-DEFINITION-CLASS)|
                |(SETF SLOT-VALUE-USING-CLASS)|
                |(SETF SLOT-DEFINITION-LOCATION)|
                |(SETF SLOT-DEFINITION-READER-FUNCTION)|
                |(SETF SLOT-DEFINITION-WRITER-FUNCTION)|
                |(SETF SLOT-DEFINITION-BOUNDP-FUNCTION)|
                |(SETF SLOT-DEFINITION-INTERNAL-READER-FUNCTION)|
                |(SETF SLOT-DEFINITION-INTERNAL-WRITER-FUNCTION)|
                |(SETF SLOT-DEFINITION-ALLOCATION)|
                |(SETF SLOT-DEFINITION-INITFUNCTION)|
                |(SETF SLOT-ACCESSOR-FUNCTION)|
                |(BOUNDP DEFSTRUCT-CONSTRUCTOR)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT PRETTY-ARGLIST)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT LAMBDA-LIST)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT CLASS-PRECEDENCE-LIST)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT CAN-PRECEDE-LIST)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT INCOMPATIBLE-SUPERCLASS-LIST)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT PLIST)|
                |(SETF SLOT-DEFINITION-READERS)|
                |(SETF SLOT-DEFINITION-WRITERS)|
                |(SETF SLOT-DEFINITION-TYPE)|
                |(SETF SLOT-DEFINITION-INITFORM)|
                |(BOUNDP INITIALIZE-INFO)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT OPTIONS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT METHODS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT DIRECT-SLOTS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT SLOTS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT DIRECT-METHODS)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT FROM-DEFCLASS-P)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT DIRECT-SUPERCLASSES)|
                |(FAST-BOUNDP-METHOD SLOT-OBJECT DIRECT-SUBCLASSES)|
                |(FAST-INTERNAL-READER-METHOD STANDARD-GENERIC-FUNCTION ARG-INFO)|
                |(BOUNDP INITARGS)| LONG-METHOD-COMBINATION-FUNCTION
                GENERIC-FUNCTION-P
                |PCL::SLOT-DEFINITION class predicate|
                |LISP::NULL class predicate| |(READER NAME)|
                |(READER CLASS)| |(FAST-METHOD SLOT-MISSING (T T T T))|
                |(FAST-METHOD (SETF DOCUMENTATION) (T T))|
                |(FAST-METHOD WRITER-METHOD-CLASS (SLOT-CLASS T))|
                |(FAST-METHOD SHARED-INITIALIZE :BEFORE (STANDARD-ACCESSOR-METHOD T))|
                |(FAST-METHOD SHARED-INITIALIZE :AFTER (STRUCTURE-SLOT-DEFINITION T))|
                |(FAST-METHOD FIND-METHOD-COMBINATION (GENERIC-FUNCTION (EQL STANDARD) T))|
                |(FAST-METHOD SHARED-INITIALIZE :AFTER (DOCUMENTATION-MIXIN T))|
                |(FAST-METHOD SLOT-UNBOUND (T T T))|
                |(FAST-METHOD REMOVE-NAMED-METHOD (T T))|
                |(FAST-METHOD (SETF SLOT-ACCESSOR-STD-P) (T EFFECTIVE-SLOT-DEFINITION T))|
                |(FAST-METHOD COMPUTE-SLOT-ACCESSOR-INFO (EFFECTIVE-SLOT-DEFINITION T T))|
                |(FAST-METHOD SHARED-INITIALIZE :AFTER (STRUCTURE-CLASS T))|
                |(FAST-METHOD SHARED-INITIALIZE :BEFORE (BUILT-IN-CLASS T))|
                |(FAST-METHOD READER-METHOD-CLASS (SLOT-CLASS T))|
                |(FAST-METHOD SHARED-INITIALIZE :AFTER (STD-CLASS T))|
                |(FAST-METHOD COMPUTE-EFFECTIVE-METHOD (GENERIC-FUNCTION SHORT-METHOD-COMBINATION T))|
                |(FAST-METHOD SHARED-INITIALIZE :AFTER (STANDARD-METHOD T))|
                |(FAST-METHOD SHARED-INITIALIZE :AFTER (CLASS-EQ-SPECIALIZER T))|
                |(FAST-METHOD SHARED-INITIALIZE :BEFORE (CLASS T))|
                |(FAST-METHOD SHARED-INITIALIZE :AFTER (STANDARD-SLOT-DEFINITION T))|
                |(FAST-METHOD (SETF CLASS-SLOT-VALUE) (T STD-CLASS T))|
                |(FAST-METHOD SHARED-INITIALIZE :BEFORE (STANDARD-METHOD T))|
                |(FAST-METHOD (SETF SLOT-ACCESSOR-FUNCTION) (T EFFECTIVE-SLOT-DEFINITION T))|
                |(FAST-METHOD SHARED-INITIALIZE :AFTER (STANDARD-ACCESSOR-METHOD T))|
                |(FAST-METHOD COMPUTE-EFFECTIVE-METHOD (GENERIC-FUNCTION LONG-METHOD-COMBINATION T))|
                |(FAST-METHOD ADD-WRITER-METHOD (SLOT-CLASS T T))|
                |(FAST-METHOD ADD-BOUNDP-METHOD (SLOT-CLASS T T))|
                |(FAST-METHOD SHARED-INITIALIZE :AFTER (EQL-SPECIALIZER T))|
                |(FAST-METHOD SHARED-INITIALIZE (SLOT-OBJECT T))|
                |(FAST-METHOD SHARED-INITIALIZE :BEFORE (STANDARD-GENERIC-FUNCTION T))|
                |(FAST-METHOD ADD-READER-METHOD (SLOT-CLASS T T))|
                |(FAST-METHOD LEGAL-QUALIFIERS-P (STANDARD-METHOD T))|
                |(FAST-METHOD DESCRIBE-OBJECT (T T))|
                |(FAST-METHOD LEGAL-SPECIALIZERS-P (STANDARD-METHOD T))|
                |(FAST-METHOD COMPUTE-APPLICABLE-METHODS-USING-CLASSES (GENERIC-FUNCTION T))|
                |(FAST-METHOD DESCRIBE-OBJECT (STANDARD-GENERIC-FUNCTION T))|
                |(FAST-METHOD DESCRIBE-OBJECT (CLASS T))|
                |(FAST-METHOD DEFAULT-INITARGS (SLOT-CLASS T))|
                |(FAST-METHOD CLASS-SLOT-VALUE (STD-CLASS T))|
                |(FAST-METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION (SLOT-CLASS T))|
                |(FAST-METHOD DESCRIBE-OBJECT (SLOT-OBJECT T))|
                |(FAST-METHOD SLOT-ACCESSOR-FUNCTION (EFFECTIVE-SLOT-DEFINITION T))|
                |(FAST-METHOD UPDATE-INSTANCE-FOR-REDEFINED-CLASS (STANDARD-OBJECT T T T))|
                |(FAST-METHOD EFFECTIVE-SLOT-DEFINITION-CLASS (STRUCTURE-CLASS T))|
                |(FAST-METHOD COMPUTE-APPLICABLE-METHODS (GENERIC-FUNCTION T))|
                |(FAST-METHOD REMOVE-BOUNDP-METHOD (SLOT-CLASS T))|
                |(FAST-METHOD INFORM-TYPE-SYSTEM-ABOUT-CLASS (STD-CLASS T))|
                |(FAST-METHOD PRINT-OBJECT (T T))|
                |(FAST-METHOD MAP-DEPENDENTS (DEPENDENT-UPDATE-MIXIN T))|
                |(FAST-METHOD DIRECT-SLOT-DEFINITION-CLASS (STRUCTURE-CLASS T))|
                |(FAST-METHOD MAKE-WRITER-METHOD-FUNCTION (FUNCALLABLE-STANDARD-CLASS T))|
                |(FAST-METHOD SLOT-ACCESSOR-STD-P (EFFECTIVE-SLOT-DEFINITION T))|
                |(FAST-METHOD MAKE-READER-METHOD-FUNCTION (SLOT-CLASS T))|
                |(FAST-METHOD EFFECTIVE-SLOT-DEFINITION-CLASS (STD-CLASS T))|
                |(FAST-METHOD PRINT-OBJECT (CLASS T))|
                |(FAST-METHOD REMOVE-DEPENDENT (DEPENDENT-UPDATE-MIXIN T))|
                |(FAST-METHOD UPDATE-GF-DFUN (STD-CLASS T))|
                |(FAST-METHOD PRINT-OBJECT (SLOT-DEFINITION T))|
                |(FAST-METHOD COMPATIBLE-META-CLASS-CHANGE-P (T T))|
                |(FAST-METHOD MAKE-WRITER-METHOD-FUNCTION (SLOT-CLASS T))|
                |(FAST-METHOD LEGAL-QUALIFIER-P (STANDARD-METHOD T))|
                |(FAST-METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION-INITARGS (SLOT-CLASS T))|
                |(FAST-METHOD LEGAL-LAMBDA-LIST-P (STANDARD-METHOD T))|
                |(FAST-METHOD LEGAL-SLOT-NAME-P (STANDARD-METHOD T))|
                |(FAST-METHOD PRINT-OBJECT (STANDARD-ACCESSOR-METHOD T))|
                |(FAST-METHOD COMPUTE-EFFECTIVE-SLOT-DEFINITION-INITARGS :AROUND (STRUCTURE-CLASS T))|
                |(FAST-METHOD ADD-DEPENDENT (DEPENDENT-UPDATE-MIXIN T))|
                |(FAST-METHOD MAKE-BOUNDP-METHOD-FUNCTION (SLOT-CLASS T))|
                |(FAST-METHOD LEGAL-DOCUMENTATION-P (STANDARD-METHOD T))|
                |(FAST-METHOD LEGAL-SPECIALIZER-P (STANDARD-METHOD T))|
                |(FAST-METHOD PRINT-OBJECT (STANDARD-METHOD T))|
                |(FAST-METHOD PRINT-OBJECT (GENERIC-FUNCTION T))|
                |(FAST-METHOD PRINT-OBJECT (STANDARD-METHOD-COMBINATION T))|
                |(FAST-METHOD DIRECT-SLOT-DEFINITION-CLASS (STD-CLASS T))|
                |(FAST-METHOD LEGAL-METHOD-FUNCTION-P (STANDARD-METHOD T))|
                |(FAST-METHOD REMOVE-WRITER-METHOD (SLOT-CLASS T))|
                |(FAST-METHOD INFORM-TYPE-SYSTEM-ABOUT-CLASS (STRUCTURE-CLASS T))|
                |(FAST-METHOD REMOVE-READER-METHOD (SLOT-CLASS T))|
                |(FAST-METHOD MAKE-READER-METHOD-FUNCTION (FUNCALLABLE-STANDARD-CLASS T))|
                LEGAL-SLOT-NAME-P |(READER OBJECT)| |(READER TYPE)|
                CLASS-WRAPPER |(READER PLIST)|
                |(FAST-METHOD NO-APPLICABLE-METHOD (T))|
                |(FAST-METHOD DOCUMENTATION (T))|
                |(FAST-METHOD CLASS-PREDICATE-NAME (T))|
                |(READER SLOTS)| |(WRITER NAME)| DEFINITION-SOURCE
                |PCL::SLOT-OBJECT class predicate| DEFAULT-INITARGS
                |(WRITER CLASS)| CLASS-SLOT-VALUE |(WRITER OBJECT)|
                |(WRITER TYPE)|
                |(FAST-METHOD ENSURE-CLASS-USING-CLASS (T NULL))|
                |(WRITER PLIST)| |(WRITER SLOTS)|
                |PCL::DOCUMENTATION-MIXIN class predicate|
                FORWARD-REFERENCED-CLASS-P GF-FAST-METHOD-FUNCTION-P
                LEGAL-QUALIFIER-P METHOD-P
                |PCL::SPECIALIZER-WITH-OBJECT class predicate|
                CLASS-SLOT-CELLS
                |(COMBINED-METHOD REINITIALIZE-INSTANCE)|
                |(COMBINED-METHOD INITIALIZE-INSTANCE)|
                STANDARD-ACCESSOR-METHOD-P |(SETF CLASS-NAME)|
                STANDARD-METHOD-P STANDARD-READER-METHOD-P
                STANDARD-GENERIC-FUNCTION-P |(READER WRAPPER)|
                |(READER DEFSTRUCT-ACCESSOR-SYMBOL)|
                |(READER CLASS-EQ-SPECIALIZER)|
                COMPUTE-DEFAULT-INITARGS
                COMPUTE-EFFECTIVE-SLOT-DEFINITION-INITARGS
                |(SETF CLASS-DEFSTRUCT-FORM)|
                |(CALL REAL-MAKE-METHOD-LAMBDA)|
                |(SETF CLASS-INCOMPATIBLE-SUPERCLASS-LIST)|
                |SETF PCL CLASS-SLOT-VALUE| |(SETF CLASS-DIRECT-SLOTS)|
                |(SETF CLASS-SLOTS)| DO-STANDARD-DEFSETF-1
                |(READER OPERATOR)| |(CALL REAL-ADD-METHOD)|
                |(CALL REAL-REMOVE-METHOD)| |(CALL REAL-GET-METHOD)|
                |(READER ARG-INFO)| METHOD-COMBINATION-TYPE
                |(READER DEFSTRUCT-CONSTRUCTOR)|
                |(INTERNAL-READER-METHOD STANDARD-GENERIC-FUNCTION ARG-INFO)|
                |(READER INITIALIZE-INFO)| |(WRITER WRAPPER)|
                STANDARD-CLASS-P |LISP::NUMBER class predicate|
                LEGAL-SPECIALIZER-P
                |PCL::LONG-METHOD-COMBINATION class predicate|
                |(WRITER DEFSTRUCT-ACCESSOR-SYMBOL)|
                COMPUTE-SLOT-ACCESSOR-INFO |(READER INITARGS)|
                |(WRITER CLASS-EQ-SPECIALIZER)|
                STANDARD-BOUNDP-METHOD-P FDEFINE-CAREFULLY
                |(SETF DOCUMENTATION)| RAW-INSTANCE-ALLOCATOR
                |SETF PCL CLASS-INITIALIZE-INFO|
                |SETF PCL SLOT-DEFINITION-DEFSTRUCT-ACCESSOR-SYMBOL|
                |(WRITER OPERATOR)| |(WRITER ARG-INFO)|
                COMPUTE-DISCRIMINATING-FUNCTION-ARGLIST-INFO
                STANDARD-WRITER-METHOD-P
                CLASS-INCOMPATIBLE-SUPERCLASS-LIST
                |(WRITER DEFSTRUCT-CONSTRUCTOR)|
                |PCL::TRACED-METHOD class predicate| WRAPPER-FETCHER
                MAKE-A-METHOD |(WRITER INITIALIZE-INFO)|
                METHOD-COMBINATION-DOCUMENTATION
                |SETF PCL SLOT-DEFINITION-INITARGS|
                REMOVE-BOUNDP-METHOD ADD-NAMED-METHOD
                |(WRITER INITARGS)|
                |SETF PCL CLASS-DEFSTRUCT-CONSTRUCTOR|
                |LISP::CONS class predicate| |(BOUNDP METHOD)|
                |(FAST-WRITER-METHOD STANDARD-GENERIC-FUNCTION NAME)|
                |(FAST-WRITER-METHOD SLOT-OBJECT NAME)|
                |(FAST-WRITER-METHOD STANDARD-GENERIC-FUNCTION DFUN-STATE)|
                |(FAST-WRITER-METHOD SLOT-OBJECT DFUN-STATE)|
                |(FAST-WRITER-METHOD SLOT-OBJECT SLOT-NAME)|
                |(FAST-WRITER-METHOD SLOT-DEFINITION NAME)|
                |(FAST-WRITER-METHOD CLASS NAME)|
                |(FAST-WRITER-METHOD SLOT-OBJECT PREDICATE-NAME)|
                |(BOUNDP SOURCE)| |(SETF GF-DFUN-STATE)|
                SHORT-COMBINATION-OPERATOR
                |(FAST-WRITER-METHOD STANDARD-GENERIC-FUNCTION METHOD-CLASS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT METHOD-CLASS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT ACCESSOR-FLAGS)|
                |(FAST-WRITER-METHOD SLOT-DEFINITION CLASS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT CLASS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT DOCUMENTATION)|
                |(FAST-WRITER-METHOD STANDARD-GENERIC-FUNCTION METHOD-COMBINATION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT METHOD-COMBINATION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT SLOT-DEFINITION)|
                |(FAST-WRITER-METHOD STANDARD-METHOD GENERIC-FUNCTION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT GENERIC-FUNCTION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT FUNCTION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT FAST-FUNCTION)|
                |(FAST-WRITER-METHOD STANDARD-EFFECTIVE-SLOT-DEFINITION LOCATION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT LOCATION)|
                |(FAST-WRITER-METHOD EFFECTIVE-SLOT-DEFINITION READER-FUNCTION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT READER-FUNCTION)|
                |(FAST-WRITER-METHOD EFFECTIVE-SLOT-DEFINITION WRITER-FUNCTION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT WRITER-FUNCTION)|
                |(FAST-WRITER-METHOD EFFECTIVE-SLOT-DEFINITION BOUNDP-FUNCTION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT BOUNDP-FUNCTION)|
                |(FAST-WRITER-METHOD STRUCTURE-SLOT-DEFINITION INTERNAL-READER-FUNCTION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT INTERNAL-READER-FUNCTION)|
                |(FAST-WRITER-METHOD STRUCTURE-SLOT-DEFINITION INTERNAL-WRITER-FUNCTION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT INTERNAL-WRITER-FUNCTION)|
                |(FAST-WRITER-METHOD STANDARD-SLOT-DEFINITION ALLOCATION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT ALLOCATION)|
                |(FAST-WRITER-METHOD SLOT-DEFINITION INITFUNCTION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT INITFUNCTION)|
                |(FAST-WRITER-METHOD TRACED-METHOD GENERIC-FUNCTION)|
                |(FAST-WRITER-METHOD SLOT-OBJECT SPECIALIZERS)|
                |(FAST-WRITER-METHOD SLOT-DEFINITION READERS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT READERS)|
                |(FAST-WRITER-METHOD SLOT-DEFINITION WRITERS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT WRITERS)|
                |(FAST-WRITER-METHOD SLOT-OBJECT OBJECT)|
                |(FAST-WRITER-METHOD SLOT-OBJECT IDENTITY-WITH-ONE-ARGUMENT)|
                |(FAST-WRITER-METHOD SLOT-OBJECT TYPE)|
                |(FAST-WRITER-METHOD SLOT-DEFINITION TYPE)|
                |(FAST-WRITER-METHOD SLOT-OBJECT PROTOTYPE)|
                REMOVE-NAMED-METHOD
                |(FAST-WRITER-METHOD SLOT-DEFINITION INITFORM)|
                |(FAST-WRITER-METHOD SLOT-OBJECT INITFORM)|
                |(FAST-WRITER-METHOD STRUCTURE-CLASS DEFSTRUCT-FORM)|
                |(FAST-WRITER-METHOD SLOT-OBJECT DEFSTRUCT-FORM)|
                |(FAST-WRITER-METHOD STANDARD-GENERIC-FUNCTION PRETTY-ARGLIST)|
                |(FAST-WRITER-METHOD SLOT-OBJECT PRETTY-ARGLIST)|
                |(FAST-WRITER-METHOD SLOT-OBJECT LAMBDA-LIST)|
                |(FAST-WRITER-METHOD SLOT-OBJECT CLASS-PRECEDENCE-LIST)|
                |(FAST-WRITER-METHOD SLOT-OBJECT CAN-PRECEDE-LIST)|
                |(FAST-WRITER-METHOD PCL-CLASS INCOMPATIBLE-SUPERCLASS-LIST)|
                |(FAST-WRITER-METHOD SLOT-OBJECT INCOMPATIBLE-SUPERCLASS-LIST)|
                |(FAST-WRITER-METHOD PLIST-MIXIN PLIST)|
                |(FAST-WRITER-METHOD SLOT-OBJECT PLIST)|
                LEGAL-DOCUMENTATION-P CLASS-DIRECT-SUPERCLASSES
                CLASS-DIRECT-SUBCLASSES CLASS-DIRECT-DEFAULT-INITARGS
                SLOT-DEFINITION-READERS SLOT-VALUE-USING-CLASS
                COMPUTE-APPLICABLE-METHODS CLASS-NAME CLASSP
                CLASS-PROTOTYPE READER-METHOD-CLASS REMOVE-METHOD
                SLOT-DEFINITION-INITFORM
                UPDATE-INSTANCE-FOR-REDEFINED-CLASS
                UPDATE-INSTANCE-FOR-DIFFERENT-CLASS CHANGE-CLASS
                METHOD-FUNCTION DIRECT-SLOT-DEFINITION-CLASS
                MAKE-METHOD-LAMBDA EFFECTIVE-SLOT-DEFINITION-CLASS
                CLASS-SLOTS COMPUTE-SLOTS SLOT-DEFINITION-NAME
                FINALIZE-INHERITANCE GENERIC-FUNCTION-LAMBDA-LIST
                CLASS-DIRECT-SLOTS CLASS-DEFAULT-INITARGS
                COMPUTE-DISCRIMINATING-FUNCTION CLASS-FINALIZED-P
                GENERIC-FUNCTION-NAME REMOVE-DEPENDENT
                COMPUTE-CLASS-PRECEDENCE-LIST ADD-DEPENDENT
                SLOT-BOUNDP-USING-CLASS ACCESSOR-METHOD-SLOT-DEFINITION
                SHARED-INITIALIZE ADD-DIRECT-METHOD
                SLOT-DEFINITION-LOCATION SLOT-DEFINITION-INITFUNCTION
                SLOT-DEFINITION-ALLOCATION ADD-METHOD
                GENERIC-FUNCTION-METHOD-CLASS METHOD-SPECIALIZERS
                SLOT-DEFINITION-INITARGS WRITER-METHOD-CLASS
                ADD-DIRECT-SUBCLASS SPECIALIZER-DIRECT-METHODS
                GENERIC-FUNCTION-METHOD-COMBINATION ALLOCATE-INSTANCE
                COMPUTE-EFFECTIVE-METHOD SLOT-DEFINITION-TYPE
                SLOT-UNBOUND INITIALIZE-INSTANCE FUNCTION-KEYWORDS
                REINITIALIZE-INSTANCE VALIDATE-SUPERCLASS
                GENERIC-FUNCTION-METHODS REMOVE-DIRECT-METHOD
                METHOD-LAMBDA-LIST MAKE-INSTANCE
                COMPUTE-EFFECTIVE-SLOT-DEFINITION PRINT-OBJECT
                METHOD-QUALIFIERS METHOD-GENERIC-FUNCTION
                REMOVE-DIRECT-SUBCLASS MAKE-INSTANCES-OBSOLETE
                SLOT-MAKUNBOUND-USING-CLASS
                ENSURE-GENERIC-FUNCTION-USING-CLASS SLOT-MISSING
                MAP-DEPENDENTS UPDATE-DEPENDENT FIND-METHOD-COMBINATION
                ENSURE-CLASS-USING-CLASS NO-APPLICABLE-METHOD
                SLOT-DEFINITION-WRITERS
                COMPUTE-APPLICABLE-METHODS-USING-CLASSES
                CLASS-PRECEDENCE-LIST))
  (SETF (GET V 'SYSTEM::PROCLAIMED-CLOSURE) T)) 
