
(COMMON-LISP::IN-PACKAGE "SYSTEM") 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             ((COMMON-LISP::VECTOR COMMON-LISP::CHARACTER
                  COMMON-LISP::*))
             COMMON-LISP::T)
         SYSTEM::RESET-SYS-PATHS)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T)
             (COMMON-LISP::VECTOR COMMON-LISP::T))
         SYSTEM::CONTEXT-VEC)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             ((COMMON-LISP::INTEGER -9223372036854775808
                  9223372036854775807))
             COMMON-LISP::T)
         SYSTEM::PUSH-CONTEXT SYSTEM::GET-CONTEXT)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION COMMON-LISP::NIL COMMON-LISP::T)
         SLOOP::PARSE-LOOP-DO ANSI-LOOP::LOOP-WHEN-IT-VARIABLE
         SYSTEM::GET-INDEX-NODE SLOOP::LOOP-PEEK
         ANSI-LOOP::LOOP-POP-SOURCE SYSTEM::STEP-READ-LINE
         SYSTEM::SET-UP-TOP-LEVEL SLOOP::LOOP-POP SYSTEM::SET-ENV
         SYSTEM::DBL COMMON-LISP::TYPE-ERROR SYSTEM::INSPECT-INDENT
         SLOOP::PARSE-LOOP-COLLECT SYSTEM::CLEANUP
         SYSTEM::DEFAULT-SYSTEM-BANNER
         SYSTEM::CURRENT-DIRECTORY-PATHNAME ANSI-LOOP::LOOP-DO-WITH
         SYSTEM::INIT-BREAK-POINTS SYSTEM::TEST-ERROR
         SYSTEM::GET-SIG-FN-NAME SLOOP::PARSE-ONE-WHEN-CLAUSE
         ANSI-LOOP::LOOP-DO-DO SYSTEM::READ-EVALUATED-FORM
         SYSTEM::INSPECT-INDENT-1 ANSI-LOOP::LOOP-DO-NAMED
         SLOOP::PARSE-LOOP-FOR SYSTEM::ALL-TRACE-DECLARATIONS
         ANSI-LOOP::LOOP-GET-FORM ANSI-LOOP::LOOP-BIND-BLOCK
         SLOOP::PARSE-LOOP-WHEN SYSTEM::TOP-LEVEL
         SYSTEM::DM-TOO-FEW-ARGUMENTS SYSTEM::KCL-TOP-RESTARTS
         SYSTEM::DEFAULT-INFO-HOTLIST SYSTEM::SHOW-RESTARTS
         SYSTEM::DM-TOO-MANY-ARGUMENTS SYSTEM::SETUP-LINEINFO
         SYSTEM::GET-TEMP-DIR ANSI-LOOP::LOOP-ITERATION-DRIVER
         SLOOP::PARSE-LOOP1 SLOOP::LOOP-UN-POP
         ANSI-LOOP::LOOP-DO-FINALLY SYSTEM::INSPECT-READ-LINE
         ANSI-LOOP::LOOP-CONTEXT SYSTEM::SET-CURRENT
         ANSI-LOOP::LOOP-DO-REPEAT SYSTEM::ILLEGAL-BOA
         COMMON-LISP::LISP-IMPLEMENTATION-VERSION
         ANSI-LOOP::LOOP-DO-RETURN ANSI-LOOP::LOOP-DO-INITIALLY
         ANSI-LOOP::LOOP-GET-PROGN)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T)
             COMMON-LISP::HASH-TABLE)
         SYSTEM::CONTEXT-SPICE)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T)
             (COMMON-LISP::OR COMMON-LISP::NULL
                 COMMON-LISP::HASH-TABLE))
         SYSTEM::CONTEXT-HASH)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::FIXNUM)
         ANSI-LOOP::DUPLICATABLE-CODE-P SYSTEM::RELATIVE-LINE
         SYSTEM::LENEL SYSTEM::GET-NODE-INDEX SYSTEM::FASLINK
         SYSTEM::THE-END)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::T)
         SLOOP::IN-PACKAGE-SLOOP-MAP SLOOP::DESETQ1
         COMMON-LISP::LOGANDC2 ANSI-LOOP::MAKE-LOOP-MINIMAX
         COMMON-LISP::WRITE-BYTE SYSTEM::MATCH-DIMENSIONS
         SLOOP::IN-CAREFULLY-SLOOP-FOR SLOOP::SUM-SLOOP-COLLECT
         SYSTEM::DOT-DIR-P SLOOP::IN-FRINGE-SLOOP-MAP
         SLOOP::COLLATE-SLOOP-COLLECT ANSI-LOOP::LOOP-TMEMBER
         FPE::READ-OPERANDS SYSTEM::IN-INTERVAL-P SYSTEM::SUBSTRINGP
         FPE::PAREN-READER ANSI-LOOP::HIDE-VARIABLE-REFERENCES
         SYSTEM::QUOTATION-READER SYSTEM::ALL-MATCHES SYSTEM::GET-MATCH
         SYSTEM::ADD-FILE ANSI-LOOP::LOOP-DO-ALWAYS SLOOP::THE-TYPE
         SYSTEM::?PUSH SYSTEM::INCREMENT-CURSOR
         SYSTEM::CHECK-SEQ-START-END SLOOP::MAKE-VALUE
         SLOOP::THEREIS-SLOOP-COLLECT ANSI-LOOP::LOOP-DO-WHILE
         COMMON-LISP::COERCE ANSI-LOOP::LOOP-TEQUAL
         ANSI-LOOP::LOOP-DECLARE-VARIABLE COMMON-LISP::LOGNAND
         COMMON-LISP::LOGORC1 SYSTEM::BREAK-STEP-NEXT
         SLOOP::LOGXOR-SLOOP-COLLECT COMMON-LISP::LOGNOR
         COMPILER::COMPILER-DEF-HOOK ANSI-LOOP::LOOP-TASSOC
         SYSTEM::GET-LINE-OF-FORM SLOOP::MAXIMIZE-SLOOP-COLLECT
         ANSI-LOOP::LOOP-DO-IF SYSTEM::SETF-EXPAND SYSTEM::DM-V
         SYSTEM::ITERATE-OVER-BKPTS COMMON-LISP::NTHCDR
         SYSTEM::CONDITION-PASS SYSTEM::DISPLAY-COMPILED-ENV
         COMMON-LISP::LDB-TEST ANSI-LOOP::LOOP-MAYBE-BIND-FORM
         SYSTEM::SUPER-GO SYSTEM::SETF-LOGICAL-PATHNAME-TRANSLATIONS
         FPE::RF SYSTEM::SUB-INTERVAL-P SYSTEM::LEFT-PARENTHESIS-READER
         COMMON-LISP::FILE-STRING-LENGTH SYSTEM::OBJLT SYSTEM::MSUB
         SYSTEM::COERCE-TO-STRING SYSTEM::SAFE-EVAL
         SYSTEM::SET-PATH-STREAM-NAME SYSTEM::SET-BACK
         ANSI-LOOP::LOOP-NOTE-MINIMAX-OPERATION COMMON-LISP::LOGTEST
         SYSTEM::*BREAK-POINTS* SLOOP::=-SLOOP-FOR
         SLOOP::MINIMIZE-SLOOP-COLLECT SYSTEM::KEYWORD-SUPPLIED-P
         SLOOP::COUNT-SLOOP-COLLECT FPE::%-READER COMMON-LISP::LOGORC2
         SYSTEM::SEQUENCE-CURSOR SYSTEM::LOOKUP-KEYWORD
         COMMON-LISP::BYTE SYSTEM::PARSE-SLOT-DESCRIPTION
         COMMON-LISP::LOGANDC1 SYSTEM::DM-NTH-CDR FPE::0-READER
         SLOOP::L-EQUAL SYSTEM::LIST-DELQ SYSTEM::DM-NTH
         COMMON-LISP::LDB SYSTEM::SETF-HELPER
         SLOOP::NEVER-SLOOP-COLLECT SLOOP::PARSE-LOOP-MAP
         COMMON-LISP::NTH SYSTEM::BREAK-STEP-INTO
         SYSTEM::GET-INFO-CHOICES SLOOP::IN-TABLE-SLOOP-MAP
         SYSTEM::GET-NODES COMMON-LISP::VECTOR-PUSH
         COMMON-LISP::PATHNAME-MATCH-P SYSTEM::DBL-UP
         ANSI-LOOP::LOOP-LOOKUP-KEYWORD FPE::READ-INSTRUCTION
         SLOOP::ALWAYS-SLOOP-COLLECT SYSTEM::SET-DIR SYSTEM::INFO-AUX
         SYSTEM::DISPLAY-ENV COMMON-LISP::DOCUMENTATION
         SYSTEM::OVERWRITE-SLOT-DESCRIPTIONS)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T COMMON-LISP::*)
             COMMON-LISP::*)
         COMMON-LISP::APROPOS ANSI-LOOP::LOOP-CONSTANT-FOLD-IF-POSSIBLE
         COMMON-LISP::FFLOOR SYSTEM::PRINT-DOC SYSTEM::INFO
         SYSTEM::PARSE-BODY-HEADER COMMON-LISP::INVOKE-RESTART
         SYSTEM::BREAK-FUNCTION SYSTEM::SHOW-INFO COMMON-LISP::FROUND
         COMMON-LISP::GET-SETF-EXPANSION COMMON-LISP::PARSE-NAMESTRING
         SYSTEM::APROPOS-DOC COMMON-LISP::ENSURE-DIRECTORIES-EXIST
         COMMON-LISP::USE-VALUE COMMON-LISP::READ-FROM-STRING
         COMMON-LISP::FTRUNCATE COMMON-LISP::STORE-VALUE
         SYSTEM::STEPPER SYSTEM::GET-SETF-METHOD-MULTIPLE-VALUE
         COMMON-LISP::APROPOS-LIST COMMON-LISP::FCEILING
         COMMON-LISP::WRITE-TO-STRING
         COMMON-LISP::DECODE-UNIVERSAL-TIME)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::T)
         SYSTEM::SETF-EXPAND-1 SLOOP::LOOP-PARSE-ADDITIONAL-COLLECTIONS
         SYSTEM::WARN-VERSION ANSI-LOOP::LOOP-TRANSLATE
         ANSI-LOOP::LOOP-FOR-IN ANSI-LOOP::PRINT-LOOP-UNIVERSE
         ANSI-LOOP::LOOP-STANDARD-EXPANSION
         ANSI-LOOP::LOOP-ANSI-FOR-EQUALS SYSTEM::DM-VL
         SYSTEM::SHARP-A-READER COMMON-LISP::DEPOSIT-FIELD
         SYSTEM::RESTART-CASE-EXPRESSION-CONDITION
         SYSTEM::APPLY-DISPLAY-FUN ANSI-LOOP::HIDE-VARIABLE-REFERENCE
         SYSTEM::FLOATING-POINT-ERROR SYSTEM::GET-SLOT-POS
         ANSI-LOOP::LOOP-MAKE-ITERATION-VARIABLE
         SYSTEM::MAKE-BREAK-POINT SYSTEM::SHARP-V-READER
         SYSTEM::TO-REGEXP-OR-NAMESTRING ANSI-LOOP::LOOP-FOR-ON
         SYSTEM::SHARP-U-READER ANSI-LOOP::LOOP-SUM-COLLECTION
         SYSTEM::SHARP-P-READER SYSTEM::MAKE-T-TYPE
         ANSI-LOOP::LOOP-FOR-ACROSS SYSTEM::MFR SYSTEM::RECURSE-DIR
         SYSTEM::PATHNAME-PARSE ANSI-LOOP::LOOP-FOR-BEING
         COMMON-LISP::DPB SYSTEM::SHARP-DQ-READER
         SYSTEM::CHECK-TRACE-ARGS SYSTEM::DEFMACRO*
         SYSTEM::CHECK-S-DATA FPE::REF)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::*)
             COMMON-LISP::T)
         SYSTEM::FIND-IHS COMMON-LISP::NSET-DIFFERENCE
         COMMON-LISP::BIT-NAND SYSTEM::BREAK-CALL
         COMMON-LISP::COUNT-IF-NOT COMMON-LISP::DELETE
         SYSTEM::INTERNAL-COUNT COMMON-LISP::BIT-ORC1
         COMMON-LISP::DELETE-IF COMMON-LISP::BIT-ANDC1
         SYSTEM::VECTOR-PUSH-STRING COMMON-LISP::MISMATCH
         COMMON-LISP::NOTEVERY SYSTEM::PROCESS-ERROR COMMON-LISP::TYPEP
         COMMON-LISP::BIT-IOR COMMON-LISP::BIT-EQV
         COMMON-LISP::COUNT-IF COMMON-LISP::REMOVE-IF
         COMMON-LISP::EVERY COMMON-LISP::POSITION-IF-NOT
         COMMON-LISP::ADJUST-ARRAY COMMON-LISP::VECTOR-PUSH-EXTEND
         SYSTEM::INTERNAL-COUNT-IF-NOT COMMON-LISP::COUNT
         COMMON-LISP::DELETE-IF-NOT COMMON-LISP::NINTERSECTION
         COMMON-LISP::FIND-IF-NOT COMMON-LISP::BIT-ORC2
         COMMON-LISP::SUBSETP COMMON-LISP::SOME SYSTEM::WREADDIR
         COMMON-LISP::SET-DIFFERENCE COMMON-LISP::UNION
         COMMON-LISP::BIT-XOR SLOOP::PARSE-LOOP-MACRO
         COMMON-LISP::REPLACE COMMON-LISP::REMOVE
         SLOOP::LOOP-ADD-BINDING COMMON-LISP::BIT-ANDC2
         COMMON-LISP::READ-SEQUENCE COMMON-LISP::CERROR
         COMMON-LISP::INTERSECTION COMMON-LISP::POSITION-IF
         ANSI-LOOP::LOOP-CHECK-DATA-TYPE SYSTEM::INTERNAL-COUNT-IF
         COMMON-LISP::NUNION COMMON-LISP::WRITE-SEQUENCE
         COMMON-LISP::MAP-INTO COMMON-LISP::MAKE-SEQUENCE
         COMMON-LISP::SET-EXCLUSIVE-OR SLOOP::IN-ARRAY-SLOOP-FOR
         COMMON-LISP::FIND-IF COMMON-LISP::SEARCH COMMON-LISP::FILL
         COMMON-LISP::FIND COMMON-LISP::NOTANY
         COMMON-LISP::NSET-EXCLUSIVE-OR COMMON-LISP::BIT-NOR
         COMMON-LISP::REMOVE-IF-NOT COMMON-LISP::POSITION
         COMMON-LISP::BIT-AND)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T)
             COMMON-LISP::T)
         SYSTEM::FIND-LINE-IN-FUN ANSI-LOOP::LOOP-FOR-ARITHMETIC
         SYSTEM::EXPAND-RANGE SYSTEM::MAYBE-BREAK SYSTEM::MINMAX
         SLOOP::FIRST-USE-SLOOP-FOR SLOOP::FIRST-SLOOP-FOR
         SYSTEM::SETF-STRUCTURE-ACCESS SYSTEM::DO-BREAK-LEVEL
         SYSTEM::CALL-TEST SYSTEM::ELEMENT SYSTEM::LOAD-PATHNAME
         SYSTEM::COERCE-TO-CONDITION SYSTEM::ELSUB)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::*)
             COMMON-LISP::T)
         SLOOP::DEF-LOOP-INTERNAL COMMON-LISP::MERGE
         SYSTEM::PRINT-STACK-FRAME)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::*)
             COMMON-LISP::T)
         COMMON-LISP::ENCODE-UNIVERSAL-TIME)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::*)
             COMMON-LISP::T)
         ANSI-LOOP::LOOP-PACKAGE-SYMBOLS-ITERATION-PATH
         SYSTEM::COMPLETE-PROP SYSTEM::CHECK-TYPE-SYMBOL
         COMMON-LISP::NSUBSTITUTE
         ANSI-LOOP::LOOP-SEQUENCE-ELEMENTS-PATH COMMON-LISP::SUBSTITUTE
         COMMON-LISP::TRANSLATE-PATHNAME COMMON-LISP::NSUBSTITUTE-IF
         COMMON-LISP::MAP SLOOP::LOOP-DECLARE-BINDING SYSTEM::WALK-DIR
         SYSTEM::MATCH-COMPONENT ANSI-LOOP::LOOP-MAKE-VARIABLE
         ANSI-LOOP::ADD-LOOP-PATH COMMON-LISP::SUBSTITUTE-IF
         COMMON-LISP::NSUBSTITUTE-IF-NOT SYSTEM::MME2
         ANSI-LOOP::LOOP-HASH-TABLE-ITERATION-PATH
         COMMON-LISP::SUBSTITUTE-IF-NOT SYSTEM::PUSH-LET-BINDING)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T
                 (COMMON-LISP::INTEGER -9223372036854775808
                     9223372036854775807))
             COMMON-LISP::T)
         SYSTEM::SHARP-SHARP-READER SYSTEM::SHARP-EQ-READER)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::T)
         SYSTEM::DO-ARG-COUNT-ERROR SYSTEM::PUSH-SUB-LIST-BINDING)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::T)
         SYSTEM::MAKE-CONSTRUCTOR SYSTEM::MAKE-PREDICATE)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T)
             COMMON-LISP::T)
         ANSI-LOOP::LOOP-SEQUENCER)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T COMMON-LISP::*)
             COMMON-LISP::T)
         SYSTEM::UNIVERSAL-ERROR-HANDLER)) 
(COMMON-LISP::MAPC
    (COMMON-LISP::LAMBDA (COMPILER::X)
      (COMMON-LISP::SETF
          (COMMON-LISP::GET COMPILER::X 'COMPILER::PROCLAIMED-CLOSURE)
          COMMON-LISP::T))
    '(SYSTEM::SI-FIND-CLASS SYSTEM::WARNINGP SYSTEM::SI-CLASS-OF
         SYSTEM::CONDITION-CLASS-P SYSTEM::UNTRACE-ONE
         SYSTEM::MAKE-ACCESS-FUNCTION SYSTEM::SIMPLE-CONDITION-CLASS-P
         SYSTEM::CONDITIONP SYSTEM::AUTOLOAD
         SYSTEM::SI-CLASS-PRECEDENCE-LIST SYSTEM::SI-CLASSP
         FPE::BREAK-ON-FLOATING-POINT-EXCEPTIONS SYSTEM::TRACE-ONE
         SYSTEM::AUTOLOAD-MACRO SYSTEM::DEFINE-STRUCTURE
         SYSTEM::SI-CLASS-NAME)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T) COMMON-LISP::*)
         SYSTEM::INSTREAM-NAME ANSI-LOOP::LOOP-LIST-STEP
         COMMON-LISP::PRIN1-TO-STRING ANSI-LOOP::NAMED-VARIABLE
         SYSTEM::WAITING SYSTEM::FIND-DECLARATIONS COMMON-LISP::INSPECT
         SYSTEM::END-WAITING SYSTEM::BREAK-GO SYSTEM::INFO-SUBFILE
         COMMON-LISP::INVOKE-RESTART-INTERACTIVELY
         ANSI-LOOP::LOOP-OPTIMIZATION-QUANTITIES SYSTEM::INSPECT-OBJECT
         SYSTEM::BREAK-LEVEL-INVOKE-RESTART SYSTEM::EXPAND-RANGES
         SYSTEM::GET-&ENVIRONMENT COMMON-LISP::DESCRIBE
         COMMON-LISP::PRINC-TO-STRING)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::*) COMMON-LISP::T)
         COMMON-LISP::ABORT ANSI-LOOP::MAKE-STANDARD-LOOP-UNIVERSE
         SYSTEM::MAKE-S-DATA ANSI-LOOP::MAKE-LOOP-MINIMAX-INTERNAL
         ANSI-LOOP::MAKE-LOOP-PATH SYSTEM::CURRENT-STEP-FUN SYSTEM::LOC
         SYSTEM::DBL-READ SYSTEM::MAKE-RESTART
         SYSTEM::TRANSFORM-KEYWORDS COMMON-LISP::Y-OR-N-P
         SYSTEM::NEXT-MATCH COMMON-LISP::COMPUTE-RESTARTS
         SLOOP::PARSE-LOOP-WITH COMMON-LISP::VECTOR SYSTEM::STEP-NEXT
         ANSI-LOOP::MAKE-LOOP-COLLECTOR
         COMMON-LISP::USER-HOMEDIR-PATHNAME SLOOP::PARSE-LOOP-DECLARE
         COMMON-LISP::YES-OR-NO-P SYSTEM::STEP-INTO
         SYSTEM::MAKE-CONTEXT SYSTEM::BREAK-LOCALS
         SYSTEM::DESCRIBE-ENVIRONMENT COMMON-LISP::DRIBBLE
         ANSI-LOOP::LOOP-DISALLOW-CONDITIONAL SYSTEM::MAYBE-CLEAR-INPUT
         COMMON-LISP::BREAK ANSI-LOOP::LOOP-GENTEMP
         ANSI-LOOP::MAKE-LOOP-UNIVERSE SYSTEM::MAKE-INSTREAM
         COMMON-LISP::MAKE-PATHNAME)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             ((COMMON-LISP::INTEGER -9223372036854775808
                  9223372036854775807))
             COMMON-LISP::FIXNUM)
         FPE::FE-ENABLE SYSTEM::DBL-WHAT-FRAME)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             ((COMMON-LISP::INTEGER -9223372036854775808
                  9223372036854775807)
              (COMMON-LISP::INTEGER -9223372036854775808
                  9223372036854775807))
             COMMON-LISP::FIXNUM)
         SYSTEM::ROUND-UP)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             ((COMMON-LISP::VECTOR COMMON-LISP::CHARACTER
                  COMMON-LISP::*)
              (COMMON-LISP::INTEGER -9223372036854775808
                  9223372036854775807))
             COMMON-LISP::FIXNUM)
         SYSTEM::ATOI)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T) COMMON-LISP::T)
         SYSTEM::REGEXP-CONV SYSTEM::DIR-CONJ SYSTEM::DIR-P
         ANSI-LOOP::LOOP-LIST-COLLECTION COMMON-LISP::COSH
         SYSTEM::GET-BYTE-STREAM-NCHARS SYSTEM::INSPECT-CONS
         SYSTEM::KNOWN-TYPE-P SYSTEM::LNP COMMON-LISP::SEVENTH
         SYSTEM::BKPT-FUNCTION SYSTEM::WILD-DIR-ELEMENT-P
         COMMON-LISP::COMPILER-MACRO-FUNCTION
         ANSI-LOOP::LOOP-HACK-ITERATION
         COMMON-LISP::ECHO-STREAM-OUTPUT-STREAM
         SYSTEM::DIRECTORY-LIST-CHECK COMMON-LISP::FILE-WRITE-DATE
         SYSTEM::NORMALIZE-TYPE COMMON-LISP::EIGHTH SYSTEM::TOGGLE-CASE
         SYSTEM::SHOW-ENVIRONMENT
         COMMON-LISP::TWO-WAY-STREAM-INPUT-STREAM SYSTEM::GET-PATH
         COMMON-LISP::ASINH SYSTEM::FIND-KCL-TOP-RESTART
         SYSTEM::RESTART-P SYSTEM::EVAL-FEATURE SYSTEM::ALOAD
         COMMON-LISP::PHASE SLOOP::SUBSTITUTE-SLOOP-BODY
         COMMON-LISP::ASIN SYSTEM::NODES-FROM-INDEX
         SYSTEM::MAKE-DEFPACKAGE-FORM ANSI-LOOP::LOOP-COLLECTOR-DTYPE
         SYSTEM::LOGICAL-PATHNAMEP SYSTEM::INSPECT-VECTOR
         ANSI-LOOP::LOOP-UNIVERSE-TYPE-KEYWORDS
         SYSTEM::RESTART-REPORT-FUNCTION SYSTEM::IHS-VISIBLE
         SLOOP::LOOP-COLLECT-KEYWORD-P ANSI-LOOP::LOOP-TYPED-INIT
         COMMON-LISP::VECTOR-POP SYSTEM::UNIQUE-ID
         ANSI-LOOP::LOOP-UNIVERSE-ITERATION-KEYWORDS
         SYSTEM::SIMPLE-ARRAY-P COMMON-LISP::ACOS SYSTEM::DBL-EVAL
         SYSTEM::INSPECT-STRING SYSTEM::MLP
         SYSTEM::INSTREAM-STREAM-NAME SYSTEM::WILD-NAMESTRING-P
         ANSI-LOOP::LOOP-PATH-FUNCTION
         SYSTEM::GET-STRING-INPUT-STREAM-INDEX
         ANSI-LOOP::LOOP-MINIMAX-TEMP-VARIABLE SYSTEM::SEQTYPE
         ANSI-LOOP::LOOP-UNIVERSE-KEYWORDS
         SYSTEM::BEST-ARRAY-ELEMENT-TYPE
         ANSI-LOOP::LOOP-MINIMAX-INFINITY-DATA SYSTEM::S-DATA-FROZEN
         SYSTEM::S-DATA-DOCUMENTATION SYSTEM::DWIM COMMON-LISP::SIGNUM
         SYSTEM::FIND-DOCUMENTATION ANSI-LOOP::LOOP-COLLECTOR-HISTORY
         ANSI-LOOP::LOOP-MAKE-PSETQ FPE::GREF SYSTEM::S-DATA-OFFSET
         SYSTEM::WILD-PATH-ELEMENT-P SYSTEM::INSTREAM-P
         COMMON-LISP::DIRECTORY-NAMESTRING SYSTEM::INSPECT-ARRAY
         COMMON-LISP::ARRAY-DIMENSIONS
         ANSI-LOOP::LOOP-COLLECTOR-TEMPVARS ANSI-LOOP::LOOP-MINIMAX-P
         SLOOP::RETURN-SLOOP-MACRO SYSTEM::WALK-THROUGH
         SYSTEM::NEXT-STACK-FRAME SYSTEM::S-DATA-NAME COMMON-LISP::TANH
         SYSTEM::BREAK-BACKWARD-SEARCH-STACK COMMON-LISP::TENTH
         SYSTEM::INFO-NODE-FROM-POSITION FPE::ST-LOOKUP
         COMMON-LISP::RESTART-NAME SYSTEM::S-DATA-TYPE
         SYSTEM::BKPT-FILE-LINE COMMON-LISP::FIND-ALL-SYMBOLS
         COMMON-LISP::FIFTH SLOOP::LOOP-LET-BINDINGS
         COMMON-LISP::ECHO-STREAM-INPUT-STREAM
         ANSI-LOOP::LOOP-UNIVERSE-IMPLICIT-FOR-REQUIRED
         COMMON-LISP::PROBE-FILE SYSTEM::MAKE-FRAME
         SYSTEM::IHS-NOT-INTERPRETED-ENV SYSTEM::SEARCH-STACK
         COMMON-LISP::COMPILE-FILE-PATHNAME
         SYSTEM::PRINT-SYMBOL-APROPOS COMMON-LISP::LOGNOT
         SYSTEM::INFO-GET-TAGS SYSTEM::SHORT-NAME
         ANSI-LOOP::LOOP-MINIMAX-TYPE COMMON-LISP::SIXTH
         COMMON-LISP::SECOND ANSI-LOOP::LOOP-UNIVERSE-TYPE-SYMBOLS
         COMMON-LISP::TWO-WAY-STREAM-OUTPUT-STREAM
         SYSTEM::S-DATA-INCLUDES SYSTEM::RESTART-INTERACTIVE-FUNCTION
         SLOOP::TRANSLATE-NAME SYSTEM::PATCH-SHARP COMMON-LISP::ABS
         ANSI-LOOP::LOOP-CONSTANTP SYSTEM::LEAP-YEAR-P
         ANSI-LOOP::LOOP-UNIVERSE-ANSI ANSI-LOOP::LOOP-EMIT-BODY
         COMMON-LISP::HOST-NAMESTRING COMMON-LISP::FIRST
         SYSTEM::INSERT-BREAK-POINT
         COMMON-LISP::LOAD-LOGICAL-PATHNAME-TRANSLATIONS
         COMMON-LISP::DELETE-FILE ANSI-LOOP::LOOP-PSEUDO-BODY
         SYSTEM::GET-NEXT-VISIBLE-FUN SYSTEM::S-DATA-HAS-HOLES
         ANSI-LOOP::LOOP-COLLECTOR-NAME COMMON-LISP::FOURTH
         SYSTEM::BKPT-FILE SYSTEM::CANONICALIZE-PATHNAME-DIRECTORY
         SYSTEM::INSTREAM-STREAM SYSTEM::PNL1 SYSTEM::IHS-FNAME
         SYSTEM::S-DATA-SLOT-POSITION SLOOP::PARSE-LOOP
         SYSTEM::CHECK-TRACE-SPEC SYSTEM::S-DATA-CONSTRUCTORS
         SYSTEM::S-DATA-STATICP SYSTEM::CONTEXT-P
         COMMON-LISP::LOGICAL-PATHNAME-TRANSLATIONS
         SYSTEM::INFO-GET-FILE COMMON-LISP::COMPLEMENT
         SYSTEM::INSPECT-NUMBER SYSTEM::RESET-TRACE-DECLARATIONS
         ANSI-LOOP::LOOP-PATH-P SLOOP::REPEAT-SLOOP-MACRO SYSTEM::DO-F
         SYSTEM::INSPECT-PACKAGE SYSTEM::PATH-STREAM-NAME
         SYSTEM::GET-INSTREAM COMMON-LISP::BYTE-SIZE
         SYSTEM::RESTART-FUNCTION FPE::LOOKUP SYSTEM::S-DATA-CONC-NAME
         COMMON-LISP::PROVIDE SYSTEM::S-DATA-NAMED SYSTEM::PRINT-FRS
         ANSI-LOOP::LOOP-MINIMAX-ANSWER-VARIABLE SYSTEM::NODE-OFFSET
         ANSI-LOOP::MAKE-ANSI-LOOP-UNIVERSE SYSTEM::PRINT-IHS
         ANSI-LOOP::LOOP-UNIVERSE-PATH-KEYWORDS COMMON-LISP::TRUENAME
         SYSTEM::BREAK-FORWARD-SEARCH-STACK
         COMMON-LISP::CONCATENATED-STREAM-STREAMS SYSTEM::VERSION-PARSE
         SYSTEM::INSPECT-CHARACTER SYSTEM::LOGICAL-PATHNAME-HOST-P
         SYSTEM::DM-BAD-KEY SYSTEM::EXPAND-HOME-DIR
         ANSI-LOOP::LOOP-PATH-USER-DATA
         ANSI-LOOP::LOOP-PATH-PREPOSITION-GROUPS SYSTEM::INSPECT-SYMBOL
         COMMON-LISP::INVOKE-DEBUGGER
         SYSTEM::LOGICAL-PATHNAME-DESIGNATOR-P
         COMMON-LISP::BYTE-POSITION COMMON-LISP::ISQRT COMMON-LISP::CIS
         ANSI-LOOP::LOOP-COLLECTOR-CLASS
         COMMON-LISP::SYNONYM-STREAM-SYMBOL ANSI-LOOP::LOOP-PATH-NAMES
         SYSTEM::RE-QUOTE-STRING SYSTEM::INSPECT-STRUCTURE
         COMMON-LISP::RATIONAL FPE::XMM-LOOKUP
         SYSTEM::REWRITE-RESTART-CASE-CLAUSE
         SYSTEM::S-DATA-PRINT-FUNCTION
         SYSTEM::RESTRICT-STREAM-ELEMENT-TYPE SLOOP::SLOOP-SLOOP-MACRO
         COMMON-LISP::NAMESTRING SYSTEM::ENSURE-DIR-STRING
         COMMON-LISP::CONSTANTLY SLOOP::PARSE-LOOP-INITIALLY
         SYSTEM::S-DATA-RAW SYSTEM::ADD-TO-HOTLIST SYSTEM::FRS-KIND
         ANSI-LOOP::LOOP-MAXMIN-COLLECTION
         ANSI-LOOP::LOOP-COLLECTOR-DATA SYSTEM::PROCESS-ARGS
         SYSTEM::COERCE-SLASH-TERMINATED SYSTEM::MAKE-KCL-TOP-RESTART
         COMMON-LISP::ATANH ANSI-LOOP::LOOP-CODE-DUPLICATION-THRESHOLD
         COMMON-LISP::SINH ANSI-LOOP::LOOP-UNIVERSE-P
         ANSI-LOOP::LOOP-PATH-INCLUSIVE-PERMITTED
         SYSTEM::S-DATA-INCLUDED COMMON-LISP::STREAM-EXTERNAL-FORMAT
         SYSTEM::COMPUTING-ARGS-P SYSTEM::REAL-ASINH
         ANSI-LOOP::LOOP-CONSTRUCT-RETURN
         SYSTEM::S-DATA-SLOT-DESCRIPTIONS SYSTEM::FIX-LOAD-PATH
         SYSTEM::CHECK-DECLARATIONS
         ANSI-LOOP::LOOP-UNIVERSE-FOR-KEYWORDS
         SLOOP::POINTER-FOR-COLLECT COMMON-LISP::LOGICAL-PATHNAME
         SYSTEM::CHDIR SYSTEM::IDESCRIBE
         ANSI-LOOP::LOOP-MINIMAX-OPERATIONS COMMON-LISP::ACOSH
         COMMON-LISP::NINTH ANSI-LOOP::LOOP-MINIMAX-FLAG-VARIABLE
         ANSI-LOOP::LOOP-COLLECTOR-P SYSTEM::S-DATA-P SYSTEM::BKPT-FORM
         COMMON-LISP::FILE-NAMESTRING SYSTEM::TERMINAL-INTERRUPT
         SYSTEM::SETUP-INFO SLOOP::PARSE-NO-BODY
         SYSTEM::DM-KEY-NOT-ALLOWED ANSI-LOOP::LOOP-EMIT-FINAL-VALUE
         SYSTEM::FREEZE-DEFSTRUCT SYSTEM::DBL-RPL-LOOP
         SYSTEM::TRACE-ONE-PREPROCESS
         COMMON-LISP::BROADCAST-STREAM-STREAMS COMMON-LISP::THIRD
         SLOOP::AVERAGING-SLOOP-MACRO SYSTEM::SHOW-BREAK-POINT
         COMMON-LISP::PATHNAME ANSI-LOOP::LOOP-DO-THEREIS
         COMMON-LISP::FILE-AUTHOR ANSI-LOOP::LOOP-MAKE-DESETQ
         SYSTEM::NC SYSTEM::NUMBER-OF-DAYS-FROM-1900
         SYSTEM::RESTART-TEST-FUNCTION SYSTEM::WHICH
         ANSI-LOOP::DESTRUCTURING-SIZE COMMON-LISP::FILE-LENGTH)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::*) COMMON-LISP::*)
         SYSTEM::BREAK-VS ANSI-LOOP::LOOP-OPTIONAL-TYPE
         SYSTEM::BREAK-BDS SYSTEM::IHS-BACKTRACE SYSTEM::INFO-ERROR
         SYSTEM::BREAK-LOCAL SYSTEM::SHOW-BREAK-VARIABLES
         COMMON-LISP::MUFFLE-WARNING SYSTEM::BREAK-PREVIOUS
         SYSTEM::BREAK-QUIT SYSTEM::DBL-BACKTRACE COMMON-LISP::CONTINUE
         SYSTEM::BREAK-NEXT)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T)
             (COMMON-LISP::VALUES COMMON-LISP::T COMMON-LISP::T))
         SYSTEM::MAKE-KEYWORD)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T
                 (COMMON-LISP::INTEGER -9223372036854775808
                     9223372036854775807)
                 (COMMON-LISP::INTEGER -9223372036854775808
                     9223372036854775807)
                 COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::T)
         SYSTEM::QUICK-SORT)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T
                 (COMMON-LISP::INTEGER -9223372036854775808
                     9223372036854775807)
                 COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::T)
         SYSTEM::BIGNTHCDR)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T COMMON-LISP::*)
             COMMON-LISP::T)
         COMMON-LISP::FIND-RESTART COMMON-LISP::PATHNAME-HOST
         SYSTEM::LINK-EXPAND COMMON-LISP::CONCATENATE COMMON-LISP::WARN
         COMMON-LISP::FILE-POSITION ANSI-LOOP::LOOP-WARN
         COMMON-LISP::PATHNAME-DIRECTORY COMMON-LISP::SBIT
         COMMON-LISP::BIT ANSI-LOOP::LOOP-COLLECT-PREPOSITIONAL-PHRASES
         COMMON-LISP::PATHNAME-TYPE COMMON-LISP::MAKE-ARRAY
         ANSI-LOOP::LOOP-ERROR COMMON-LISP::DIRECTORY SYSTEM::DIR-PARSE
         COMMON-LISP::TRANSLATE-LOGICAL-PATHNAME
         SYSTEM::NTH-STACK-FRAME COMMON-LISP::REQUIRE COMMON-LISP::LOAD
         SYSTEM::MGLIST COMMON-LISP::DELETE-DUPLICATES
         COMMON-LISP::PATHNAME-VERSION COMMON-LISP::ENOUGH-NAMESTRING
         SYSTEM::BAD-SEQ-LIMIT COMMON-LISP::REMOVE-DUPLICATES
         COMMON-LISP::PATHNAME-NAME
         COMMON-LISP::MAKE-STRING-INPUT-STREAM SLOOP::LOOP-ADD-TEMPS
         SYSTEM::NLOAD SYSTEM::LIST-MATCHES
         COMMON-LISP::ARRAY-ROW-MAJOR-INDEX
         COMMON-LISP::ARRAY-IN-BOUNDS-P SYSTEM::BREAK-LEVEL
         SYSTEM::PROCESS-SOME-ARGS SYSTEM::TO-REGEXP
         COMMON-LISP::UPGRADED-ARRAY-ELEMENT-TYPE COMMON-LISP::OPEN
         SYSTEM::FILE-SEARCH COMMON-LISP::READ-BYTE
         SYSTEM::FILE-TO-STRING SLOOP::ADD-FROM-DATA COMMON-LISP::ERROR
         COMMON-LISP::SIGNAL SYSTEM::MGSUB COMMON-LISP::WILD-PATHNAME-P
         COMMON-LISP::PATHNAME-DEVICE SYSTEM::LOGICAL-PATHNAME-PARSE
         COMMON-LISP::MERGE-PATHNAMES SYSTEM::INFO-SEARCH
         COMMON-LISP::BIT-NOT)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::*)
         ANSI-LOOP::ESTIMATE-CODE-SIZE-1 SYSTEM::DO-REPL
         SYSTEM::SOURCE-PORTION SYSTEM::RESTART-REPORT
         SYSTEM::NEW-SEMI-COLON-READER SYSTEM::FIND-DOC
         ANSI-LOOP::ESTIMATE-CODE-SIZE SYSTEM::NEWLINE
         COMMON-LISP::RENAME-FILE SYSTEM::LIST-TOGGLE-CASE)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::*)
             COMMON-LISP::*)
         COMMON-LISP::REDUCE COMMON-LISP::STABLE-SORT
         SYSTEM::PARSE-BODY SLOOP::FIND-IN-ORDERED-LIST
         COMMON-LISP::SUBTYPEP COMMON-LISP::SORT)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::*)
         SYSTEM::LIST-MERGE-SORT ANSI-LOOP::LOOP-GET-COLLECTION-INFO
         SYSTEM::SHARP---READER SYSTEM::SHARP-S-READER
         SYSTEM::VERIFY-KEYWORDS SYSTEM::RESTART-PRINT
         SYSTEM::SHARP-+-READER SYSTEM::READ-INSPECT-COMMAND)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::*)
         SYSTEM::PUSH-OPTIONAL-BINDING)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T)
             COMMON-LISP::*)
         SYSTEM::TRACE-CALL)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::*)
             COMMON-LISP::*)
         SYSTEM::MASET)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::*)
             COMMON-LISP::*)
         SYSTEM::EXPAND-WILD-DIRECTORY)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T COMMON-LISP::T COMMON-LISP::*)
             COMMON-LISP::*)
         SYSTEM::PARSE-DEFMACRO SYSTEM::PARSE-DEFMACRO-LAMBDA-LIST)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T)
             COMMON-LISP::*)
         SYSTEM::MME3)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             ((COMMON-LISP::INTEGER -9223372036854775808
                  9223372036854775807)
              COMMON-LISP::T)
             COMMON-LISP::T)
         SYSTEM::SMALLNTHCDR)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION COMMON-LISP::NIL COMMON-LISP::*)
         SYSTEM::GCL-TOP-LEVEL SYSTEM::BREAK-MESSAGE
         SYSTEM::BREAK-RESUME SYSTEM::SIMPLE-BACKTRACE
         SYSTEM::BREAK-HELP ANSI-LOOP::LOOP-DO-FOR
         SYSTEM::BREAK-CURRENT)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T) COMMON-LISP::FIXNUM)
         SYSTEM::S-DATA-LENGTH SYSTEM::THE-START SYSTEM::INSTREAM-LINE
         SYSTEM::S-DATA-SIZE FPE::REG-LOOKUP)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::FIXNUM) COMMON-LISP::T)
         SYSTEM::MATCH-BEGINNING SYSTEM::MATCH-END)) 