
(IN-PACKAGE "SYSTEM") 
(PROCLAIM '(FTYPE (FUNCTION (T FIXNUM T T) T) BIGNTHCDR)) 
(PROCLAIM '(FTYPE (FUNCTION (T FIXNUM FIXNUM T T) T) QUICK-SORT)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T *) T) ARRAY-IN-BOUNDS-P READ-BYTE
            PROCESS-SOME-ARGS FILE-SEARCH REMOVE-DUPLICATES
            ANSI-LOOP::LOOP-COLLECT-PREPOSITIONAL-PHRASES MAKE-ARRAY
            BIT-NOT FILE-TO-STRING LIST-MATCHES CONCATENATE
            SLOOP::ADD-FROM-DATA UPGRADED-ARRAY-ELEMENT-TYPE
            INFO-SEARCH NTH-STACK-FRAME SLOOP::LOOP-ADD-TEMPS SBIT
            DELETE-DUPLICATES ANSI-LOOP::LOOP-ERROR
            ARRAY-ROW-MAJOR-INDEX BAD-SEQ-LIMIT ANSI-LOOP::LOOP-WARN
            BIT)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) *) NEWLINE ANSI-LOOP::ESTIMATE-CODE-SIZE-1
            FIND-DOC NEW-SEMI-COLON-READER
            ANSI-LOOP::ESTIMATE-CODE-SIZE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) FIXNUM) INSTREAM-LINE S-DATA-LENGTH THE-START
            S-DATA-SIZE FPE::REG-LOOKUP)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM) T) GET-CONTEXT PUSH-CONTEXT)) 
(PROCLAIM
    '(FTYPE (FUNCTION NIL *) BREAK-HELP BREAK-MESSAGE
            ANSI-LOOP::LOOP-DO-FOR SIMPLE-BACKTRACE BREAK-CURRENT
            GCL-TOP-LEVEL)) 
(MAPC (LAMBDA (COMPILER::X)
        (SETF (GET COMPILER::X 'PROCLAIMED-CLOSURE) T))
      '(SI-CLASS-OF SI-CLASSP DEFINE-STRUCTURE AUTOLOAD SI-FIND-CLASS
           TRACE-ONE SI-CLASS-PRECEDENCE-LIST
           BREAK-ON-FLOATING-POINT-EXCEPTIONS MAKE-ACCESS-FUNCTION
           SI-CLASS-NAME AUTOLOAD-MACRO UNTRACE-ONE)) 
(PROCLAIM
    '(FTYPE (FUNCTION NIL T) ANSI-LOOP::LOOP-GET-PROGN
            ANSI-LOOP::LOOP-DO-REPEAT ANSI-LOOP::LOOP-DO-FINALLY
            ANSI-LOOP::LOOP-ITERATION-DRIVER SLOOP::PARSE-LOOP-WHEN
            SETUP-LINEINFO ANSI-LOOP::LOOP-CONTEXT DM-TOO-FEW-ARGUMENTS
            TYPE-ERROR ANSI-LOOP::LOOP-BIND-BLOCK DEFAULT-INFO-HOTLIST
            SLOOP::PARSE-LOOP-DO GET-INDEX-NODE
            SLOOP::PARSE-ONE-WHEN-CLAUSE GET-TEMP-DIR
            ALL-TRACE-DECLARATIONS SLOOP::PARSE-LOOP-FOR
            INIT-BREAK-POINTS SET-CURRENT READ-EVALUATED-FORM
            STEP-READ-LINE DM-TOO-MANY-ARGUMENTS SET-ENV TEST-ERROR
            SET-UP-TOP-LEVEL SLOOP::LOOP-PEEK ANSI-LOOP::LOOP-DO-DO
            SLOOP::PARSE-LOOP1 INSPECT-INDENT-1 ANSI-LOOP::LOOP-DO-WITH
            ANSI-LOOP::LOOP-DO-NAMED SLOOP::LOOP-POP SLOOP::LOOP-UN-POP
            ANSI-LOOP::LOOP-WHEN-IT-VARIABLE INSPECT-READ-LINE DBL
            TOP-LEVEL ANSI-LOOP::LOOP-GET-FORM
            LISP-IMPLEMENTATION-VERSION WINE-TMP-REDIRECT
            ANSI-LOOP::LOOP-POP-SOURCE CLEANUP INSPECT-INDENT
            ILLEGAL-BOA DEFAULT-SYSTEM-BANNER SLOOP::PARSE-LOOP-COLLECT
            ANSI-LOOP::LOOP-DO-INITIALLY ANSI-LOOP::LOOP-DO-RETURN)) 
(PROCLAIM
    '(FTYPE (FUNCTION (STRING) T) COERCE-SLASH-TERMINATED
            RESET-SYS-PATHS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) T) DM-NTH LOGANDC1 INCREMENT-CURSOR
            SLOOP::LOGXOR-SLOOP-COLLECT INFO-AUX SLOOP::L-EQUAL
            ANSI-LOOP::LOOP-DO-ALWAYS SLOOP::MINIMIZE-SLOOP-COLLECT
            SLOOP::MAXIMIZE-SLOOP-COLLECT ITERATE-OVER-BKPTS
            DISPLAY-ENV GET-LINE-OF-FORM BREAK-STEP-INTO FPE::RF
            LOGORC2 DOCUMENTATION ANSI-LOOP::LOOP-DO-WHILE NTHCDR
            SLOOP::=-SLOOP-FOR SLOOP::IN-PACKAGE-SLOOP-MAP
            ANSI-LOOP::MAKE-LOOP-MINIMAX SUPER-GO
            LISP::KEYWORD-SUPPLIED-P
            ANSI-LOOP::LOOP-NOTE-MINIMAX-OPERATION GET-INFO-CHOICES
            PARSE-SLOT-DESCRIPTION DM-V SLOOP::COUNT-SLOOP-COLLECT
            OBJLT ANSI-LOOP::LOOP-LOOKUP-KEYWORD
            ANSI-LOOP::HIDE-VARIABLE-REFERENCES SET-BACK
            COMPILER::COMPILER-DEF-HOOK DBL-UP
            SLOOP::NEVER-SLOOP-COLLECT SLOOP::THEREIS-SLOOP-COLLECT
            GET-NODES SLOOP::THE-TYPE LISP::LOOKUP-KEYWORD
            FPE::PAREN-READER LOGANDC2 *BREAK-POINTS* LDB-TEST BYTE
            ANSI-LOOP::LOOP-MAYBE-BIND-FORM SUB-INTERVAL-P GET-MATCH
            LOGNAND SUBSTRINGP SET-DIR ANSI-LOOP::LOOP-TMEMBER LOGNOR
            SLOOP::IN-FRINGE-SLOOP-MAP FPE::READ-OPERANDS
            ANSI-LOOP::LOOP-DO-IF DM-NTH-CDR LOGTEST
            OVERWRITE-SLOT-DESCRIPTIONS LOGORC1 CHECK-SEQ-START-END LDB
            QUOTATION-READER NTH IN-INTERVAL-P SLOOP::SUM-SLOOP-COLLECT
            FPE::%-READER LIST-DELQ READ-INSTRUCTION
            SLOOP::PARSE-LOOP-MAP SLOOP::DESETQ1 MATCH-DIMENSIONS
            FPE::0-READER SEQUENCE-CURSOR VECTOR-PUSH
            SLOOP::ALWAYS-SLOOP-COLLECT COERCE SLOOP::MAKE-VALUE
            ADD-FILE SAFE-EVAL SLOOP::IN-CAREFULLY-SLOOP-FOR
            SETF-HELPER ANSI-LOOP::LOOP-DECLARE-VARIABLE
            ANSI-LOOP::LOOP-TASSOC WRITE-BYTE LEFT-PARENTHESIS-READER
            DISPLAY-COMPILED-ENV SETF-EXPAND BREAK-STEP-NEXT
            ANSI-LOOP::LOOP-TEQUAL ALL-MATCHES
            SLOOP::COLLATE-SLOOP-COLLECT SLOOP::IN-TABLE-SLOOP-MAP)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T *) *) STEPPER FTRUNCATE
            GET-SETF-METHOD-MULTIPLE-VALUE INFO
            ENSURE-DIRECTORIES-EXIST NLOAD PRINT-DOC
            ANSI-LOOP::LOOP-CONSTANT-FOLD-IF-POSSIBLE
            DECODE-UNIVERSAL-TIME REQUIRE APROPOS WILD-PATHNAME-P
            FROUND PARSE-BODY-HEADER APROPOS-DOC BREAK-FUNCTION FFLOOR
            APROPOS-LIST READ-FROM-STRING FCEILING GET-SETF-METHOD
            SHOW-INFO WRITE-TO-STRING)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T) T) ANSI-LOOP::LOOP-STANDARD-EXPANSION
            APPLY-DISPLAY-FUN FLOATING-POINT-ERROR SHARP-A-READER
            DEFMACRO* FPE::REF SETF-EXPAND-1
            ANSI-LOOP::LOOP-SUM-COLLECTION SHARP-U-READER
            ANSI-LOOP::LOOP-ANSI-FOR-EQUALS ANSI-LOOP::LOOP-FOR-BEING
            MAKE-T-TYPE ANSI-LOOP::PRINT-LOOP-UNIVERSE DPB DM-VL
            ANSI-LOOP::HIDE-VARIABLE-REFERENCE
            ANSI-LOOP::LOOP-MAKE-ITERATION-VARIABLE GET-SLOT-POS
            CHECK-TRACE-ARGS ANSI-LOOP::LOOP-FOR-IN DEPOSIT-FIELD
            CHECK-S-DATA ANSI-LOOP::LOOP-FOR-ON MAKE-BREAK-POINT
            WARN-VERSION SLOOP::LOOP-PARSE-ADDITIONAL-COLLECTIONS
            ANSI-LOOP::LOOP-TRANSLATE ANSI-LOOP::LOOP-FOR-ACROSS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T *) T) NINTERSECTION POSITION FIND-IF
            WRITE-SEQUENCE DELETE MAKE-SEQUENCE NUNION MISMATCH SOME
            VECTOR-PUSH-EXTEND DELETE-IF-NOT REMOVE
            SLOOP::PARSE-LOOP-MACRO COUNT FIND-IF-NOT COUNT-IF-NOT
            BIT-ORC2 BIT-EQV SET-EXCLUSIVE-OR INTERNAL-COUNT BREAK-CALL
            NSET-DIFFERENCE FIND EVERY READ-SEQUENCE REPLACE FILL
            SEARCH INTERSECTION BIT-ANDC1 POSITION-IF DELETE-IF TYPEP
            UNION NSET-EXCLUSIVE-OR SLOOP::LOOP-ADD-BINDING NOTANY
            MAP-INTO INTERNAL-COUNT-IF POSITION-IF-NOT NOTEVERY
            BIT-NAND SLOOP::IN-ARRAY-SLOOP-FOR REMOVE-IF-NOT COUNT-IF
            BIT-XOR BIT-ORC1 ANSI-LOOP::LOOP-CHECK-DATA-TYPE BIT-NOR
            REMOVE-IF SET-DIFFERENCE INTERNAL-COUNT-IF-NOT SUBSETP
            BIT-AND BIT-ANDC2 ADJUST-ARRAY BIT-IOR)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T) T) MAKE-PREDICATE MAKE-CONSTRUCTOR)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T *) T) SLOOP::LOOP-DECLARE-BINDING
            SUBSTITUTE-IF ANSI-LOOP::LOOP-MAKE-VARIABLE
            SUBSTITUTE-IF-NOT COMPLETE-PROP
            ANSI-LOOP::LOOP-SEQUENCE-ELEMENTS-PATH MAP SUBSTITUTE
            NSUBSTITUTE-IF CHECK-TYPE-SYMBOL ANSI-LOOP::ADD-LOOP-PATH
            NSUBSTITUTE-IF-NOT LISP::PUSH-LET-BINDING
            ANSI-LOOP::LOOP-HASH-TABLE-ITERATION-PATH
            ANSI-LOOP::LOOP-PACKAGE-SYMBOLS-ITERATION-PATH NSUBSTITUTE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T) T) SLOOP::FIRST-USE-SLOOP-FOR
            MAYBE-BREAK CALL-TEST SLOOP::FIRST-SLOOP-FOR
            SETF-STRUCTURE-ACCESS ANSI-LOOP::LOOP-FOR-ARITHMETIC
            FIND-LINE-IN-FUN)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T *) T) PRINT-STACK-FRAME
            SLOOP::DEF-LOOP-INTERNAL MERGE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T T T T) T)
            ANSI-LOOP::LOOP-SEQUENCER)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T) T) LISP::DO-ARG-COUNT-ERROR
            LISP::PUSH-SUB-LIST-BINDING)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T FIXNUM) T) SHARP-EQ-READER
            SHARP-SHARP-READER)) 
(PROCLAIM '(FTYPE (FUNCTION (T T T T T T *) T) ENCODE-UNIVERSAL-TIME)) 
(PROCLAIM '(FTYPE (FUNCTION (STRING FIXNUM) FIXNUM) ATOI)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) T) GET-BYTE-STREAM-NCHARS
            ANSI-LOOP::LOOP-MINIMAX-INFINITY-DATA
            BREAK-BACKWARD-SEARCH-STACK
            ANSI-LOOP::LOOP-UNIVERSE-TYPE-SYMBOLS THIRD BKPT-FILE-LINE
            ANSI-LOOP::DESTRUCTURING-SIZE
            ANSI-LOOP::LOOP-COLLECTOR-TEMPVARS
            ANSI-LOOP::LOOP-COLLECTOR-CLASS INFO-GET-FILE
            ANSI-LOOP::LOOP-MINIMAX-OPERATIONS BYTE-POSITION
            TRACE-ONE-PREPROCESS INSTREAM-P SLOOP::REPEAT-SLOOP-MACRO
            ANSI-LOOP::LOOP-UNIVERSE-P GET-INSTREAM INSPECT-STRUCTURE
            BYTE-SIZE WALK-THROUGH RE-QUOTE-STRING SHORT-NAME
            ANSI-LOOP::LOOP-MINIMAX-ANSWER-VARIABLE PROVIDE DO-F
            ANSI-LOOP::LOOP-COLLECTOR-NAME S-DATA-SLOT-DESCRIPTIONS
            S-DATA-RAW LOGNOT EVAL-FEATURE SLOOP::RETURN-SLOOP-MACRO
            BREAK-FORWARD-SEARCH-STACK
            ANSI-LOOP::MAKE-ANSI-LOOP-UNIVERSE
            ANSI-LOOP::LOOP-CONSTRUCT-RETURN INSTREAM-STREAM ASINH TANH
            ANSI-LOOP::LOOP-HACK-ITERATION RATIONAL
            SLOOP::TRANSLATE-NAME ANSI-LOOP::LOOP-DO-THEREIS
            S-DATA-CONC-NAME CHECK-DECLARATIONS INSPECT-ARRAY
            ANSI-LOOP::LOOP-PATH-P S-DATA-STATICP COSH NORMALIZE-TYPE
            SETUP-INFO ANSI-LOOP::LOOP-PSEUDO-BODY INSPECT-PACKAGE
            CHECK-TRACE-SPEC FIRST S-DATA-DOCUMENTATION SIXTH
            ANSI-LOOP::LOOP-MAKE-PSETQ FIND-DOCUMENTATION
            ANSI-LOOP::LOOP-UNIVERSE-ANSI SLOOP::SLOOP-SLOOP-MACRO
            S-DATA-SLOT-POSITION FPE::XMM-LOOKUP SECOND
            ANSI-LOOP::LOOP-CONSTANTP IHS-FNAME CONTEXT-P ISQRT FIFTH
            SHOW-BREAK-POINT SLOOP::LOOP-LET-BINDINGS NEXT-STACK-FRAME
            COMPUTING-ARGS-P S-DATA-P SLOOP::PARSE-LOOP-INITIALLY
            COMPILE-FILE-PATHNAME S-DATA-INCLUDED INSPECT-VECTOR
            ANSI-LOOP::LOOP-MINIMAX-FLAG-VARIABLE
            ANSI-LOOP::LOOP-COLLECTOR-P SLOOP::LOOP-COLLECT-KEYWORD-P
            KNOWN-TYPE-P ANSI-LOOP::LOOP-UNIVERSE-PATH-KEYWORDS
            ANSI-LOOP::LOOP-MAXMIN-COLLECTION TENTH COMPLEMENT ASIN
            FPE::ST-LOOKUP NODES-FROM-INDEX VECTOR-POP DM-BAD-KEY
            S-DATA-NAME IDESCRIBE NODE-OFFSET
            ANSI-LOOP::LOOP-PATH-FUNCTION SLOOP::AVERAGING-SLOOP-MACRO
            IHS-NOT-INTERPRETED-ENV ANSI-LOOP::LOOP-UNIVERSE-KEYWORDS
            INFO-GET-TAGS ACOSH IHS-VISIBLE
            ANSI-LOOP::LOOP-UNIVERSE-FOR-KEYWORDS
            RESET-TRACE-DECLARATIONS FPE::GREF
            ANSI-LOOP::LOOP-COLLECTOR-DTYPE BKPT-FILE
            GET-NEXT-VISIBLE-FUN S-DATA-INCLUDES
            ANSI-LOOP::LOOP-COLLECTOR-HISTORY NINTH DM-KEY-NOT-ALLOWED
            SLOOP::PARSE-LOOP ANSI-LOOP::LOOP-PATH-NAMES
            S-DATA-PRINT-FUNCTION ANSI-LOOP::LOOP-COLLECTOR-DATA
            ANSI-LOOP::LOOP-UNIVERSE-ITERATION-KEYWORDS SEVENTH EIGHTH
            PATCH-SHARP ANSI-LOOP::LOOP-MAKE-DESETQ
            ANSI-LOOP::LOOP-UNIVERSE-TYPE-KEYWORDS
            ANSI-LOOP::LOOP-PATH-USER-DATA ACOS SIMPLE-ARRAY-P SEQTYPE
            S-DATA-HAS-HOLES FIX-LOAD-PATH FIND-ALL-SYMBOLS
            S-DATA-NAMED SIGNUM ANSI-LOOP::LOOP-TYPED-INIT
            INSPECT-STRING S-DATA-TYPE SHOW-ENVIRONMENT FOURTH
            INFO-NODE-FROM-POSITION INSTREAM-STREAM-NAME
            ANSI-LOOP::LOOP-PATH-PREPOSITION-GROUPS ABS SEARCH-STACK
            ATANH SINH ANSI-LOOP::LOOP-LIST-COLLECTION PHASE
            INSPECT-CONS SLOOP::PARSE-NO-BODY DWIM INSPECT-SYMBOL
            LEAP-YEAR-P SLOOP::POINTER-FOR-COLLECT ARRAY-DIMENSIONS
            ANSI-LOOP::LOOP-PATH-INCLUSIVE-PERMITTED
            COMPILER-MACRO-FUNCTION ANSI-LOOP::LOOP-EMIT-FINAL-VALUE
            INSPECT-NUMBER FREEZE-DEFSTRUCT
            ANSI-LOOP::LOOP-UNIVERSE-IMPLICIT-FOR-REQUIRED
            ANSI-LOOP::LOOP-CODE-DUPLICATION-THRESHOLD
            ANSI-LOOP::LOOP-MINIMAX-P S-DATA-CONSTRUCTORS
            ADD-TO-HOTLIST CONTEXT-HASH S-DATA-OFFSET CONTEXT-VEC
            TERMINAL-INTERRUPT SLOOP::SUBSTITUTE-SLOOP-BODY PRINT-IHS
            FRS-KIND NUMBER-OF-DAYS-FROM-1900 INSERT-BREAK-POINT CIS
            PRINT-SYMBOL-APROPOS ANSI-LOOP::LOOP-MINIMAX-TYPE
            MAKE-DEFPACKAGE-FORM ANSI-LOOP::LOOP-MINIMAX-TEMP-VARIABLE
            PRINT-FRS BKPT-FORM INSPECT-CHARACTER CONTEXT-SPICE
            CONSTANTLY ANSI-LOOP::LOOP-EMIT-BODY
            BEST-ARRAY-ELEMENT-TYPE S-DATA-FROZEN BKPT-FUNCTION
            FPE::LOOKUP)) 
(PROCLAIM
    '(FTYPE (FUNCTION (*) *) BREAK-QUIT BREAK-NEXT INFO-ERROR BREAK-BDS
            BREAK-LOCAL ANSI-LOOP::LOOP-OPTIONAL-TYPE BREAK-VS
            DBL-BACKTRACE IHS-BACKTRACE BREAK-PREVIOUS
            SHOW-BREAK-VARIABLES)) 
(PROCLAIM
    '(FTYPE (FUNCTION (FIXNUM) FIXNUM) FPE::FE-ENABLE DBL-WHAT-FRAME)) 
(PROCLAIM
    '(FTYPE (FUNCTION (*) T) SLOOP::PARSE-LOOP-DECLARE BREAK-LOCALS
            YES-OR-NO-P ANSI-LOOP::MAKE-LOOP-COLLECTOR
            ANSI-LOOP::MAKE-LOOP-MINIMAX-INTERNAL STEP-NEXT Y-OR-N-P
            SLOOP::PARSE-LOOP-WITH VECTOR ANSI-LOOP::MAKE-LOOP-PATH
            MAKE-INSTREAM MAKE-S-DATA LOC
            ANSI-LOOP::MAKE-STANDARD-LOOP-UNIVERSE DRIBBLE
            ANSI-LOOP::MAKE-LOOP-UNIVERSE MAYBE-CLEAR-INPUT STEP-INTO
            DBL-READ MAKE-CONTEXT DESCRIBE-ENVIRONMENT CURRENT-STEP-FUN
            ANSI-LOOP::LOOP-DISALLOW-CONDITIONAL
            ANSI-LOOP::LOOP-GENTEMP)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) *) INSTREAM-NAME INFO-SUBFILE ALOAD
            FIND-DECLARATIONS WAITING INSPECT ANSI-LOOP::NAMED-VARIABLE
            PRINC-TO-STRING GET-&ENVIRONMENT END-WAITING
            ANSI-LOOP::LOOP-LIST-STEP
            ANSI-LOOP::LOOP-OPTIMIZATION-QUANTITIES INSPECT-OBJECT
            PRIN1-TO-STRING DESCRIBE BREAK-GO)) 
(PROCLAIM '(FTYPE (FUNCTION (T) (VALUES T T)) LISP::MAKE-KEYWORD)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) FIXNUM) ANSI-LOOP::DUPLICATABLE-CODE-P
            THE-END RELATIVE-LINE GET-NODE-INDEX)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM T) T) SMALLNTHCDR)) 
(PROCLAIM '(FTYPE (FUNCTION (FIXNUM FIXNUM) FIXNUM) ROUND-UP)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T) *) LISP::VERIFY-KEYWORDS
            ANSI-LOOP::LOOP-GET-COLLECTION-INFO SHARP---READER
            SHARP-+-READER SHARP-S-READER READ-INSPECT-COMMAND
            LIST-MERGE-SORT)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T *) *) LISP::PARSE-BODY STABLE-SORT
            SLOOP::FIND-IN-ORDERED-LIST REDUCE SUBTYPEP SORT)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T T T T) *) LISP::PUSH-OPTIONAL-BINDING)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T *) *) LISP::PARSE-DEFMACRO
            LISP::PARSE-DEFMACRO-LAMBDA-LIST)) 
(PROCLAIM '(FTYPE (FUNCTION (T T T T T T T) *) TRACE-CALL)) 
(PROCLAIM '(FTYPE (FUNCTION (T T T *) *) MASET)) 