
(IN-PACKAGE "CONDITIONS") 
(PROCLAIM
    '(FTYPE (FUNCTION (T) T) CONDITION-CLASS-P IS-WARNING CONDITIONP
            IS-CONDITION ESCAPE-SPECIAL-CASES-REPLACE
            SIMPLE-CONDITION-CLASS-P INTERNAL-SIMPLE-CONDITION-CLASS-P)) 
(PROCLAIM '(FTYPE (FUNCTION (*) *) CLCS-COMPILE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) T) ASSERT-REPORT SYMCAT COERCE-TO-FN
            SLOT-SYM)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T *) *) CLCS-LOAD CLCS-OPEN CLCS-COMPILE-FILE
            MAKE-CONDITION)) 
(PROCLAIM '(FTYPE (FUNCTION (T) (*)) SIMPLE-ASSERTION-FAILURE)) 
(PROCLAIM '(FTYPE (FUNCTION (T T T) T) ACCUMULATE-CASES)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T) T)
            |(PCL::FAST-METHOD PRINT-OBJECT (CONDITION T))|)) 
(PROCLAIM '(FTYPE (FUNCTION (T T) *) ASSERT-PROMPT)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T) *)
            |(PCL::FAST-METHOD PRINT-OBJECT (INTERNAL-WARNING T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (UNBOUND-SLOT T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (END-OF-FILE T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (FILE-ERROR T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (ARITHMETIC-ERROR T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (SIMPLE-CONDITION T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (ABORT-FAILURE T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (CASE-FAILURE T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (UNDEFINED-FUNCTION T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (PRINT-NOT-READABLE T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (INTERNAL-ERROR T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (PACKAGE-ERROR T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (CELL-ERROR T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (INTERNAL-CONDITION T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (STREAM-ERROR T))|
            COERCE-TO-CONDITION
            |(PCL::FAST-METHOD PRINT-OBJECT (TYPE-ERROR T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (UNBOUND-VARIABLE T))|)) 
(PROCLAIM
    '(FTYPE (FUNCTION NIL T) REVERT-CLCS-SYMBOLS INSTALL-CLCS-SYMBOLS
            READ-EVALUATED-FORM)) 
(MAPC (LAMBDA (COMPILER::X)
        (SETF (GET COMPILER::X 'SYSTEM::PROCLAIMED-CLOSURE) T))
      '(INSTALL-SYMBOL REVERT-SYMBOL)) 