
(COMMON-LISP::IN-PACKAGE "CONDITIONS") 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T COMMON-LISP::T)
             COMMON-LISP::T)
         COMMON-LISP::HANDLER-BIND COMMON-LISP::DEFINE-CONDITION
         COMMON-LISP::HANDLER-CASE COMMON-LISP::IGNORE-ERRORS
         CONDITIONS::COERCE-TO-FN CONDITIONS::SLOT-SYM)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T COMMON-LISP::*)
             COMMON-LISP::*)
         COMMON-LISP::MAKE-CONDITION)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T)
             COMMON-LISP::*)
         CONDITIONS::|(PCL::FAST-METHOD PRINT-OBJECT (TYPE-ERROR T))|
         CONDITIONS::|(PCL::FAST-METHOD PRINT-OBJECT (INTERNAL-CONDITION T))|
         CONDITIONS::|(PCL::FAST-METHOD PRINT-OBJECT (FILE-ERROR T))|
         CONDITIONS::|(PCL::FAST-METHOD PRINT-OBJECT (CASE-FAILURE T))|
         CONDITIONS::|(PCL::FAST-METHOD PRINT-OBJECT (UNBOUND-SLOT T))|
         CONDITIONS::|(PCL::FAST-METHOD PRINT-OBJECT (ABORT-FAILURE T))|
         CONDITIONS::|(PCL::FAST-METHOD PRINT-OBJECT (UNDEFINED-FUNCTION T))|
         CONDITIONS::|(PCL::FAST-METHOD PRINT-OBJECT (UNBOUND-VARIABLE T))|
         CONDITIONS::|(PCL::FAST-METHOD PRINT-OBJECT (PRINT-NOT-READABLE T))|
         CONDITIONS::|(PCL::FAST-METHOD PRINT-OBJECT (CELL-ERROR T))|
         CONDITIONS::|(PCL::FAST-METHOD PRINT-OBJECT (STREAM-ERROR T))|
         CONDITIONS::|(PCL::FAST-METHOD PRINT-OBJECT (ARITHMETIC-ERROR T))|
         CONDITIONS::|(PCL::FAST-METHOD PRINT-OBJECT (END-OF-FILE T))|
         CONDITIONS::|(PCL::FAST-METHOD PRINT-OBJECT (SIMPLE-CONDITION T))|
         CONDITIONS::|(PCL::FAST-METHOD PRINT-OBJECT (PACKAGE-ERROR T))|)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION
             (COMMON-LISP::T COMMON-LISP::T COMMON-LISP::T
                 COMMON-LISP::T)
             COMMON-LISP::T)
         CONDITIONS::|(PCL::FAST-METHOD MAKE-LOAD-FORM (CONDITION))|
         CONDITIONS::|(PCL::FAST-METHOD PRINT-OBJECT (CONDITION T))|)) 
(COMMON-LISP::PROCLAIM
    '(COMMON-LISP::FTYPE
         (COMMON-LISP::FUNCTION (COMMON-LISP::T) COMMON-LISP::T)
         CONDITIONS::CONDITIONP CONDITIONS::IS-CONDITION
         CONDITIONS::IS-WARNING CONDITIONS::DEFAULT-REPORT)) 