
(IN-PACKAGE "CONDITIONS") 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T) *)
            |(PCL::FAST-METHOD PRINT-OBJECT (CASE-FAILURE T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (END-OF-FILE T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (PACKAGE-ERROR T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (UNBOUND-VARIABLE T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (UNDEFINED-FUNCTION T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (ABORT-FAILURE T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (INTERNAL-ERROR T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (INTERNAL-SIMPLE-ERROR T))|
            COERCE-TO-CONDITION
            |(PCL::FAST-METHOD PRINT-OBJECT (SIMPLE-CONDITION T))|
            |(PCL::FAST-METHOD PRINT-OBJECT (TYPE-ERROR T))|)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T) *) RESTART-PRINT
            EXECUTE-DEBUGGER-COMMAND)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T T *) *) CLCS-UNIVERSAL-ERROR-HANDLER)) 
(PROCLAIM '(FTYPE (FUNCTION (T T *) T) CERROR)) 
(PROCLAIM '(FTYPE (FUNCTION (T T T) T) ACCUMULATE-CASES)) 
(PROCLAIM '(FTYPE (FUNCTION (T T T *) T) SET-INTERNAL-ERROR)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T T T) T)
            |(PCL::FAST-METHOD PRINT-OBJECT (CONDITION T))|)) 
(PROCLAIM
    '(FTYPE (FUNCTION NIL *) ABORT CONTINUE MUFFLE-WARNING
            SYSTEM::BREAK-RESUME SYSTEM::BREAK-HELP)) 
(PROCLAIM
    '(FTYPE (FUNCTION NIL T) KCL-TOP-RESTARTS INSTALL-CLCS-SYMBOLS
            REVERT-CLCS-SYMBOLS READ-EVALUATED-FORM
            INITIALIZE-INTERNAL-ERROR-TABLE READ-DEBUG-COMMAND)) 
(PROCLAIM '(FTYPE (FUNCTION (*) *) INVOKE-DEBUGGER CLCS-COMPILE)) 
(PROCLAIM
    '(FTYPE (FUNCTION (*) T) COMPUTE-RESTARTS SYSTEM::CLCS-BREAK-QUIT
            BREAK SHOW-RESTARTS MAKE-RESTART)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) *) INVOKE-RESTART-INTERACTIVELY STORE-VALUE
            USE-VALUE COMPILER::CMP-TOPLEVEL-EVAL CLCS-ERROR-SET
            SIMPLE-ASSERTION-FAILURE
            SYSTEM::CLCS-BREAK-LEVEL-INVOKE-RESTART)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T) T) RESTART-NAME UNIQUE-ID REVERT-SYMBOL
            MAKE-KCL-TOP-RESTART FIND-KCL-TOP-RESTART
            RESTART-REPORT-FUNCTION SYSTEM::CLCS-TERMINAL-INTERRUPT
            RESTART-FUNCTION RESTART-INTERACTIVE-FUNCTION CONDITIONP
            CONDITION-CLASS-P RESET-FUNCTION CONDITION-BACKTRACE
            ESCAPE-SPECIAL-CASES-REPLACE STANDARD-DEBUGGER
            SIMPLE-CONDITION-CLASS-P RESTART-P)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T *) *) MAKE-CONDITION INVOKE-RESTART
            CLCS-COMPILE-FILE CLCS-LOAD CLCS-OPEN ERROR)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T *) T) FIND-RESTART SYSTEM::CLCS-BREAK-LEVEL
            WARN SIGNAL)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) *) RESTART-REPORT ASSERT-PROMPT
            PARSE-KEYWORD-PAIRS)) 
(PROCLAIM
    '(FTYPE (FUNCTION (T T) T) INSTALL-SYMBOL
            INTERNAL-SIMPLE-ERROR-PRINTER ASSERT-REPORT
            SIMPLE-CONDITION-PRINTER)) 